import Map from 'ol/Map';import View from 'ol/View';import TileLayer from 'ol/layer/Tile';import OSM from 'ol/source/OSM';import TileWMS from 'ol/source/TileWMS';import WMTS from 'ol/source/WMTS';import WMTSTileGrid from 'ol/tilegrid/WMTS';import {transformExtent} from 'ol/proj';
import type {StudyExtent} from '../components/MapPanel';import type {BuiltInMapSourceId} from '../core/appSettings';import type {ReportMapSource} from '../core/reportMapSources';import {createExternalMapSource} from './externalMapLayers';
import {COPERNICUS_VHR_2021_LAYER,COPERNICUS_VHR_2021_WMS} from './ogc';
const resolutions=Array.from({length:20},(_,zoom)=>156543.03392804097/2**zoom),matrixIds=resolutions.map((_,zoom)=>String(zoom));
function builtInSource(id:BuiltInMapSourceId){
 if(id==='osm')return new OSM({crossOrigin:'anonymous'});
 if(id==='ign-topographic')return new WMTS({url:'https://www.ign.es/wmts/mapa-raster',layer:'MTN',matrixSet:'GoogleMapsCompatible',format:'image/jpeg',projection:'EPSG:3857',tileGrid:new WMTSTileGrid({origin:[-20037508.342789244,20037508.342789244],resolutions,matrixIds}),style:'default',crossOrigin:'anonymous'});
 if(id==='pnoa')return new WMTS({url:'https://www.ign.es/wmts/pnoa-ma',layer:'OI.OrthoimageCoverage',matrixSet:'GoogleMapsCompatible',format:'image/jpeg',projection:'EPSG:3857',tileGrid:new WMTSTileGrid({origin:[-20037508.342789244,20037508.342789244],resolutions,matrixIds}),style:'default',crossOrigin:'anonymous'});
 if(id==='copernicus-vhr-2021')return new TileWMS({url:COPERNICUS_VHR_2021_WMS,params:{LAYERS:COPERNICUS_VHR_2021_LAYER,TILED:true,FORMAT:'image/jpeg'},crossOrigin:'anonymous'});
 const aerial=id==='AMS_1956-1957'||id==='Interministerial_1973-1986',minutas=id==='Minutas';return new TileWMS({url:aerial?'https://www.ign.es/wms/pnoa-historico':minutas?'https://www.ign.es/wms/minutas-cartograficas':'https://www.ign.es/wms/primera-edicion-mtn',params:{LAYERS:id,TILED:true,FORMAT:aerial?'image/jpeg':'image/png',TRANSPARENT:false},projection:'EPSG:3857',crossOrigin:'anonymous'});
}
function composite(host:HTMLElement,width:number,height:number){const output=document.createElement('canvas'),context=output.getContext('2d');if(!context)throw new Error('No se pudo preparar el mapa del informe.');output.width=width;output.height=height;context.fillStyle='#d9ddd7';context.fillRect(0,0,width,height);for(const canvas of host.querySelectorAll('canvas')){if(!canvas.width)continue;const opacity=Number(canvas.parentElement?.style.opacity||canvas.style.opacity||'1'),match=canvas.style.transform.match(/^matrix\(([^)]+)\)$/);context.save();context.globalAlpha=Number.isFinite(opacity)?opacity:1;if(match){const m=match[1].split(',').map(Number);context.setTransform(m[0],m[1],m[2],m[3],m[4],m[5])}context.drawImage(canvas,0,0);context.restore()}return output.toDataURL('image/png')}
export async function renderReportMapSource(source:ReportMapSource,extent:StudyExtent,width=1600,height=900){if(source.terrain3d)throw new Error('El modelo 3D utiliza su renderizador específico.');const host=document.createElement('div');host.style.cssText=`position:fixed;left:-12000px;top:0;width:${width}px;height:${height}px`;document.body.appendChild(host);const tileSource=source.external?createExternalMapSource(source.external):source.builtIn?builtInSource(source.builtIn.id):null;if(!tileSource){host.remove();throw new Error('La base seleccionada ya no está disponible.')}const view=new View({projection:'EPSG:3857'}),map=new Map({target:host,layers:[new TileLayer({source:tileSource})],view,controls:[]});view.fit(transformExtent(extent,'EPSG:4326','EPSG:3857'),{size:[width,height]});try{await new Promise<void>((resolve,reject)=>{const timeout=window.setTimeout(()=>reject(new Error(`La capa «${source.name}» no terminó de cargarse para el informe.`)),15000);map.once('rendercomplete',()=>{window.clearTimeout(timeout);resolve()});map.renderSync()});return composite(host,width,height)}finally{map.setTarget(undefined);host.remove()}}
