import { jsPDF } from 'jspdf';
import {getLanguage,locale,translateText} from '../core/i18n';
import type { Barrier, Connectivity, ContourResult, GeoPoint, IsochroneResult, LcpCorridorResult, RouteResult, ViewshedObserverResult } from '../types';
import type { StudyExtent } from '../components/MapPanel';
import { MODELS } from '../core/costModels';

export type ReportPageSize='a4'|'a3'|'a2';
export interface ReportOptions { navigation:boolean; pnoaOverview:boolean; individualRoutePages:boolean; terrain3d:boolean; historical:boolean; pointList:boolean; barrierList:boolean; pageSize:ReportPageSize }
export interface ReportRoute { result:RouteResult; color:string }
export type ReportAnalysis=
  |{kind:'route-simple';title:string;includeTechnicalPage?:boolean}
  |{kind:'route-comparison';title:string;includeIndividualPages?:boolean;includeProfilePages?:boolean;individualMaps?:Record<string,string>}
  |{kind:'multiroute';title:string;includeTechnicalPage?:boolean}
  |{kind:'multipoint';title:string;matrix:(number|null)[][];unit:string;includeMatrixPage?:boolean;includeTechnicalPage?:boolean}
  |{kind:'isochrones';title:string;result:IsochroneResult;surfaceImage?:string;includeTechnicalPage?:boolean}
  |{kind:'contours';title:string;result:ContourResult;includeTechnicalPage?:boolean}
  |{kind:'corridor';title:string;result:LcpCorridorResult;surfaceImage?:string;includeTechnicalPage?:boolean}
  |{kind:'viewshed';title:string;result:ViewshedObserverResult;surfaceImage?:string;limitation:string;includeTechnicalPage?:boolean};
export interface ReportMapPage {id:string;title:string;image:string;attribution?:string;legend?:{label:string;color:string}[];legendColumns?:1|2}
export interface ReportTextPage {id:string;title:string;lines:string[]}
export type ReportMapBase='cartographic'|'orthophoto'|'historical'|'terrain3d';
export type ReportOverlayPosition='top-left'|'top-right'|'bottom-left'|'bottom-right';
export interface RouteSimpleReportSettings {
  base:ReportMapBase;includeOutbound:boolean;includeReturn:boolean;includeAlternatives:boolean;includeTechnicalPage:boolean;
  showPoints:boolean;showPointLabels:boolean;showBarriers:boolean;showCorridors:boolean;showCrossings:boolean;showPointsOfInterest:boolean;
  showNorthArrow:boolean;northPosition:ReportOverlayPosition;showScale:boolean;scalePosition:ReportOverlayPosition;scaleM:'auto'|number;
  inclination:number;orientation:number;
}
export interface RouteComparisonReportSettings {
  base:ReportMapBase;selectedModels:string[];includeCombinedMap:boolean;includeIndividualPages:boolean;includeProfilePages:boolean;
  showPoints:boolean;showPointLabels:boolean;showBarriers:boolean;showCorridors:boolean;showCrossings:boolean;showPointsOfInterest:boolean;
  showNorthArrow:boolean;northPosition:ReportOverlayPosition;showScale:boolean;scalePosition:ReportOverlayPosition;scaleM:'auto'|number;
  inclination:number;orientation:number;
}
export interface MultipointReportSettings {
  base:ReportMapBase;includeCombinedMap:boolean;includeMatrixPage:boolean;includeAlternatives:boolean;includeTechnicalPage:boolean;
  showPoints:boolean;showPointLabels:boolean;showBarriers:boolean;showCorridors:boolean;showCrossings:boolean;showPointsOfInterest:boolean;
  showNorthArrow:boolean;northPosition:ReportOverlayPosition;showScale:boolean;scalePosition:ReportOverlayPosition;scaleM:'auto'|number;
  inclination:number;orientation:number;
}
export interface CorridorReportSettings {
  base:ReportMapBase;includeCombinedMap:boolean;includeTechnicalPage:boolean;surfaceOpacity:number;
  showPoints:boolean;showPointLabels:boolean;showBarriers:boolean;showCorridors:boolean;showCrossings:boolean;showPointsOfInterest:boolean;
  showNorthArrow:boolean;northPosition:ReportOverlayPosition;showScale:boolean;scalePosition:ReportOverlayPosition;scaleM:'auto'|number;
  inclination:number;orientation:number;
}
export interface ViewshedReportSettings extends CorridorReportSettings {observerId:string}
export interface ReportComposition {pageSize:ReportPageSize;items:{id:string;title:string;kind:'map'|'section'}[];routeSimple?:RouteSimpleReportSettings;routeComparison?:RouteComparisonReportSettings;multipoint?:MultipointReportSettings;multiroute?:MultipointReportSettings;corridor?:CorridorReportSettings;isochrones?:CorridorReportSettings;contours?:CorridorReportSettings;viewshed?:ViewshedReportSettings}
interface ReportInput {
  options:ReportOptions; points:GeoPoint[]; barriers:Barrier[]; routes:ReportRoute[]; extent:StudyExtent;
  navigationImage?:string; pnoaImage?:string; terrain3dImage?:string; historicalImage?:string;
  navigationLabel:string; historicalLabel:string; resolution:number; paletteLabel:string; rasterSize?:[number,number];
  areaKm2:number; cells:number; mdtSource:string; connectivity:Connectivity; criticalSlopePercent:number;
  analysis?:ReportAnalysis; projectName?:string; generatedAt?:string; rasterCrs?:string;
  customMapPages?:ReportMapPage[];
  customTextPages?:ReportTextPage[];
  customOrder?:string[];
}

const MARGIN=12;
function imageFormat(data:string){return data.startsWith('data:image/jpeg')?'JPEG':'PNG'}
function pageHeader(pdf:jsPDF,title:string,subtitle?:string){const pageW=pdf.internal.pageSize.getWidth();pdf.setFillColor(10,23,17);pdf.rect(0,0,pageW,20,'F');pdf.setTextColor(216,255,85);pdf.setFontSize(16);pdf.setFont('helvetica','bold');pdf.text('VS',MARGIN,12);pdf.setFont('helvetica','normal');pdf.setTextColor(235,241,237);pdf.setFontSize(12);pdf.text('ViaSpania',25,12);pdf.text(title,58,12);if(subtitle){pdf.setTextColor(155,169,160);pdf.setFontSize(8);pdf.text(subtitle,pageW-MARGIN,12,{align:'right'})}pdf.setTextColor(25,35,30)}
export function imageContainRect(imageWidth:number,imageHeight:number,x:number,y:number,width:number,height:number){const ratio=Math.min(width/imageWidth,height/imageHeight),drawWidth=imageWidth*ratio,drawHeight=imageHeight*ratio;return{x:x+(width-drawWidth)/2,y:y+(height-drawHeight)/2,width:drawWidth,height:drawHeight}}
function addImageContained(pdf:jsPDF,data:string,x:number,y:number,width:number,height:number){const properties=pdf.getImageProperties(data),rect=imageContainRect(properties.width,properties.height,x,y,width,height);pdf.setFillColor(242,244,242);pdf.rect(x,y,width,height,'F');pdf.addImage(data,imageFormat(data),rect.x,rect.y,rect.width,rect.height,undefined,'FAST')}
function project([lon,lat]:[number,number],[west,south,east,north]:StudyExtent,x:number,y:number,w:number,h:number){return [x+(lon-west)/(east-west)*w,y+(north-lat)/(north-south)*h] as const}
function drawRoutes(pdf:jsPDF,routes:ReportRoute[],extent:StudyExtent,x:number,y:number,w:number,h:number){pdf.setLineCap('round');pdf.setLineJoin('round');for(const route of routes){const coordinates=route.result.coordinates??[];if(coordinates.length<2)continue;const points=coordinates.map(point=>project(point,extent,x,y,w,h));pdf.setDrawColor(8,20,23);pdf.setLineWidth(2.7);for(let i=1;i<points.length;i++)pdf.line(...points[i-1],...points[i]);pdf.setDrawColor(route.color);pdf.setLineWidth(1.25);for(let i=1;i<points.length;i++)pdf.line(...points[i-1],...points[i])}}
function drawPointsAndBarriers(pdf:jsPDF,input:ReportInput,x:number,y:number,w:number,h:number){for(const barrier of input.barriers){const points=barrier.coordinates.map(point=>project(point,input.extent,x,y,w,h));pdf.setDrawColor(barrier.kind==='absolute'?'#ff3030':'#ffb340');pdf.setLineWidth(1);for(let i=1;i<points.length;i++)pdf.line(...points[i-1],...points[i])}for(const point of input.points){const [px,py]=project([point.lon,point.lat],input.extent,x,y,w,h);pdf.setFillColor(point.role==='inicio'?'#59d2ff':point.role==='final'?'#ff796f':'#d8ff55');pdf.setDrawColor('#ffffff');pdf.circle(px,py,2,'FD')}}
function routeConfiguration(route:RouteResult,input:ReportInput){const settings=route.settings;const connectivity=settings?.connectivity??input.connectivity;const parts=[`${connectivity} vecinos`];if(route.rank)parts.unshift(`ruta subóptima · rango ${route.rank}${route.rank>1&&route.costIncreasePercent!=null?` · +${route.costIncreasePercent.toFixed(1)} % · ${route.sharedCellsPercent?.toFixed(0)??'—'} % compartido`:''}`);if(route.model==='wheeled')parts.push(`pendiente crítica ${settings?.criticalSlopePercent??input.criticalSlopePercent}%`);if(route.model==='ardigo'&&settings?.ardigoSpeedMs)parts.push(`velocidad ${settings.ardigoSpeedMs.toFixed(1)} m/s`);return parts.join(' · ')}
function connectivityDetail(value:Connectivity){return value===4?'4 vecinos: movimientos cardinales, sin diagonales.':value===8?'8 vecinos: movimientos cardinales y diagonales inmediatas.':'16 vecinos: añade conexiones extendidas para aumentar las direcciones posibles.'}
function calculationParameterRows(route:RouteResult,input:ReportInput){const settings=route.settings,connectivity=settings?.connectivity??input.connectivity,critical=route.model==='wheeled'?settings?.criticalSlopePercent??input.criticalSlopePercent:null,speed=route.model==='ardigo'?settings?.ardigoSpeedMs:null;return[`Conectividad utilizada: ${connectivity} vecinos.`,connectivityDetail(connectivity),critical==null?'Pendiente crítica: no utilizada por este perfil.':`Pendiente crítica utilizada: sí · ${critical} %.`,route.model!=='ardigo'?'Velocidad configurable: no aplicable a este perfil.':speed==null?'Velocidad seleccionada: no.':`Velocidad seleccionada: sí · ${speed.toFixed(2)} m/s.`,`Resolución del MDT: ${input.resolution} m.`,`Fuente del MDT: ${input.mdtSource}.`]}
const TECHNICAL_TEXT_SIZE=8.5;
function drawTechnicalTitle(pdf:jsPDF,title:string,x:number,y:number){pdf.setFont('helvetica','bold');pdf.setFontSize(TECHNICAL_TEXT_SIZE);pdf.setTextColor(25,35,30);pdf.text(title,x,y);pdf.setFont('helvetica','normal')}
function drawTechnicalRows(pdf:jsPDF,rows:string[],x:number,startY:number,maxWidth:number,lineGap=7){pdf.setFontSize(TECHNICAL_TEXT_SIZE);pdf.setTextColor(25,35,30);rows.forEach((row,index)=>{const separator=row.indexOf(':');if(separator<0){pdf.setFont('helvetica','normal');pdf.text(row,x,startY+index*lineGap,{maxWidth});return}const label=row.slice(0,separator+1),value=row.slice(separator+1);pdf.setFont('helvetica','bold');pdf.text(label,x,startY+index*lineGap);const offset=pdf.getTextWidth(label)+1;pdf.setFont('helvetica','normal');pdf.text(value,x+offset,startY+index*lineGap,{maxWidth:Math.max(8,maxWidth-offset)})});pdf.setFont('helvetica','normal')}
function drawLegend(pdf:jsPDF,input:ReportInput,startY:number,maxRows=12){pdf.setFontSize(10);pdf.text('Resultados y configuración',MARGIN,startY);let y=startY+7;for(const route of input.routes.slice(0,maxRows)){pdf.setDrawColor(route.color);pdf.setLineWidth(2);pdf.line(MARGIN,y-1,MARGIN+10,y-1);pdf.setTextColor(25,35,30);pdf.setFontSize(7.5);const result=route.result;pdf.text(`${MODELS[result.model].name} · coste ${result.cost.toFixed(2)} ${result.unit} · distancia ${result.distanceM.toFixed(1)} m · ${routeConfiguration(result,input)}`,MARGIN+14,y);y+=5.5}return y}
function addNewPage(pdf:jsPDF,title:string,subtitle:string|undefined,format:ReportPageSize){pdf.addPage(format,'landscape');pageHeader(pdf,title,subtitle)}
function drawMapLegend(pdf:jsPDF,entries:{label:string;color:string}[],pageW:number,pageH:number,columns:1|2=1){if(!entries.length)return;const columnCount=Math.min(columns,entries.length),rows=Math.ceil(entries.length/columnCount),rowH=columns===2?4.6:6,columnW=Math.min(82,Math.max(46,...entries.map(entry=>entry.label.length*1.45+19))),width=columnW*columnCount+8,height=11+rows*rowH,x=pageW-MARGIN-width-5,y=pageH-28-height;pdf.setFillColor(255,255,255);pdf.setDrawColor(50,65,57);pdf.roundedRect(x,y,width,height,2,2,'FD');pdf.setTextColor(25,35,30);pdf.setFontSize(7.5);pdf.text('Perfiles calculados',x+4,y+6.5);entries.forEach((entry,index)=>{const column=Math.floor(index/rows),row=index%rows,itemX=x+4+column*columnW,rowY=y+11+row*rowH;pdf.setDrawColor(entry.color);pdf.setLineWidth(1.7);pdf.line(itemX,rowY-1,itemX+9,rowY-1);pdf.setFontSize(6.2);pdf.setTextColor(25,35,30);pdf.text(entry.label,itemX+12,rowY,{maxWidth:columnW-14})})}

export function createProjectReport(input:ReportInput):Uint8Array{
  const format=input.options.pageSize??'a4',pdf=new jsPDF({unit:'mm',format,orientation:'landscape',compress:true}),pageW=pdf.internal.pageSize.getWidth(),pageH=pdf.internal.pageSize.getHeight(),contentW=pageW-MARGIN*2;let hasPage=false;
  if(getLanguage()==='en'){const originalText=pdf.text.bind(pdf);pdf.text=((text:string|string[],...args:unknown[])=>originalText(Array.isArray(text)?text.map(translateText):translateText(text),...(args as Parameters<typeof originalText> extends [unknown,...infer R]?R:never))) as typeof pdf.text}
  const begin=(title:string,subtitle?:string)=>{if(hasPage)addNewPage(pdf,title,subtitle,format);else{pageHeader(pdf,title,subtitle);hasPage=true}};
  const [west,south,east,north]=input.extent;
  const generatedAt=input.generatedAt??new Date().toISOString(),reportLocale=locale();
  if(input.options.navigation&&input.navigationImage){begin('Mapa de navegación',input.navigationLabel);const mapW=contentW*.66,mapH=pageH-58,sideX=MARGIN+mapW+8,sideW=pageW-sideX-MARGIN;addImageContained(pdf,input.navigationImage,MARGIN,26,mapW,mapH);pdf.setFontSize(10);pdf.text('Área de estudio y datos de entrada',sideX,31);pdf.setFontSize(8);const rows=[`Extensión: ${input.areaKm2.toLocaleString(reportLocale,{maximumFractionDigits:3})} km²`,`Límites: ${west.toFixed(6)}, ${south.toFixed(6)} — ${east.toFixed(6)}, ${north.toFixed(6)}`,`Malla: ${input.cells.toLocaleString(reportLocale)} celdas${input.rasterSize?` · ${input.rasterSize[0]} × ${input.rasterSize[1]}`:''}`,`MDT utilizado: MDT${String(input.resolution).padStart(2,'0')} · ${input.resolution} m`,`Fuente del MDT: ${input.mdtSource}`,`Puntos seleccionados: ${input.points.length}`,`Barreras: ${input.barriers.length}`];rows.forEach((row,index)=>pdf.text(row,sideX,41+index*7,{maxWidth:sideW}));if(input.options.pointList){pdf.setFontSize(9);pdf.text('Puntos',sideX,96);pdf.setFontSize(7);input.points.slice(0,13).forEach((point,index)=>pdf.text(`${point.name} · ${point.role} · ${point.lat.toFixed(6)}, ${point.lon.toFixed(6)}`,sideX,103+index*5,{maxWidth:sideW}))}if(input.options.barrierList&&input.barriers.length){const start=Math.min(pageH-34,108+Math.min(input.points.length,13)*5);pdf.setFontSize(9);pdf.text('Barreras',sideX,start);pdf.setFontSize(7);input.barriers.slice(0,5).forEach((barrier,index)=>pdf.text(`${index+1}. ${barrier.kind==='absolute'?'Absoluta':`Penalización ×${barrier.value}`} · ${barrier.coordinates.length} vértices`,sideX,start+7+index*5))}}
  if(input.options.pnoaOverview&&input.pnoaImage){begin('Ortofotografía PNOA y rutas',`${input.routes.length} perfil(es) calculado(s)`);const mapX=MARGIN,mapY=26,mapW=contentW,mapH=pageH*.57;addImageContained(pdf,input.pnoaImage,mapX,mapY,mapW,mapH);drawRoutes(pdf,input.routes,input.extent,mapX,mapY,mapW,mapH);drawPointsAndBarriers(pdf,input,mapX,mapY,mapW,mapH);drawLegend(pdf,input,mapY+mapH+11,10);pdf.setFontSize(7);pdf.setTextColor(95,105,98);pdf.text('Ortofotografía: IGN/CNIG. Las rutas se calculan exclusivamente sobre el modelo de elevaciones y las barreras definidas.',MARGIN,pageH-11);if(input.routes.length>10){addNewPage(pdf,'Leyenda completa de modelos',undefined,format);drawLegend(pdf,input,32,30)}}
  if(input.options.individualRoutePages&&input.pnoaImage)for(const route of input.routes){begin(`Perfil: ${MODELS[route.result.model].name}`,routeConfiguration(route.result,input));const x=MARGIN,y=27,w=205,h=137;addImageContained(pdf,input.pnoaImage,x,y,w,h);drawRoutes(pdf,[route],input.extent,x,y,w,h);drawPointsAndBarriers(pdf,input,x,y,w,h);pdf.setFontSize(9);pdf.text(`Coste: ${route.result.cost.toFixed(2)} ${route.result.unit}`,224,38);pdf.text(`Distancia: ${route.result.distanceM.toFixed(1)} m`,224,47);pdf.text(`Ascenso: ${route.result.ascentM.toFixed(1)} m`,224,56);pdf.text(`Descenso: ${route.result.descentM.toFixed(1)} m`,224,65);pdf.text(`Conectividad: ${route.result.settings?.connectivity??input.connectivity}`,224,74);if(route.result.model==='wheeled')pdf.text(`Pendiente crítica: ${route.result.settings?.criticalSlopePercent??input.criticalSlopePercent}%`,224,83);pdf.setDrawColor(route.color);pdf.setLineWidth(3);pdf.line(224,95,270,95)}
  if(input.options.terrain3d&&input.terrain3dImage){begin('Visor 3D del terreno y las rutas',`Paleta ${input.paletteLabel}`);addImageContained(pdf,input.terrain3dImage,MARGIN,27,contentW,pageH-55);pdf.setFontSize(8);pdf.text(`Rutas representadas: ${input.routes.length}. Los colores corresponden a la leyenda de resultados de la ortofotografía.`,MARGIN,pageH-12)}
  if(input.options.historical&&input.historicalImage){begin('Cartografía histórica',input.historicalLabel);addImageContained(pdf,input.historicalImage,MARGIN,27,contentW,pageH-55);pdf.setFontSize(7);pdf.setTextColor(90,100,94);pdf.text('Fuente: Instituto Geográfico Nacional de España / Centro Nacional de Información Geográfica.',MARGIN,pageH-12)}
  const maps=input.customMapPages??[],texts=input.customTextPages??[],order=input.customOrder??[...maps.map(page=>page.id),...texts.map(page=>page.id)];for(const id of order){const map=maps.find(page=>page.id===id),text=texts.find(page=>page.id===id);if(map){begin(map.title,map.attribution);addImageContained(pdf,map.image,MARGIN,27,contentW,pageH-55);if(map.legend)drawMapLegend(pdf,map.legend,pageW,pageH,map.legendColumns);if(map.attribution){pdf.setFontSize(7);pdf.setTextColor(90,100,94);pdf.text(map.attribution,MARGIN,pageH-12,{maxWidth:contentW})}}else if(text){begin(text.title,'Contenido seleccionado en el compositor');pdf.setFontSize(8);pdf.setTextColor(25,35,30);text.lines.slice(0,30).forEach((line,index)=>pdf.text(line,MARGIN,31+index*6,{maxWidth:contentW}))}}
  const analysis=input.analysis;
  if(analysis?.kind==='route-simple'&&analysis.includeTechnicalPage){begin('Configuración técnica de Ruta simple',`${input.routes.length} cálculo(s) seleccionado(s) · ${generatedAt}`);const first=input.routes[0]?.result,profile=first?MODELS[first.model]:null;drawTechnicalTitle(pdf,'Perfil de desplazamiento',MARGIN,33);const profileRows=profile?[`Nombre: ${profile.name}`,`Familia: ${profile.family}`,`Magnitud de coste: ${profile.unit}`,`Direccional: ${profile.directional?'sí; ida y vuelta pueden diferir':'no'}`,`Descripción: ${profile.description}`,`Referencia: ${profile.citation}`]:['No hay una ruta seleccionada.'];drawTechnicalRows(pdf,profileRows,MARGIN,43,contentW*.46);const sideX=MARGIN+contentW*.5;drawTechnicalTitle(pdf,'Parámetros efectivos por cálculo',sideX,33);let parameterY=43;for(const route of input.routes){pdf.setTextColor(route.color);drawTechnicalTitle(pdf,route.result.direction,sideX,parameterY);parameterY+=7;drawTechnicalRows(pdf,calculationParameterRows(route.result,input),sideX,parameterY,contentW*.48,5.5);parameterY+=calculationParameterRows(route.result,input).length*5.5+4}let y=104;drawTechnicalTitle(pdf,'Resultados incluidos',MARGIN,y);y+=10;for(const [index,route] of input.routes.entries()){const result=route.result;pdf.setDrawColor(route.color);pdf.setLineWidth(2.5);pdf.line(MARGIN,y-2,MARGIN+12,y-2);pdf.setFont('helvetica','normal');pdf.setFontSize(TECHNICAL_TEXT_SIZE);pdf.text(`${index+1}. ${result.direction} · ${result.distanceM.toFixed(1)} m · coste ${result.cost.toFixed(2)} ${result.unit} · ascenso ${result.ascentM.toFixed(1)} m · descenso ${result.descentM.toFixed(1)} m`,MARGIN+17,y,{maxWidth:contentW-17});y+=9}}
  if(analysis?.kind==='route-simple')for(const route of input.routes){const result=route.result,profile=MODELS[result.model],direction=result.direction.includes('final→inicio')?'Vuelta':'Ida';begin(`Resultado individual · ${direction}`,`${profile.name} · ${result.direction}`);pdf.setDrawColor(route.color);pdf.setLineWidth(4);pdf.line(MARGIN,31,MARGIN+35,31);drawTechnicalTitle(pdf,profile.name,MARGIN,45);const resultRows=[`Dirección calculada: ${result.direction}`,`Coste acumulado: ${result.cost.toFixed(2)} ${result.unit}`,`Distancia: ${result.distanceM.toFixed(1)} m`,`Ascenso acumulado: ${result.ascentM.toFixed(1)} m`,`Descenso acumulado: ${result.descentM.toFixed(1)} m`,`Vértices del trazado: ${result.coordinates?.length??0}`];drawTechnicalRows(pdf,resultRows,MARGIN,58,contentW*.46,9);const sideX=MARGIN+contentW*.5;drawTechnicalTitle(pdf,'Configuración utilizada',sideX,45);drawTechnicalRows(pdf,calculationParameterRows(result,input),sideX,58,contentW*.48,8);drawTechnicalRows(pdf,[`Perfil: ${profile.description}`,`Referencia: ${profile.citation}`],MARGIN,130,contentW,12)}
  if(analysis?.kind==='route-comparison')for(const route of input.routes){const result=route.result,profile=MODELS[result.model];if(analysis.includeIndividualPages){begin(`Resultado individual · ${profile.name}`,result.direction);const map=analysis.individualMaps?.[result.model],sideX=map?MARGIN+contentW*.68:MARGIN+contentW*.5;if(map)addImageContained(pdf,map,MARGIN,32,contentW*.63,pageH-62);pdf.setDrawColor(route.color);pdf.setLineWidth(4);pdf.line(sideX,34,sideX+34,34);drawTechnicalTitle(pdf,'Resultado calculado',sideX,48);drawTechnicalRows(pdf,[`Coste acumulado: ${result.cost.toFixed(2)} ${result.unit}`,`Distancia: ${result.distanceM.toFixed(1)} m`,`Ascenso acumulado: ${result.ascentM.toFixed(1)} m`,`Descenso acumulado: ${result.descentM.toFixed(1)} m`,`Vértices del trazado: ${result.coordinates?.length??0}`,`Dirección: ${result.direction}`],sideX,60,pageW-sideX-MARGIN,8);drawTechnicalTitle(pdf,'Configuración efectiva',sideX,116);drawTechnicalRows(pdf,calculationParameterRows(result,input),sideX,127,pageW-sideX-MARGIN,7)}if(analysis.includeProfilePages){begin(`Perfil y parámetros · ${profile.name}`,profile.citation);pdf.setDrawColor(route.color);pdf.setLineWidth(4);pdf.line(MARGIN,31,MARGIN+38,31);drawTechnicalTitle(pdf,'Perfil de desplazamiento',MARGIN,47);drawTechnicalRows(pdf,[`Nombre: ${profile.name}`,`Familia: ${profile.family}`,`Magnitud de coste: ${profile.unit}`,`Direccional: ${profile.directional?'sí':'no'}`,`Descripción: ${profile.description}`,`Referencia: ${profile.citation}`],MARGIN,61,contentW*.46,9);drawTechnicalTitle(pdf,'Parámetros de esta ruta',MARGIN+contentW*.52,47);drawTechnicalRows(pdf,calculationParameterRows(result,input),MARGIN+contentW*.52,61,contentW*.46,9)}}
  if(analysis?.kind==='multipoint'&&analysis.includeMatrixPage!==false){begin(analysis.title,'Matriz dirigida de costes');pdf.setFontSize(8);pdf.text(`Fecha: ${generatedAt} · Conectividad: ${input.connectivity} vecinos · MDT${String(input.resolution).padStart(2,'0')}`,MARGIN,30);const matrix=analysis.matrix,cellW=Math.min(28,(pageW-MARGIN*2-36)/Math.max(1,matrix.length));pdf.setFontSize(7);matrix.forEach((row,r)=>row.forEach((value,c)=>pdf.text(value==null?'—':value.toFixed(1),MARGIN+36+c*cellW,42+r*6,{align:'right'})));input.points.slice(0,matrix.length).forEach((point,index)=>pdf.text(point.name,MARGIN,42+index*6,{maxWidth:32}));}
  if(analysis?.kind==='multipoint'&&analysis.includeTechnicalPage){const first=input.routes[0]?.result,profile=first?MODELS[first.model]:null;begin('Perfil y parámetros · Multipunto',`${input.routes.length} conexión(es) calculada(s)`);drawTechnicalTitle(pdf,'Perfil de desplazamiento',MARGIN,38);const rows=profile?[`Nombre: ${profile.name}`,`Familia: ${profile.family}`,`Magnitud de coste: ${profile.unit}`,`Direccional: ${profile.directional?'sí':'no'}`,`Descripción: ${profile.description}`,`Referencia: ${profile.citation}`]:['No hay conexiones calculadas.'];drawTechnicalRows(pdf,rows,MARGIN,52,contentW*.47,9);if(first){const sideX=MARGIN+contentW*.53;drawTechnicalTitle(pdf,'Parámetros efectivos',sideX,38);drawTechnicalRows(pdf,calculationParameterRows(first,input),sideX,52,contentW*.45,9);drawTechnicalRows(pdf,[`Conexiones incluidas: ${input.routes.length}`,`Puntos participantes: ${input.points.length}`],sideX,123,contentW*.45,11)}}
  if(analysis?.kind==='multiroute'&&analysis.includeTechnicalPage){const first=input.routes[0]?.result,profile=first?MODELS[first.model]:null;begin('Perfil y parámetros · Multirruta',`${input.routes.length} tramo(s) calculado(s)`);drawTechnicalTitle(pdf,'Perfil de desplazamiento',MARGIN,38);const rows=profile?[`Nombre: ${profile.name}`,`Familia: ${profile.family}`,`Magnitud de coste: ${profile.unit}`,`Direccional: ${profile.directional?'sí':'no'}`,`Descripción: ${profile.description}`,`Referencia: ${profile.citation}`]:['No hay tramos calculados.'];drawTechnicalRows(pdf,rows,MARGIN,52,contentW*.47,9);if(first){const sideX=MARGIN+contentW*.53;drawTechnicalTitle(pdf,'Parámetros efectivos',sideX,38);drawTechnicalRows(pdf,calculationParameterRows(first,input),sideX,52,contentW*.45,9);drawTechnicalRows(pdf,[`Tramos incluidos: ${input.routes.length}`,`Puntos de la secuencia: ${input.points.length}`],sideX,123,contentW*.45,11)}}
  if(analysis?.kind==='isochrones'&&analysis.includeTechnicalPage!==false){const result=analysis.result;begin(analysis.title,`${MODELS[result.model].name} · intervalo ${result.interval} ${result.unit}`);if(analysis.surfaceImage)addImageContained(pdf,analysis.surfaceImage,MARGIN,27,contentW*.68,pageH-53);const x=analysis.surfaceImage?MARGIN+contentW*.71:MARGIN;drawTechnicalRows(pdf,[`Niveles: ${new Set(result.lines.map(line=>line.level)).size}`,`Celdas accesibles: ${result.reachableCells.toLocaleString(reportLocale)}`,`Coste máximo: ${result.maxCost.toFixed(2)} ${result.unit}`,`Intervalo: ${result.interval} ${result.unit}`,`Modelo: ${MODELS[result.model].name}`,`Conectividad: ${input.connectivity} vecinos`,`Fuente: ${result.source}`],x,34,pageW-x-MARGIN,8)}
  if(analysis?.kind==='contours'&&analysis.includeTechnicalPage!==false){const result=analysis.result;begin(analysis.title,`Intervalo vertical ${result.intervalM.toFixed(1)} m`);drawTechnicalRows(pdf,[`Intervalo entre curvas: ${result.intervalM.toFixed(1)} m`,`Altitud mínima: ${result.minElevationM.toFixed(1)} m`,`Altitud máxima: ${result.maxElevationM.toFixed(1)} m`,`Segmentos vectoriales: ${result.lines.length.toLocaleString(reportLocale)}`,`Niveles representados: ${new Set(result.lines.map(line=>line.level)).size}`,`Resolución del MDT: ${result.resolutionM.toFixed(1)} m`,`Celdas nodata: ${result.nodataCells.toLocaleString(reportLocale)}`,`Fuente: ${result.source}`],MARGIN,38,contentW,9)}
  if(analysis?.kind==='corridor'&&analysis.includeTechnicalPage!==false){const result=analysis.result;begin(analysis.title,`${MODELS[result.model].name} · umbral +${result.thresholdPercent}%`);if(analysis.surfaceImage)addImageContained(pdf,analysis.surfaceImage,MARGIN,27,contentW*.68,pageH-53);const x=analysis.surfaceImage?MARGIN+contentW*.71:MARGIN;drawTechnicalRows(pdf,[`Coste óptimo: ${result.optimalCost.toFixed(2)} ${result.unit}`,`Umbral: +${result.thresholdPercent}%`,`Celdas del pasillo: ${result.corridorCells.toLocaleString(reportLocale)}`,`Modelo: ${MODELS[result.model].name}`,`Conectividad: ${input.connectivity} vecinos`,`Fuente: ${result.source}`],x,34,pageW-x-MARGIN,8)}
  if(analysis?.kind==='viewshed'&&analysis.includeTechnicalPage!==false){const result=analysis.result;begin(analysis.title,`Observador: ${result.observerName} · altura ${result.observerHeightM.toFixed(1)} m`);if(analysis.surfaceImage)addImageContained(pdf,analysis.surfaceImage,MARGIN,27,contentW*.68,pageH-62);const x=analysis.surfaceImage?MARGIN+contentW*.71:MARGIN,percentage=result.validCells?result.visibleCells/result.validCells*100:0;drawTechnicalRows(pdf,[`Coordenada: ${result.coordinate[1].toFixed(6)}, ${result.coordinate[0].toFixed(6)}`,`Elevación del terreno: ${result.groundElevationM.toFixed(1)} m`,`Altura usada en el cálculo: ${result.observerHeightM.toFixed(1)} m sobre el terreno`,`Altura total del punto de vista: ${(result.groundElevationM+result.observerHeightM).toFixed(1)} m`,`Celdas visibles: ${result.visibleCells.toLocaleString(reportLocale)} (${percentage.toFixed(1)}%)`,`Celdas válidas: ${result.validCells.toLocaleString(reportLocale)}`,`Resolución del MDT: ${input.resolution} m`],x,34,pageW-x-MARGIN,8);pdf.setFont('helvetica','normal');pdf.setFontSize(TECHNICAL_TEXT_SIZE);pdf.setTextColor(115,78,38);pdf.text(analysis.limitation,MARGIN,pageH-19,{maxWidth:contentW});}
  if(!hasPage){pageHeader(pdf,'Informe sin secciones cartográficas');hasPage=true;pdf.setFontSize(11);pdf.text('No se seleccionó ninguna sección disponible para exportar.',MARGIN,40)}
  const count=pdf.getNumberOfPages();for(let page=1;page<=count;page++){pdf.setPage(page);pdf.setFont('helvetica','normal');pdf.setTextColor(90,100,94);pdf.setFontSize(7);pdf.text(`ViaSpania · ${new Date().toLocaleString(reportLocale)} · Página ${page} de ${count}`,pageW-MARGIN,pageH-6,{align:'right'})}
  return new Uint8Array(pdf.output('arraybuffer'));
}
