import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { completeTutorial, shouldStartTutorial, tutorialCompleted } from '../core/tutorial';
import type { AppSettings } from '../core/appSettings';
import {useLanguage} from '../core/i18n';
import '../tutorial.css';

type WorkflowStep={selector:string;title:string;text:string;titleEn:string;textEn:string};
/**
 * Keep this sequence organised by work phase. New tools belong in the phase
 * where their input first becomes available, rather than at the end of the tour.
 */
export const WORKFLOW_STEPS:readonly WorkflowStep[]=[
  {selector:'[data-tutorial="new-project"]',title:'Crear proyecto',text:'Comience creando un proyecto para guardar el área de estudio, los elementos y los resultados. Indique un nombre y una ubicación para el archivo.',titleEn:'Create a project',textEn:'Start by creating a project to keep the study area, features and results together. Choose a name and location for the file.'},
  {selector:'[data-tutorial="open-project"]',title:'Abrir proyecto',text:'Si ya tiene un trabajo guardado, ábralo aquí antes de editarlo. ViaSpania recupera el área, los puntos, los elementos y los parámetros del proyecto.',titleEn:'Open a project',textEn:'If you already have saved work, open it here before editing it. ViaSpania restores its area, points, features and parameters.'},
  {selector:'.nav-panel',title:'1. Delimitar el área de estudio',text:'En Navegación, sitúe la zona de trabajo, pulse «Seleccionar área» y marque dos esquinas opuestas. El área determina la descarga y la resolución del modelo digital.',titleEn:'1. Define the study area',textEn:'In Navigation, locate the work area, select “Select area” and mark two opposite corners. The area determines the download and resolution of the digital model.'},
  {selector:'.model-load-panel',title:'2. Cargar el modelo digital',text:'Abra «Cargar modelo», elija un modelo de elevación y descárguelo, o importe un archivo local. Para calcular rutas y pendientes use un MDT; un MDS está destinado a análisis específicos de superficie.',titleEn:'2. Load the digital model',textEn:'Open “Load model”, choose and download an elevation model, or import a local file. Use a DTM for routes and slopes; a DSM is for specific surface analysis.'},
  {selector:'.dem-panel',title:'Comprobar el modelo digital',text:'El visor del modelo digital permite comprobar la cobertura, la paleta y las elevaciones antes de calcular. Las rutas y los análisis se superponen aquí cuando estén disponibles.',titleEn:'Check the digital model',textEn:'The digital-model viewer lets you check coverage, palette and elevations before calculation. Routes and analyses appear here when available.'},
  {selector:'.ortho-panel',title:'3. Situar los puntos',text:'En Selección añada el punto de inicio, el punto final y, cuando corresponda, puntos multipunto. Use la ortofotografía para ajustar su posición y editar los elementos seleccionados.',titleEn:'3. Place points',textEn:'In Selection, add the start, end and, when needed, multipoint locations. Use the orthophoto to refine their position and edit selected features.'},
  {selector:'.constraint-panel',title:'4. Añadir barreras y facilitadores',text:'Dibuje barreras, corredores, puentes, vados, túneles o puntos de interés en Selección. Configure después sus atributos en «Barreras y facilitadores»; estos elementos modifican los cálculos.',titleEn:'4. Add barriers and facilitators',textEn:'Draw barriers, corridors, bridges, fords, tunnels or points of interest in Selection. Then set their attributes in “Barriers and facilitators”; they modify calculations.'},
  {selector:'.options',title:'5. Configurar el análisis',text:'Elija el modo de cálculo, el perfil de desplazamiento y la conectividad. Algunas opciones, como pendiente crítica, velocidad o rutas subóptimas, solo aparecen cuando son pertinentes.',titleEn:'5. Configure the analysis',textEn:'Choose a calculation mode, travel profile and connectivity. Some options, such as critical slope, speed or alternative routes, appear only when relevant.'},
  {selector:'.calculation-access > div:first-child > button:nth-child(1)',title:'Calcular Ruta simple',text:'Use Ruta simple para obtener el recorrido de menor coste entre inicio y final. Calcule ida, vuelta o ambas, y abra el visor de ruta para interpretar trazado, coste y perfil altimétrico.',titleEn:'Calculate a simple route',textEn:'Use Simple route to obtain the least-cost path between start and end. Calculate outbound, return or both, then open the route viewer to interpret path, cost and elevation profile.'},
  {selector:'.calculation-access > div:first-child > button:nth-child(2)',title:'Comparar perfiles',text:'Ruta comparativa calcula los mismos extremos con varios perfiles sobre el mismo modelo y los mismos elementos. Úsela para contrastar coste, distancia y geometría.',titleEn:'Compare profiles',textEn:'Route comparison calculates the same endpoints with several profiles over the same model and features. Use it to contrast cost, distance and geometry.'},
  {selector:'.calculation-access > div:first-child > button:nth-child(3)',title:'Analizar varios puntos',text:'Multipunto genera una matriz dirigida de costes y las conexiones entre los primeros ocho puntos. Es útil cuando necesita comparar muchos orígenes y destinos.',titleEn:'Analyse several points',textEn:'Multipoint creates a directed cost matrix and connections among the first eight points. Use it when comparing many origins and destinations.'},
  {selector:'.calculation-access > div:first-child > button:nth-child(4)',title:'Construir una Multirruta',text:'Multirruta conecta los puntos en el orden de la lista. Revise el orden antes de calcular: cada par consecutivo forma un tramo del itinerario.',titleEn:'Build a multi-route',textEn:'Multi-route connects points in list order. Check the order before calculating: each consecutive pair forms one itinerary leg.'},
  {selector:'.calculation-access > div:first-child > button:nth-child(5)',title:'Explorar un Pasillo',text:'Pasillo delimita las alternativas próximas a la ruta óptima según el umbral elegido. Permite estudiar la anchura espacial de una solución, no solo una línea única.',titleEn:'Explore a corridor',textEn:'Corridor delineates alternatives close to the optimal route using the chosen threshold. It studies the spatial breadth of a solution, rather than a single line.'},
  {selector:'.calculation-access > div:nth-child(2)',title:'Analizar superficie y visibilidad',text:'Use Isócronas para coste acumulado desde uno o varios orígenes; Visibilidad para zonas visibles desde observadores; y Curvas de nivel para representar la altitud. Estos análisis requieren el modelo digital ya cargado.',titleEn:'Analyse surface and visibility',textEn:'Use Isochrones for accumulated cost from one or more origins; Viewshed for areas visible from observers; and Contours to represent elevation. These analyses require the loaded digital model.'},
  {selector:'.historical-panel',title:'6. Interpretar con cartografía',text:'Contraste rutas y elementos con mapas topográficos, históricos o capas externas en Cartografía. Todos los visores comparten el encuadre para facilitar la comparación.',titleEn:'6. Interpret with cartography',textEn:'Contrast routes and features with topographic, historical or external maps in Cartography. All viewers share the view to make comparison easier.'},
  {selector:'.open-3d-overlay',title:'Interpretar en 3D',text:'Abra «Visor 3D» para revisar relieve, inclinación y relación espacial entre el modelo, las rutas y los elementos. La flecha ↗ junto al cierre abre el visor en una ventana externa y mantiene la vista general en la principal. En la ventana externa, ↙ vuelve al visor integrado. Los controles y el proyecto permanecen sincronizados.',titleEn:'Interpret in 3D',textEn:'Open “3D View” to inspect relief, slope and spatial relations between the model, routes and features. The ↗ arrow next to Close opens a separate window while the main window keeps the project overview. In the external window, ↙ returns to the integrated viewer. Controls and project data stay synchronised.'},
  {selector:'[data-tutorial="export-results"]',title:'7. Exportar resultados',text:'Exporte únicamente los productos ya calculados: rutas GeoJSON, superficies PNG, el modelo GeoTIFF y los elementos del proyecto en GeoPackage.',titleEn:'7. Export results',textEn:'Export only products already calculated: GeoJSON routes, PNG surfaces, the GeoTIFF model and project features in GeoPackage.'},
  {selector:'[data-tutorial="compose-report"]',title:'Componer informe',text:'Genere un informe PDF después de revisar el resultado. El compositor permite elegir mapas, páginas técnicas, formato y elementos visuales para documentar el análisis.',titleEn:'Compose a report',textEn:'Generate a PDF report after reviewing the result. The composer lets you choose maps, technical pages, format and visual elements to document the analysis.'},
  {selector:'[data-tutorial="save-project"]',title:'Guardar el proyecto',text:'Guarde el proyecto al terminar una etapa de trabajo. El proyecto conserva el estado editable; las exportaciones e informes se guardan como productos independientes.',titleEn:'Save the project',textEn:'Save the project after completing a work stage. The project keeps the editable state; exports and reports are saved as separate products.'},
  {selector:'[data-tutorial="settings"]',title:'Configuración y ayuda',text:'Use Configuración para ajustar idioma, fuentes, visores y preferencias generales. El botón está junto a Ayuda, en la parte derecha de la cabecera. Ayuda y Créditos quedan disponibles como consulta, sin interrumpir el flujo de trabajo.',titleEn:'Settings and help',textEn:'Use Settings to adjust language, sources, viewers and general preferences. The button is next to Help on the right of the header. Help and Credits remain available for reference without interrupting the workflow.'},
];

export function AppTutorial({settings,startToken=0}:{settings:AppSettings;startToken?:number}){
  const language=useLanguage();
  const [open,setOpen]=useState(()=>shouldStartTutorial(settings.tutorialEnabled,tutorialCompleted()));
  const [index,setIndex]=useState(0),[rect,setRect]=useState<DOMRect|null>(null);
  const dialogRef=useRef<HTMLDivElement>(null),previousStartToken=useRef(startToken),step=WORKFLOW_STEPS[index],title=language==='en'?step.titleEn:step.title,text=language==='en'?step.textEn:step.text;
  useEffect(()=>{if(startToken!==previousStartToken.current){previousStartToken.current=startToken;setIndex(0);setOpen(true)}},[startToken]);
  useLayoutEffect(()=>{if(!open)return;const update=()=>{const element=document.querySelector(step.selector);if(!(element instanceof HTMLElement)){setRect(null);return}element.scrollIntoView?.({block:'nearest',inline:'nearest'});setRect(element.getBoundingClientRect())};update();window.addEventListener('resize',update);return()=>window.removeEventListener('resize',update)},[open,step]);
  useEffect(()=>{if(!open)return;dialogRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){completeTutorial();setOpen(false)}else if(event.key==='ArrowRight')setIndex(value=>Math.min(WORKFLOW_STEPS.length-1,value+1));else if(event.key==='ArrowLeft')setIndex(value=>Math.max(0,value-1))};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open,index]);
  if(!open)return null;
  const finish=()=>{completeTutorial();setOpen(false)},below=rect?rect.bottom+330<window.innerHeight:true;
  return <section className="tutorial-layer" aria-label="Tutorial de ViaSpania">
    {rect&&<div className="tutorial-shades" aria-hidden="true"><i style={{left:0,top:0,right:0,height:Math.max(0,rect.top-5)}}/><i style={{left:0,top:Math.max(0,rect.top-5),width:Math.max(0,rect.left-5),height:rect.height+10}}/><i style={{left:rect.right+5,top:Math.max(0,rect.top-5),right:0,height:rect.height+10}}/><i style={{left:0,top:rect.bottom+5,right:0,bottom:0}}/></div>}
    {rect&&<div className="tutorial-highlight" style={{left:rect.left-5,top:rect.top-5,width:rect.width+10,height:rect.height+10}}/>}
    <div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="tutorial-title" tabIndex={-1} className={`tutorial-card ${below?'below':'above'}`} style={rect?{left:Math.max(16,Math.min(rect.left,window.innerWidth-396)),top:below?rect.bottom+14:Math.max(16,rect.top-214)}:undefined}>
      <div className="tutorial-progress"><span>{language==='en'?`Step ${index+1} of ${WORKFLOW_STEPS.length}`:`Paso ${index+1} de ${WORKFLOW_STEPS.length}`}</span><button aria-label={language==='en'?'Exit tutorial':'Salir del tutorial'} onClick={finish}>{language==='en'?'Exit':'Salir'}</button></div>
      <b id="tutorial-title">{title}</b><p>{text}</p>
      <nav className="tutorial-step-picker" aria-label={language==='en'?'Go directly to a step':'Ir directamente a un paso'}>{WORKFLOW_STEPS.map((item,stepIndex)=>{const itemTitle=language==='en'?item.titleEn:item.title;return <button key={item.title} className={stepIndex===index?'active':''} aria-label={language==='en'?`Go to step ${stepIndex+1}: ${itemTitle}`:`Ir al paso ${stepIndex+1}: ${itemTitle}`} onClick={()=>setIndex(stepIndex)}>{stepIndex+1}</button>})}</nav>
      <footer><button disabled={index===0} onClick={()=>setIndex(value=>value-1)}>{language==='en'?'Previous':'Anterior'}</button><button className="primary" onClick={()=>index===WORKFLOW_STEPS.length-1?finish():setIndex(value=>value+1)}>{language==='en'?(index===WORKFLOW_STEPS.length-1?'Finish':'Next item'):(index===WORKFLOW_STEPS.length-1?'Terminar':'Siguiente elemento')}</button></footer>
    </div>
  </section>;
}
