import { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { completeTutorial, shouldStartTutorial, tutorialCompleted } from '../core/tutorial';
import type { AppSettings } from '../core/appSettings';
import {setLanguage,useLanguage,translateText,type AppLanguage} from '../core/i18n';
import '../tutorial.css';

type WorkflowStep={selector:string;title:string;text:string;titleEn:string;textEn:string;titleIt:string;textIt:string};
/**
 * Keep this sequence organised by work phase. New tools belong in the phase
 * where their input first becomes available, rather than at the end of the tour.
 */
export const WORKFLOW_STEPS:readonly WorkflowStep[]=[
  {selector:'[data-tutorial="new-project"]',title:'1. Crear o abrir un proyecto',text:'Cree un proyecto para guardar el trabajo, o abra uno existente desde la cabecera.',titleEn:'1. Create or open a project',textEn:'Create a project to save your work, or open an existing one from the header.',titleIt:'1. Crea o apri un progetto',textIt:'Crea un progetto per salvare il lavoro oppure aprine uno esistente dalla barra in alto.'},
  {selector:'[data-tutorial="study-area"]',title:'2. Elegir el área',text:'En Navegación, busque la zona y marque dos esquinas con «Seleccionar área».',titleEn:'2. Choose an area',textEn:'In Navigation, find the location and mark two corners with “Select area”.',titleIt:'2. Scegli l’area',textIt:'In Navigazione, cerca la zona e indica due angoli con «Seleziona area».'},
  {selector:'.model-load-toggle',title:'3. Cargar el terreno',text:'Abra «Cargar modelo» y descargue un MDT para analizar rutas, o importe un archivo local.',titleEn:'3. Load terrain',textEn:'Open “Load model” and download a DTM for route analysis, or import a local file.',titleIt:'3. Carica il terreno',textIt:'Apri «Carica modello» e scarica un MDT per analizzare i percorsi, oppure importa un file locale.'},
  {selector:'[data-tutorial="expand-navigation"]',title:'4. Ampliar el visor de navegación',text:'La flecha del encabezado amplía este mapa para explorar la zona y delimitar el área de estudio. Vuelva a pulsarla para restaurar la vista.',titleEn:'4. Expand the navigation map',textEn:'The arrow in the heading expands this map so you can explore the area and set the study area. Press it again to restore the layout.',titleIt:'4. Espandi la mappa di navigazione',textIt:'La freccia nell’intestazione espande questa mappa per esplorare la zona e definire l’area di studio. Premila di nuovo per ripristinare la vista.'},
  {selector:'[data-tutorial="expand-selection"]',title:'5. Ampliar el visor de selección',text:'Este visor muestra la ortofoto para situar puntos y dibujar barreras y otros elementos. Amplíelo desde la flecha del encabezado cuando necesite más espacio.',titleEn:'5. Expand the selection map',textEn:'This viewer shows the orthophoto for placing points and drawing barriers and other features. Use the heading arrow when you need more room.',titleIt:'5. Espandi la mappa di selezione',textIt:'Questo visore mostra l’ortofoto per posizionare punti e disegnare barriere e altri elementi. Usa la freccia nell’intestazione quando ti serve più spazio.'},
  {selector:'[data-tutorial="expand-historical"]',title:'6. Consultar cartografía histórica',text:'Aquí puede cambiar entre mapas actuales e históricos para comparar el territorio en distintas fechas. La flecha amplía el visor.',titleEn:'6. Explore historical maps',textEn:'Switch between current and historical maps here to compare the area across dates. The arrow expands the viewer.',titleIt:'6. Esplora le mappe storiche',textIt:'Qui puoi passare tra mappe attuali e storiche per confrontare il territorio in epoche diverse. La freccia espande il visore.'},
  {selector:'[data-tutorial="expand-dem"]',title:'7. Ampliar el modelo digital',text:'El modelo digital representa las elevaciones del terreno y sirve de base para los análisis. Amplíelo para consultar mejor el relieve y sus opciones de visualización.',titleEn:'7. Expand the digital terrain model',textEn:'The digital terrain model shows ground elevation and supports the analyses. Expand it to inspect the relief and its display options.',titleIt:'7. Espandi il modello digitale del terreno',textIt:'Il modello digitale mostra le elevazioni del terreno ed è la base delle analisi. Espandilo per osservare meglio il rilievo e le opzioni di visualizzazione.'},
  {selector:'[data-tutorial="open-3d"]',title:'8. Abrir el visor 3D',text:'Tras cargar un MDT, abra aquí el relieve en 3D. Puede girarlo y acercarse; la barra permite ajustar exageración, luz, textura, paleta y capas, o activar el vuelo.',titleEn:'8. Open the 3D viewer',textEn:'After loading a DTM, open its 3D relief here. Rotate and zoom the view; the toolbar lets you adjust exaggeration, lighting, texture, palette and layers, or enable flight mode.',titleIt:'8. Apri il visore 3D',textIt:'Dopo aver caricato un MDT, apri qui il rilievo 3D. Puoi ruotarlo e ingrandirlo; la barra consente di regolare esagerazione, illuminazione, texture, tavolozza e livelli o attivare il volo.'},
  {selector:'[data-tutorial="create-point"]',title:'9. Añadir puntos y condiciones de paso',text:'En Selección, añada los puntos de origen y destino, barreras y facilitadores. Puede mover o eliminar elementos. Deshacer y Rehacer, debajo de «Eliminar elemento», recorren el historial de cambios de puntos, barreras, facilitadores y máscaras marítimas.',titleEn:'9. Add points and passage conditions',textEn:'In Selection, add origin and destination points, barriers and facilitators. You can move or delete elements. Undo and Redo, below “Delete feature”, step through changes to points, barriers, facilitators and marine masks.',titleIt:'9. Aggiungi punti e condizioni di passaggio',textIt:'In Selezione, aggiungi i punti di origine e destinazione, le barriere e i facilitatori. Puoi spostare o eliminare gli elementi. Annulla e Ripeti, sotto «Elimina elemento», scorrono la cronologia delle modifiche a punti, barriere, facilitatori e maschere marine.'},
  {selector:'[data-tutorial="analysis-ruta"]',title:'10. Calcular una ruta',text:'Elija Ruta simple y un perfil de desplazamiento. Calcule la ida para ver la ruta de menor coste entre los dos puntos.',titleEn:'10. Calculate a route',textEn:'Choose Simple route and a travel profile. Calculate the outbound route to find the least-cost path between the two points.',titleIt:'10. Calcola un percorso',textIt:'Scegli Percorso semplice e un profilo di spostamento. Calcola l’andata per trovare il percorso a costo minimo tra i due punti.'},
  {selector:'[data-tutorial="save-project"]',title:'11. Guardar o exportar',text:'Guarde el proyecto para continuar más tarde. Use Exportar resultados para guardar la ruta calculada.',titleEn:'11. Save or export',textEn:'Save the project to continue later. Use Export results to save the calculated route.',titleIt:'11. Salva o esporta',textIt:'Salva il progetto per continuare più tardi. Usa Esporta risultati per salvare il percorso calcolato.'},
];

export function AppTutorial({settings,onSave,startToken=0,autoStart=true}:{settings:AppSettings;onSave?:(settings:AppSettings)=>void;startToken?:number;autoStart?:boolean}){
  const language=useLanguage();
  const [open,setOpen]=useState(()=>autoStart&&shouldStartTutorial(settings.tutorialEnabled,tutorialCompleted()));
  const [choosingLanguage,setChoosingLanguage]=useState(()=>autoStart&&shouldStartTutorial(settings.tutorialEnabled,tutorialCompleted()));
  const [selectedLanguage,setSelectedLanguage]=useState<AppLanguage>(settings.language??'es');
  const [index,setIndex]=useState(0),[rect,setRect]=useState<DOMRect|null>(null);
  const dialogRef=useRef<HTMLDivElement>(null),previousStartToken=useRef(startToken),step=WORKFLOW_STEPS[index],title=language==='en'?step.titleEn:language==='it'?step.titleIt:step.title,text=language==='en'?step.textEn:language==='it'?step.textIt:step.text;
  useEffect(()=>{if(startToken!==previousStartToken.current){previousStartToken.current=startToken;setIndex(0);setSelectedLanguage(settings.language??'es');setChoosingLanguage(true);setOpen(true)}},[startToken,settings.language]);
  useLayoutEffect(()=>{
    if(!open||choosingLanguage){setRect(null);return}
    const element=document.querySelector(step.selector);
    if(!(element instanceof HTMLElement)){setRect(null);return}
    element.scrollIntoView?.({block:'nearest',inline:'nearest'});
    const update=()=>{const bounds=element.getBoundingClientRect();setRect(bounds.width>0&&bounds.height>0?bounds:null)};
    update();
    window.addEventListener('resize',update);
    window.addEventListener('scroll',update,true);
    return()=>{window.removeEventListener('resize',update);window.removeEventListener('scroll',update,true)};
  },[open,step,choosingLanguage]);
  useEffect(()=>{if(!open)return;dialogRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){completeTutorial();setOpen(false)}else if(!choosingLanguage&&event.key==='ArrowRight')setIndex(value=>Math.min(WORKFLOW_STEPS.length-1,value+1));else if(!choosingLanguage&&event.key==='ArrowLeft')setIndex(value=>Math.max(0,value-1))};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open,index,choosingLanguage]);
  if(!open)return null;
  const finish=()=>{completeTutorial();setOpen(false)},below=rect?rect.bottom+330<window.innerHeight:true;
  const beginTutorial=()=>{setLanguage(selectedLanguage);setChoosingLanguage(false)};
  return <section className="tutorial-layer" aria-label="Tutorial de ViaSpania">
    {rect&&<div className="tutorial-shades" aria-hidden="true"><i style={{left:0,top:0,right:0,height:Math.max(0,rect.top-5)}}/><i style={{left:0,top:Math.max(0,rect.top-5),width:Math.max(0,rect.left-5),height:rect.height+10}}/><i style={{left:rect.right+5,top:Math.max(0,rect.top-5),right:0,height:rect.height+10}}/><i style={{left:0,top:rect.bottom+5,right:0,bottom:0}}/></div>}
    {rect&&<div className="tutorial-highlight" style={{left:rect.left-5,top:rect.top-5,width:rect.width+10,height:rect.height+10}}/>}
    <div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="tutorial-title" tabIndex={-1} className={`tutorial-card ${choosingLanguage?'language-choice':below?'below':'above'}`} style={choosingLanguage?undefined:rect?{left:Math.max(16,Math.min(rect.left,window.innerWidth-356)),top:below?rect.bottom+14:Math.max(16,rect.top-214)}:undefined}>
      {choosingLanguage?<>
        <div className="tutorial-progress"><span>{language==='en'?'Before you begin':language==='it'?'Prima di iniziare':'Antes de empezar'}</span><button aria-label={language==='en'?'Exit tutorial':language==='it'?'Esci dal tutorial':'Salir del tutorial'} onClick={finish}>{language==='en'?'Exit':language==='it'?'Esci':'Salir'}</button></div>
        <b id="tutorial-title">{language==='en'?'Choose the tutorial language':language==='it'?'Scegli la lingua del tutorial':'Elija el idioma del tutorial'}</b>
        <p>{language==='en'?'This will also become the app’s main language. You can change it later in Settings.':language==='it'?'Questa diventerà anche la lingua principale dell’app. Potrai cambiarla in seguito nelle Impostazioni.':'Este también será el idioma principal del programa. Puede cambiarlo más adelante en Configuración.'}</p>
        <label className="tutorial-language">{language==='en'?'Language':language==='it'?'Lingua':'Idioma'}<select aria-label={language==='en'?'Tutorial language':language==='it'?'Lingua del tutorial':'Idioma del tutorial'} value={selectedLanguage} onChange={event=>setSelectedLanguage(event.target.value as AppLanguage)}><option value="es">Español</option><option value="en">English</option><option value="it">Italiano</option></select></label>
        <footer><button className="primary" onClick={()=>{beginTutorial();if(onSave)onSave({...settings,language:selectedLanguage})}}>{language==='en'?'Start tutorial':language==='it'?'Avvia il tutorial':'Iniciar tutorial'}</button></footer>
      </>:<>
      <div className="tutorial-progress"><span>{language==='en'?`Step ${index+1} of ${WORKFLOW_STEPS.length}`:translateText(`Paso ${index+1} de ${WORKFLOW_STEPS.length}`,language)}</span><button aria-label={language==='en'?'Exit tutorial':translateText('Salir del tutorial',language)} onClick={finish}>{language==='en'?'Exit':translateText('Salir',language)}</button></div>
      <b id="tutorial-title">{title}</b><p>{text}</p>
      <nav className="tutorial-step-picker" aria-label={language==='en'?'Go directly to a step':translateText('Ir directamente a un paso',language)}>{WORKFLOW_STEPS.map((item,stepIndex)=>{const itemTitle=language==='en'?item.titleEn:item.title;return <button key={item.title} className={stepIndex===index?'active':''} aria-label={language==='en'?`Go to step ${stepIndex+1}: ${itemTitle}`:translateText(`Ir al paso ${stepIndex+1}: ${itemTitle}`,language)} onClick={()=>setIndex(stepIndex)}>{stepIndex+1}</button>})}</nav>
      <footer><button disabled={index===0} onClick={()=>setIndex(value=>value-1)}>{language==='en'?'Previous':language==='it'?'Indietro':translateText('Anterior',language)}</button><button className="primary" onClick={()=>index===WORKFLOW_STEPS.length-1?finish():setIndex(value=>value+1)}>{index===WORKFLOW_STEPS.length-1?(language==='en'?'Finish':language==='it'?'Fine':'Terminar'):(language==='en'?'Next':language==='it'?'Avanti':'Siguiente')}</button></footer>
      </>}
    </div>
  </section>;
}
