import {trackProcess} from '../core/processStatus';
import {useState} from 'react';
import {useLanguage,translateText} from '../core/i18n';
import {importElements} from '../services/elementImports';
import type {ImportedElements} from '../core/elementImports';
export function DataImportControl({onImport}:{onImport:(data:ImportedElements)=>void}){
 const language=useLanguage(),en=language==='en',[opened,setOpened]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <><button data-tutorial="import-data" onClick={()=>{setError('');setOpened(true)}}>{en?'Import data':translateText('Importar datos',language)}</button>{opened&&<section className="result-export-backdrop"><div className="result-export-dialog data-import-dialog" role="dialog" aria-modal="true" aria-label={en?'Import data':translateText('Importar datos',language)}><header><b>{en?'Import data':translateText('Importar datos',language)}</b><button disabled={busy} aria-label={en?'Close':translateText('Cerrar',language)} onClick={()=>setOpened(false)}>×</button></header><p className="surface-model-warning data-import-notice"><b>{en?'Notice:':translateText('Aviso:',language)}</b> {en?'Import points, barriers and facilitators from a ViaSpania GeoPackage (.gpkg). These elements will replace the current project elements, including layers absent from the file. Calculated results will be cleared.':translateText('Importar puntos, barreras y facilitadores de un GeoPackage de ViaSpania (.gpkg). Estos elementos sustituirán a los actuales, incluidas las capas ausentes del archivo. Se borrarán los resultados calculados.',language)}</p>{error&&<p role="alert">{error}</p>}<footer><button disabled={busy} onClick={()=>setOpened(false)}>{en?'Cancel':translateText('Cancelar',language)}</button><button className="primary" disabled={busy} onClick={async()=>{return trackProcess(async(process)=>{setBusy(true);setError('');try{const data=await importElements();if(data){onImport(data);setOpened(false)}}catch(error){process.fail();setError(error instanceof Error?error.message:`No se pudo importar el GeoPackage: ${String(error)}`)}finally{setBusy(false)}});}}>{busy?(en?'Importing…':translateText('Importando…',language)):(en?'Select GeoPackage and replace':translateText('Seleccionar GeoPackage y sustituir',language))}</button></footer></div></section>}</>;
}
