import {CONSTRAINT_COLORS} from '../core/constraintColors';
import {useState} from 'react';
import type {Barrier,BarrierKind,EnabledCrossing,PointOfInterest,PreferredCorridor} from '../types';
import {FacilitatorHelp} from './FacilitatorHelp';

interface Props{
 barriers:Barrier[];corridors:PreferredCorridor[];crossings:EnabledCrossing[];points:PointOfInterest[];
 onBarriers:(items:Barrier[])=>void;onCorridors:(items:PreferredCorridor[])=>void;onCrossings:(items:EnabledCrossing[])=>void;onPoints:(items:PointOfInterest[])=>void;
}

export function FacilitatorEditor(props:Props){
 const [open,setOpen]=useState(false),[helpOpen,setHelpOpen]=useState(false),count=props.barriers.length+props.corridors.length+props.crossings.length+props.points.length;
 return <><section className={`constraint-panel ${open?'open':''}`}>
  <div className="constraint-panel-header"><button type="button" className="constraint-panel-toggle" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span><b>Barreras y facilitadores</b><small>{count} elemento(s) · {props.barriers.length} barrera(s), {props.corridors.length} corredor(es), {props.crossings.length} paso(s), {props.points.length} interés(es)</small></span><i>{open?'▴':'▾'}</i></button><button type="button" className="constraint-help-trigger" aria-label="Ayuda sobre barreras y facilitadores" title="Ayuda sobre barreras y facilitadores" onClick={()=>setHelpOpen(true)}>?</button></div>
  {open&&<div className="constraint-panel-body">
   <div className="constraint-list">
    {props.barriers.map((item,index)=><fieldset className="constraint-card barrier-card" key={`barrier-${index}`}><legend><i aria-hidden="true" style={{backgroundColor:CONSTRAINT_COLORS.barrier ,border:`1px solid ${CONSTRAINT_COLORS.outline}`}}/>Barrera {index+1}</legend><input className="constraint-name" aria-label={`Nombre de la barrera ${index+1}`} value={item.name??`Barrera ${index+1}`} onChange={event=>props.onBarriers(props.barriers.map((value,candidate)=>candidate===index?{...value,name:event.target.value}:value))}/><label>Tipo<select aria-label={`Tipo de la barrera ${index+1}`} value={item.kind} onChange={event=>{const kind=event.target.value as BarrierKind;props.onBarriers(props.barriers.map((value,candidate)=>candidate===index?{...value,kind,value:kind==='absolute'?1:Math.max(1,value.value)}:value))}}><option value="absolute">Absoluta</option><option value="penalty">Permeable</option></select></label>{item.kind==='penalty'&&<label>Coste<input type="number" min="1" max="1000" step="0.5" value={item.value} onChange={event=>props.onBarriers(props.barriers.map((value,candidate)=>candidate===index?{...value,value:Math.max(1,Number(event.target.value))}:value))}/><span>×</span></label>}<small>{item.coordinates.length} vértices</small><button type="button" onClick={()=>props.onBarriers(props.barriers.filter((_,candidate)=>candidate!==index))}>Eliminar</button></fieldset>)}
    {props.corridors.map((item,index)=><fieldset className="constraint-card corridor-card" key={item.id}><legend><i aria-hidden="true" style={{backgroundColor:CONSTRAINT_COLORS.corridor}}/>Corredor {index+1}</legend><input className="constraint-name" aria-label="Nombre del corredor" value={item.name} onChange={event=>props.onCorridors(props.corridors.map(value=>value.id===item.id?{...value,name:event.target.value}:value))}/><label>Anchura<input type="number" min="1" value={item.widthM} onChange={event=>props.onCorridors(props.corridors.map(value=>value.id===item.id?{...value,widthM:Math.max(1,Number(event.target.value))}:value))}/><span>m</span></label><label>Coste<input type="number" min="0.01" max="1" step="0.05" value={item.costMultiplier} onChange={event=>props.onCorridors(props.corridors.map(value=>value.id===item.id?{...value,costMultiplier:Math.min(1,Math.max(.01,Number(event.target.value)))}:value))}/><span>×</span></label><small>{item.coordinates.length} vértices</small><button type="button" onClick={()=>props.onCorridors(props.corridors.filter(value=>value.id!==item.id))}>Eliminar</button></fieldset>)}
    {props.crossings.map((item,index)=><fieldset className="constraint-card crossing-card" key={item.id}><legend><i aria-hidden="true" style={{backgroundColor:CONSTRAINT_COLORS.crossing}}/>Paso {index+1}</legend><input className="constraint-name" aria-label="Nombre del paso" value={item.name} onChange={event=>props.onCrossings(props.crossings.map(value=>value.id===item.id?{...value,name:event.target.value}:value))}/><label>Tipo<select value={item.kind} onChange={event=>props.onCrossings(props.crossings.map(value=>value.id===item.id?{...value,kind:event.target.value as EnabledCrossing['kind']}:value))}><option value="bridge">Puente</option><option value="ford">Vado</option><option value="tunnel">Túnel</option></select></label><label>Coste<input type="number" min="0.01" step="0.1" value={item.crossingCostMultiplier} onChange={event=>props.onCrossings(props.crossings.map(value=>value.id===item.id?{...value,crossingCostMultiplier:Math.max(.01,Number(event.target.value))}:value))}/><span>×</span></label><label><input type="checkbox" aria-label={`Paso obligatorio: ${item.name}`} checked={item.required===true} onChange={event=>props.onCrossings(props.crossings.map(value=>value.id===item.id?{...value,required:event.target.checked}:value))}/>Paso obligatorio</label><small>{item.coordinates.length} vértices</small><button type="button" onClick={()=>props.onCrossings(props.crossings.filter(value=>value.id!==item.id))}>Eliminar</button></fieldset>)}
    {props.points.map((item,index)=><fieldset className="constraint-card poi-card" key={item.id}><legend><i aria-hidden="true" style={{backgroundColor:CONSTRAINT_COLORS.poi}}/>Interés {index+1}</legend><input className="constraint-name" aria-label="Nombre del punto de interés" value={item.name} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,name:event.target.value}:value))}/><label className="constraint-category">Categoría<input aria-label="Categoría" placeholder="Sin categoría" value={item.category==='otro'?'':item.category} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,category:event.target.value}:value))}/></label><label>Modo<select value={item.mode} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,mode:event.target.value as PointOfInterest['mode']}:value))}><option value="influence">Influencia espacial</option><option value="waypoint">Paso obligatorio</option><option value="single-visit" disabled>Visita única · futura</option></select></label><label>Radio<input type="number" min="1" value={item.influenceRadiusM} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,influenceRadiusM:Math.max(1,Number(event.target.value))}:value))}/><span>m</span></label><label>Atracción<input type="number" min="0" max="0.99" step="0.05" value={item.attraction} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,attraction:Math.min(.99,Math.max(0,Number(event.target.value)))}:value))}/></label><button type="button" onClick={()=>props.onPoints(props.points.filter(value=>value.id!==item.id))}>Eliminar</button></fieldset>)}
    {!count&&<p className="constraint-empty">No hay elementos. Créelos con las herramientas del mapa de Selección.</p>}
   </div>
  </div>}
 </section>{helpOpen&&<FacilitatorHelp onClose={()=>setHelpOpen(false)}/>}</>
}
