import {useState} from 'react';
import type {Barrier,BarrierKind,EnabledCrossing,PointOfInterest,PreferredCorridor} from '../types';

interface Props{
 barriers:Barrier[];corridors:PreferredCorridor[];crossings:EnabledCrossing[];points:PointOfInterest[];
 barrierKind:BarrierKind;barrierValue:number;corridorWidth:number;corridorMultiplier:number;crossingMultiplier:number;
 onBarriers:(items:Barrier[])=>void;onCorridors:(items:PreferredCorridor[])=>void;onCrossings:(items:EnabledCrossing[])=>void;onPoints:(items:PointOfInterest[])=>void;
 onBarrierKind:(value:BarrierKind)=>void;onBarrierValue:(value:number)=>void;onCorridorWidth:(value:number)=>void;onCorridorMultiplier:(value:number)=>void;onCrossingMultiplier:(value:number)=>void;
}

export function FacilitatorEditor(props:Props){
 const [open,setOpen]=useState(false),count=props.barriers.length+props.corridors.length+props.crossings.length+props.points.length;
 return <section className={`constraint-panel ${open?'open':''}`}>
  <button type="button" className="constraint-panel-toggle" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span><b>Barreras y facilitadores</b><small>{count} elemento(s) · {props.barriers.length} barrera(s), {props.corridors.length} corredor(es), {props.crossings.length} paso(s), {props.points.length} interés(es)</small></span><i>{open?'▴':'▾'}</i></button>
  {open&&<div className="constraint-panel-body">
   <fieldset className="constraint-defaults"><legend>Valores para nuevos elementos</legend><label>Tipo de barrera<select value={props.barrierKind} onChange={event=>props.onBarrierKind(event.target.value as BarrierKind)}><option value="absolute">Absoluta · infranqueable</option><option value="penalty">Permeable · coste multiplicado</option></select></label>{props.barrierKind==='penalty'&&<label>Coste barrera<input type="number" min="1" max="1000" step="0.5" value={props.barrierValue} onChange={event=>props.onBarrierValue(Math.max(1,Number(event.target.value)))}/><span>×</span></label>}<label>Anchura corredor<input type="number" min="1" step="1" value={props.corridorWidth} onChange={event=>props.onCorridorWidth(Math.max(1,Number(event.target.value)))}/><span>m</span></label><label>Coste corredor<input type="number" min="0.01" max="1" step="0.05" value={props.corridorMultiplier} onChange={event=>props.onCorridorMultiplier(Math.min(1,Math.max(.01,Number(event.target.value))))}/><span>×</span></label><label>Coste del paso<input type="number" min="0.01" step="0.1" value={props.crossingMultiplier} onChange={event=>props.onCrossingMultiplier(Math.max(.01,Number(event.target.value)))}/><span>×</span></label></fieldset>
   <div className="constraint-list">
    {props.barriers.map((item,index)=><fieldset className="constraint-card barrier-card" key={`barrier-${index}`}><legend><i/>Barrera {index+1}</legend><label>Tipo<select aria-label={`Tipo de la barrera ${index+1}`} value={item.kind} onChange={event=>{const kind=event.target.value as BarrierKind;props.onBarriers(props.barriers.map((value,candidate)=>candidate===index?{...value,kind,value:kind==='absolute'?1:Math.max(1,value.value)}:value))}}><option value="absolute">Absoluta</option><option value="penalty">Permeable</option></select></label>{item.kind==='penalty'&&<label>Coste<input type="number" min="1" max="1000" step="0.5" value={item.value} onChange={event=>props.onBarriers(props.barriers.map((value,candidate)=>candidate===index?{...value,value:Math.max(1,Number(event.target.value))}:value))}/><span>×</span></label>}<small>{item.coordinates.length} vértices</small><button type="button" onClick={()=>props.onBarriers(props.barriers.filter((_,candidate)=>candidate!==index))}>Eliminar</button></fieldset>)}
    {props.corridors.map((item,index)=><fieldset className="constraint-card corridor-card" key={item.id}><legend><i/>Corredor {index+1}</legend><input aria-label="Nombre del corredor" value={item.name} onChange={event=>props.onCorridors(props.corridors.map(value=>value.id===item.id?{...value,name:event.target.value}:value))}/><label>Anchura<input type="number" min="1" value={item.widthM} onChange={event=>props.onCorridors(props.corridors.map(value=>value.id===item.id?{...value,widthM:Math.max(1,Number(event.target.value))}:value))}/><span>m</span></label><label>Coste<input type="number" min="0.01" max="1" step="0.05" value={item.costMultiplier} onChange={event=>props.onCorridors(props.corridors.map(value=>value.id===item.id?{...value,costMultiplier:Math.min(1,Math.max(.01,Number(event.target.value)))}:value))}/><span>×</span></label><small>{item.coordinates.length} vértices</small><button type="button" onClick={()=>props.onCorridors(props.corridors.filter(value=>value.id!==item.id))}>Eliminar</button></fieldset>)}
    {props.crossings.map((item,index)=><fieldset className="constraint-card crossing-card" key={item.id}><legend><i/>Paso {index+1}</legend><input aria-label="Nombre del paso" value={item.name} onChange={event=>props.onCrossings(props.crossings.map(value=>value.id===item.id?{...value,name:event.target.value}:value))}/><label>Tipo<select value={item.kind} onChange={event=>props.onCrossings(props.crossings.map(value=>value.id===item.id?{...value,kind:event.target.value as EnabledCrossing['kind']}:value))}><option value="bridge">Puente</option><option value="ford">Vado</option><option value="tunnel">Túnel</option></select></label><label>Coste<input type="number" min="0.01" step="0.1" value={item.crossingCostMultiplier} onChange={event=>props.onCrossings(props.crossings.map(value=>value.id===item.id?{...value,crossingCostMultiplier:Math.max(.01,Number(event.target.value))}:value))}/><span>×</span></label><small>{item.coordinates.length} vértices</small><button type="button" onClick={()=>props.onCrossings(props.crossings.filter(value=>value.id!==item.id))}>Eliminar</button></fieldset>)}
    {props.points.map((item,index)=><fieldset className="constraint-card poi-card" key={item.id}><legend><i/>Interés {index+1}</legend><input aria-label="Nombre del punto de interés" value={item.name} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,name:event.target.value}:value))}/><input aria-label="Categoría" value={item.category} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,category:event.target.value}:value))}/><label>Modo<select value={item.mode} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,mode:event.target.value as PointOfInterest['mode']}:value))}><option value="influence">Influencia espacial</option><option value="waypoint">Paso obligatorio</option><option value="single-visit" disabled>Visita única · futura</option></select></label><label>Radio<input type="number" min="1" value={item.influenceRadiusM} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,influenceRadiusM:Math.max(1,Number(event.target.value))}:value))}/><span>m</span></label><label>Atracción<input type="number" min="0" max="0.99" step="0.05" value={item.attraction} onChange={event=>props.onPoints(props.points.map(value=>value.id===item.id?{...value,attraction:Math.min(.99,Math.max(0,Number(event.target.value)))}:value))}/></label><button type="button" onClick={()=>props.onPoints(props.points.filter(value=>value.id!==item.id))}>Eliminar</button></fieldset>)}
    {!count&&<p className="constraint-empty">No hay elementos. Créelos con las herramientas del mapa de Selección.</p>}
   </div>
  </div>}
 </section>
}
