import { useState } from 'react';
import { recommendedCellLimit, type AppSettings, type BuiltInMapSourceId, type PaletteId } from '../core/appSettings';
import { nativeStatus } from '../services/native';
import { NOTIFICATION_SOUNDS, playNotificationSound, type NotificationSound } from '../core/notificationSounds';
import { normalizeExternalMapLayer, type ExternalMapLayer, type ExternalMapProtocol, type ExternalMapViewer } from '../core/externalMapLayers';
import { inspectExternalMapService, type ExternalServiceLayer } from '../services/externalCapabilities';
import { ELEVATION_SOURCES, type ElevationSourceId } from '../core/elevationSources';
import { BUILT_IN_MAP_SOURCES } from '../core/mapSources';
import { translateText,useLanguage } from '../core/i18n';
import '../general-settings.css';
import '../surface-models.css';

type SettingsTab='language'|'tutorial'|'viewers2d'|'viewer3d'|'models'|'cartography'|'processing'|'sounds';
const PALETTES:Record<PaletteId,string>={grayscale:'Escala de grises',terrain:'Terreno',hypsometric:'Hipsométrica',viridis:'Viridis',alpine:'Alta montaña'};

export function GeneralSettingsControl({settings,onSave,onStartTutorial}:{settings:AppSettings;onSave:(settings:AppSettings)=>void;onStartTutorial?:()=>void}){
  const language=useLanguage();
  const [open,setOpen]=useState(false),[draft,setDraft]=useState(settings),[tab,setTab]=useState<SettingsTab>('viewers2d'),[memory,setMemory]=useState<number|null>(null),[layerName,setLayerName]=useState(''),[layerUrl,setLayerUrl]=useState(''),[layerAttribution,setLayerAttribution]=useState(''),[layerViewer,setLayerViewer]=useState<ExternalMapViewer>('navigation'),[layerProtocol,setLayerProtocol]=useState<ExternalMapProtocol>('xyz'),[serviceLayers,setServiceLayers]=useState<ExternalServiceLayer[]>([]),[selectedServiceLayer,setSelectedServiceLayer]=useState(''),[inspecting,setInspecting]=useState(false),[layerError,setLayerError]=useState('');
  const update=<K extends keyof AppSettings>(key:K,value:AppSettings[K])=>setDraft(current=>({...current,[key]:value}));
  const updateElevation=(id:ElevationSourceId,value:boolean)=>setDraft(current=>({...current,enabledElevationModels:{...current.enabledElevationModels,[id]:value}}));
  const updateMap=(id:BuiltInMapSourceId,value:boolean)=>setDraft(current=>({...current,enabledMapSources:{...current.enabledMapSources,[id]:value}}));
  const show=()=>{setDraft(settings);setTab('viewers2d');setOpen(true);nativeStatus().then(status=>setMemory(status.totalMemoryBytes??null)).catch(()=>setMemory(null))};
  const recommendation=recommendedCellLimit(memory),gib=memory?memory/1073741824:null;
  const inspectService=async()=>{if(layerProtocol==='xyz')return;setInspecting(true);setLayerError('');setServiceLayers([]);setSelectedServiceLayer('');try{const layers=await inspectExternalMapService(layerProtocol,layerUrl);if(!layers.length)throw new Error('El servicio no contiene capas compatibles con ViaSpania.');setServiceLayers(layers);setSelectedServiceLayer(layers[0].id)}catch(error){const message=error instanceof Error?error.message:'No se pudo consultar el servicio.';setLayerError(language==='en'?`${translateText(message)} ${translateText('Compruebe que el servidor permita solicitudes CORS.')}`:`${message} Compruebe que el servidor permita solicitudes CORS.`)}finally{setInspecting(false)}};
  const addExternalLayer=()=>{try{let candidate:ExternalMapLayer;if(layerProtocol==='xyz')candidate={id:`external-${Date.now()}`,name:layerName,url:layerUrl,viewer:layerViewer,protocol:'xyz',attribution:layerAttribution};else{const selected=serviceLayers.find(layer=>layer.id===selectedServiceLayer);if(!selected)throw new Error('Consulte el servicio y seleccione una capa.');candidate={...selected.config,id:`external-${Date.now()}`,name:layerName||selected.title,viewer:layerViewer,attribution:layerAttribution} as ExternalMapLayer}const layer=normalizeExternalMapLayer(candidate);setDraft(current=>({...current,externalMapLayers:[...current.externalMapLayers,layer]}));setLayerName('');setLayerUrl('');setLayerAttribution('');setServiceLayers([]);setSelectedServiceLayer('');setLayerError('')}catch(error){setLayerError(error instanceof Error?error.message:'No se pudo añadir la capa externa.')}};
  const saveDraft=()=>{try{
    if(!Object.values(draft.enabledElevationModels).some(Boolean)){setTab('models');throw new Error('Debe mantener activado al menos un modelo digital.')}
    const navigation=(['osm','ign-topographic'] as const).filter(id=>draft.enabledMapSources[id]),orthophotos=(['pnoa','copernicus-vhr-2021'] as const).filter(id=>draft.enabledMapSources[id]),cartography=(['MTN50','MTN25','catastrones','Minutas','AMS_1956-1957','Interministerial_1973-1986'] as const).filter(id=>draft.enabledMapSources[id]);
    if(!navigation.length||!orthophotos.length||!cartography.length){setTab('cartography');throw new Error('Debe mantener activa al menos una fuente de navegación, una ortofotografía y una fuente del visor de cartografía.')}
    onSave({...draft,defaultNavigationLayer:navigation.includes(draft.defaultNavigationLayer)?draft.defaultNavigationLayer:navigation[0],defaultSelectionOrthophoto:orthophotos.includes(draft.defaultSelectionOrthophoto)?draft.defaultSelectionOrthophoto:orthophotos[0],externalMapLayers:draft.externalMapLayers.map(normalizeExternalMapLayer)});setLayerError('');setOpen(false)
  }catch(error){setLayerError(error instanceof Error?error.message:'Revise las preferencias.')}};
  const paletteOptions=(value:PaletteId,key:'defaultPalette'|'defaultTerrain3dPalette')=><select value={value} onChange={event=>update(key,event.target.value as PaletteId)}>{Object.entries(PALETTES).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select>;
  return <><button onClick={show}>Configuración</button>{open&&<section className="settings-backdrop"><div className="settings-dialog">
    <header><div><b>Configuración</b><span>Preferencias guardadas en este equipo</span></div><button aria-label="Cerrar configuración" onClick={()=>setOpen(false)}>×</button></header>
    <div className="settings-tabs">{([['language','Idioma / Language'],['tutorial','Tutorial'],['viewers2d','Visores 2D'],['viewer3d','Visor 3D'],['models','Modelos digitales'],['cartography','Cartografía'],['processing','Procesado'],['sounds','Sonidos']] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    <div className="settings-body single">
      {tab==='language'&&<fieldset><legend>Idioma de la aplicación / Application language</legend><label>Idioma / Language<select aria-label="Idioma de la aplicación" value={draft.language??'es'} onChange={event=>update('language',event.target.value as 'es'|'en')}><option value="es">Español</option><option value="en">English</option></select></label><p className="processing-warning">El idioma se aplica a toda la interfaz, las ayudas, el tutorial, los créditos, los informes y los mensajes exportados al guardar las preferencias.</p></fieldset>}
      {tab==='tutorial'&&<fieldset><legend>Tutorial de inicio</legend><label className="check"><input type="checkbox" checked={draft.tutorialEnabled} onChange={e=>update('tutorialEnabled',e.target.checked)}/> Mostrar el tutorial automáticamente la primera vez</label><p className="processing-warning">El recorrido explica los cuatro visores, los modos de cálculo y las acciones principales. Se detiene en cada paso hasta que decida continuar.</p><button type="button" onClick={()=>{setOpen(false);onStartTutorial?.()}}>Iniciar tutorial ahora</button></fieldset>}
      {tab==='viewers2d'&&<fieldset><legend>Visores 2D</legend>
        <label className="check"><input type="checkbox" checked={draft.showCrosshairs} onChange={e=>update('showCrosshairs',e.target.checked)}/> Mostrar crucetas sobre visores</label>
        <label className="check"><input type="checkbox" checked={draft.showSelectionMarker} onChange={e=>update('showSelectionMarker',e.target.checked)}/> Mostrar punteros simultáneos</label>
        <label className="check"><input type="checkbox" checked={draft.showScales} onChange={e=>update('showScales',e.target.checked)}/> Mostrar escalas</label>
        <label className="check"><input type="checkbox" checked={draft.showSelectionCoordinates} onChange={e=>update('showSelectionCoordinates',e.target.checked)}/> Mostrar coordenadas del cursor en el visor de selección</label>
        <label className="check"><input type="checkbox" checked={draft.showPointLabels} onChange={e=>update('showPointLabels',e.target.checked)}/> Mostrar etiquetas de los elementos</label>
        <label className="check"><input type="checkbox" checked={draft.showMunicipalBoundaries} onChange={e=>update('showMunicipalBoundaries',e.target.checked)}/> Mostrar límites administrativos (España)</label>
        <label>Mapa de navegación predeterminado<select value={draft.defaultNavigationLayer} onChange={e=>update('defaultNavigationLayer',e.target.value as AppSettings['defaultNavigationLayer'])}>{draft.enabledMapSources.osm&&<option value="osm">OpenStreetMap</option>}{draft.enabledMapSources['ign-topographic']&&<option value="ign-topographic">Topográfico IGN</option>}</select></label>
        <label>Ortofotografía de selección predeterminada<select value={draft.defaultSelectionOrthophoto} onChange={e=>update('defaultSelectionOrthophoto',e.target.value as AppSettings['defaultSelectionOrthophoto'])}>{draft.enabledMapSources.pnoa&&<option value="pnoa">PNOA · España</option>}{draft.enabledMapSources['copernicus-vhr-2021']&&<option value="copernicus-vhr-2021">Copernicus VHR 2021 · Europa · 2 m</option>}</select></label>
        <label>Paleta predeterminada del modelo digital{paletteOptions(draft.defaultPalette,'defaultPalette')}</label>
      </fieldset>}
      {tab==='viewer3d'&&<fieldset><legend>Visor 3D</legend>
        <label>Exageración vertical 3D predeterminada<select value={draft.defaultTerrain3dExaggeration} onChange={e=>update('defaultTerrain3dExaggeration',Number(e.target.value) as AppSettings['defaultTerrain3dExaggeration'])}>{[0,.5,1,1.5,2,3,4,6,8].map(value=><option key={value} value={value}>{value===0?'0 % · plano':`${value.toFixed(1)}×`}</option>)}</select></label>
        <label>Paleta predeterminada del modelo 3D{paletteOptions(draft.defaultTerrain3dPalette,'defaultTerrain3dPalette')}</label>
        <label className="check"><input type="checkbox" checked={draft.defaultTerrain3dHighestPoint} onChange={e=>update('defaultTerrain3dHighestPoint',e.target.checked)}/> Mostrar por defecto la cota más alta</label>
        <label className="check"><input type="checkbox" checked={draft.defaultTerrain3dShowScale} onChange={e=>update('defaultTerrain3dShowScale',e.target.checked)}/> Mostrar escala</label>
      </fieldset>}
      {tab==='models'&&<fieldset><legend>Modelos digitales</legend>{(['terrain','surface'] as const).map(kind=><section className="settings-source-group" key={kind}><b>{kind==='terrain'?'Modelos digitales de terreno (MDT)':'Modelos digitales de superficie (MDS)'}</b>{Object.values(ELEVATION_SOURCES).filter(source=>source.kind===kind).map(source=><label className="check" key={source.id}><input type="checkbox" checked={draft.enabledElevationModels[source.id]} onChange={event=>updateElevation(source.id,event.target.checked)}/><span>{source.label}<small>{source.coverage} · {source.resolutionM} m</small></span></label>)}</section>)}</fieldset>}
      {tab==='cartography'&&<>
        <fieldset><legend>Fuentes de cartografía incorporadas</legend><div className="built-in-source-list">{BUILT_IN_MAP_SOURCES.map(source=><div key={source.id}><label className="check"><input type="checkbox" checked={draft.enabledMapSources[source.id]} onChange={event=>updateMap(source.id,event.target.checked)}/><span>{source.name}<small>{source.category} · {source.provider}</small></span></label><a href={source.url} target="_blank" rel="noreferrer">Enlace de origen ↗</a></div>)}</div></fieldset>
        <fieldset className="external-layers"><legend>Otras fuentes externas</legend>
          <p className="processing-warning">Admite teselas XYZ y servicios interoperables WMS o WMTS. En WMS/WMTS, consulte primero las capacidades del servicio.</p>
          <label>Tipo de servicio<select aria-label="Tipo de servicio" value={layerProtocol} onChange={event=>{setLayerProtocol(event.target.value as ExternalMapProtocol);setServiceLayers([]);setSelectedServiceLayer('');setLayerError('')}}><option value="xyz">XYZ</option><option value="wms">WMS</option><option value="wmts">WMTS</option></select></label>
          <label>Nombre de la capa<input value={layerName} onChange={event=>setLayerName(event.target.value)} placeholder={layerProtocol==='xyz'?(language==='en'?'My map':'Mi cartografía'):(language==='en'?'Optional · the service title will be used':'Opcional · se usará el título del servicio')}/></label>
          <label>{layerProtocol==='xyz'?'URL XYZ':'URL del servicio'}<input aria-label={layerProtocol==='xyz'?'URL XYZ':'URL del servicio'} value={layerUrl} onChange={event=>{setLayerUrl(event.target.value);setServiceLayers([]);setSelectedServiceLayer('')}} placeholder={layerProtocol==='xyz'?(language==='en'?'https://server/{z}/{x}/{y}.png':'https://servidor/{z}/{x}/{y}.png'):(language==='en'?'https://server/wms':'https://servidor/wms')}/></label>
          {layerProtocol!=='xyz'&&<><button type="button" disabled={inspecting||!layerUrl.trim()} onClick={()=>void inspectService()}>{inspecting?'Consultando…':'Consultar servicio'}</button>{serviceLayers.length>0&&<label>Capa disponible<select aria-label="Capa disponible" value={selectedServiceLayer} onChange={event=>setSelectedServiceLayer(event.target.value)}>{serviceLayers.map(layer=><option key={layer.id} value={layer.id}>{layer.title}</option>)}</select></label>}</>}
          <label>Atribución<input aria-label="Atribución" value={layerAttribution} onChange={event=>setLayerAttribution(event.target.value)} placeholder={language==='en'?'Organisation, licence or source':'Organismo, licencia o procedencia'}/></label>
          <label>Visor<select value={layerViewer} onChange={event=>setLayerViewer(event.target.value as ExternalMapViewer)}><option value="navigation">Navegación</option><option value="selection">Selección</option><option value="historical">Visor de cartografía</option></select></label>
          {layerError&&<p className="external-layer-error">{language==='en'?translateText(layerError):layerError}</p>}<button type="button" className="primary" onClick={addExternalLayer}>Añadir capa</button>
          <div className="external-layer-list">{draft.externalMapLayers.length?draft.externalMapLayers.map(layer=><div key={layer.id}><label>Nombre<input aria-label={`Nombre de ${layer.name}`} value={layer.name} onChange={event=>setDraft(current=>({...current,externalMapLayers:current.externalMapLayers.map(item=>item.id===layer.id?{...item,name:event.target.value}:item)}))}/></label><span>{(layer.protocol??'xyz').toUpperCase()} · {layer.viewer==='navigation'?'Navegación':layer.viewer==='selection'?'Selección':'Visor de cartografía'}</span><small title={layer.url}>{layer.protocol&&layer.protocol!=='xyz'?`${layer.layerName} · ${layer.url}`:layer.url}</small><button type="button" onClick={()=>setDraft(current=>({...current,externalMapLayers:current.externalMapLayers.filter(item=>item.id!==layer.id)}))}>Eliminar</button></div>):<p className="hint">No hay capas externas añadidas.</p>}</div>
        </fieldset>
      </>}
      {tab==='processing'&&<fieldset><legend>Opciones de procesado</legend><div className="memory-summary"><b>{gib?`${gib.toFixed(1)} GB de memoria detectada`:'Memoria del equipo no disponible'}</b><span>{language==='en'?`Recommended limit: ${recommendation.toLocaleString('en-GB')} cells`:`Límite recomendado: ${recommendation.toLocaleString('es-ES')} celdas`}</span></div><label>Límite máximo de celdas<select value={draft.processingCellLimit} onChange={e=>update('processingCellLimit',Number(e.target.value) as AppSettings['processingCellLimit'])}><option value="2000000">2.000.000 · conservador · hasta 8 GB</option><option value="3000000">3.000.000 · recomendado · 9–16 GB</option><option value="3500000">3.500.000 · elevado · 17–24 GB</option><option value="5000000">5.000.000 · máximo · más de 24 GB</option></select></label><button type="button" onClick={()=>update('processingCellLimit',recommendation)}>Aplicar valor recomendado</button><p className="processing-warning">El límite se aplica en el motor nativo antes de reservar la rejilla. Comparar modelos, conectividad 16 y multipunto requieren más tiempo.</p></fieldset>}
      {tab==='sounds'&&<fieldset><legend>Sonidos de aviso</legend><label className="check"><input type="checkbox" checked={draft.notificationSounds} onChange={e=>update('notificationSounds',e.target.checked)}/> Avisar al terminar cálculos, cargas y exportaciones</label><label>Sonido<select value={draft.notificationSound} disabled={!draft.notificationSounds} onChange={e=>update('notificationSound',e.target.value as NotificationSound)}>{Object.entries(NOTIFICATION_SOUNDS).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><button type="button" disabled={!draft.notificationSounds} onClick={()=>playNotificationSound(draft.notificationSound)}>Probar sonido</button><p className="processing-warning">El aviso solo se reproduce cuando la operación termina correctamente; no suena al cancelar ni cuando ocurre un error.</p></fieldset>}
    </div>{layerError&&tab!=='cartography'&&<p className="settings-save-error">{language==='en'?translateText(layerError):layerError}</p>}<footer><button onClick={()=>setOpen(false)}>Cancelar</button><button className="primary" onClick={saveDraft}>Guardar preferencias</button></footer>
  </div></section>}</>;
}
