// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {DEFAULT_APP_SETTINGS} from '../core/appSettings';
import {GeneralSettingsControl} from './GeneralSettingsControl';

afterEach(cleanup);

describe('fuentes cartográficas externas',()=>{
  it('añade, renombra y persiste una capa disponible en todos los visores',()=>{const onSave=vi.fn();render(<GeneralSettingsControl settings={DEFAULT_APP_SETTINGS} onSave={onSave}/>);fireEvent.click(screen.getByRole('button',{name:'Configuración'}));fireEvent.click(screen.getByRole('button',{name:'Cartografía'}));expect(screen.queryByLabelText('Visor')).toBeNull();fireEvent.change(screen.getByLabelText('Nombre de la capa'),{target:{value:'Teselas locales'}});fireEvent.change(screen.getByLabelText('URL XYZ'),{target:{value:'https://tiles.example/{z}/{x}/{y}.png'}});fireEvent.click(screen.getByRole('button',{name:'Añadir capa'}));const name=screen.getByDisplayValue('Teselas locales');fireEvent.change(name,{target:{value:'Teselas editadas'}});fireEvent.click(screen.getByRole('button',{name:'Guardar preferencias'}));const saved=onSave.mock.calls.at(-1)?.[0];expect(saved).toEqual(expect.objectContaining({externalMapLayers:[expect.objectContaining({name:'Teselas editadas',protocol:'xyz'})]}));expect(saved.externalMapLayers[0]).not.toHaveProperty('viewer')});
  it('permite eliminar una capa añadida',()=>{const layer={id:'x',name:'Capa',url:'https://tiles.example/{z}/{x}/{y}.png',viewer:'navigation' as const,protocol:'xyz' as const},onSave=vi.fn();render(<GeneralSettingsControl settings={{...DEFAULT_APP_SETTINGS,externalMapLayers:[layer]}} onSave={onSave}/>);fireEvent.click(screen.getByRole('button',{name:'Configuración'}));fireEvent.click(screen.getByRole('button',{name:'Cartografía'}));fireEvent.click(screen.getByRole('button',{name:'Eliminar'}));fireEvent.click(screen.getByRole('button',{name:'Guardar preferencias'}));expect(onSave).toHaveBeenCalledWith(expect.objectContaining({externalMapLayers:[]}))});
  it('mantiene el orden de las capas sin ofrecer un control de opacidad',()=>{const first={id:'a',name:'Histórica',url:'https://tiles.example/a/{z}/{x}/{y}.png',viewer:'historical' as const,protocol:'xyz' as const},second={id:'b',name:'Ortofoto',url:'https://tiles.example/b/{z}/{x}/{y}.png',viewer:'selection' as const,protocol:'xyz' as const},onSave=vi.fn();render(<GeneralSettingsControl settings={{...DEFAULT_APP_SETTINGS,externalMapLayers:[first,second]}} onSave={onSave}/>);fireEvent.click(screen.getByRole('button',{name:'Configuración'}));fireEvent.click(screen.getByRole('button',{name:'Cartografía'}));expect(screen.queryByLabelText('Opacidad de Histórica')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'Subir Ortofoto'}));fireEvent.click(screen.getByRole('button',{name:'Guardar preferencias'}));expect(onSave).toHaveBeenCalledWith(expect.objectContaining({externalMapLayers:[expect.objectContaining({id:'b'}),expect.objectContaining({id:'a'})]}))});
});
