import {useEffect,useRef,useState} from 'react';
import Feature from 'ol/Feature';
import LineString from 'ol/geom/LineString';
import Polygon from 'ol/geom/Polygon';
import Point from 'ol/geom/Point';
import Map from 'ol/Map';
import Draw from 'ol/interaction/Draw';
import VectorLayer from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector';
import {fromLonLat,toLonLat} from 'ol/proj';
import {getArea as geodesicArea,getLength as geodesicLength} from 'ol/sphere';
import {Circle as CircleStyle,Fill,Stroke,Style,Text} from 'ol/style';
import type {RouteResult} from '../types';
import {sampleRasterElevationsAt} from '../services/native';
import {translateText} from '../core/i18n';
import {ElevationProfileOverlay,type ElevationProfileRoute} from './ElevationProfileOverlay';
import '../elevation-profile.css';
import '../map-tools.css';

type Mode='pan'|'distance'|'area';
function sampledCoordinates(line:LineString,maxSamples=120):[number,number][]{
 const coordinates=line.getCoordinates();if(coordinates.length<2)return[];const lengths=coordinates.slice(1).map((coordinate,index)=>Math.hypot(coordinate[0]-coordinates[index][0],coordinate[1]-coordinates[index][1])),total=lengths.reduce((sum,value)=>sum+value,0);if(!(total>0))return[];
 const count=Math.min(maxSamples,Math.max(2,Math.ceil(total/25))),samples:[number,number][]=[];for(let index=0;index<=count;index++){let remaining=total*index/count,segment=0;while(segment<lengths.length-1&&remaining>lengths[segment]){remaining-=lengths[segment];segment++}const ratio=lengths[segment]?Math.min(1,remaining/lengths[segment]):0,a=coordinates[segment],b=coordinates[segment+1];samples.push(toLonLat([a[0]+(b[0]-a[0])*ratio,a[1]+(b[1]-a[1])*ratio]) as [number,number])}return samples;
}
async function makeProfile(rasterPath:string,coordinates:[number,number][],id:string):Promise<ElevationProfileRoute|null>{
 let elevations:(number|null)[];try{elevations=await sampleRasterElevationsAt(rasterPath,coordinates)}catch{return null}
 const valid=coordinates.map((coordinate,index)=>({coordinate,elevation:elevations[index]})).filter((item):item is {coordinate:[number,number];elevation:number}=>item.elevation!==null);if(valid.length<2)return null;let distanceM=0,ascentM=0,descentM=0;for(let index=1;index<valid.length;index++){const[aLon,aLat]=valid[index-1].coordinate,[bLon,bLat]=valid[index].coordinate,radians=Math.PI/180,dLat=(bLat-aLat)*radians,dLon=(bLon-aLon)*radians,a=Math.sin(dLat/2)**2+Math.cos(aLat*radians)*Math.cos(bLat*radians)*Math.sin(dLon/2)**2,segment=2*6371008.8*Math.asin(Math.min(1,Math.sqrt(a))),rise=valid[index].elevation-valid[index-1].elevation;distanceM+=segment;if(rise>0)ascentM+=rise;else descentM-=rise}const result:RouteResult={model:'tobler',direction:'measurement',path:[],coordinates:valid.map(item=>item.coordinate),elevationsM:valid.map(item=>item.elevation),cost:0,unit:'m',distanceM,ascentM,descentM};return{label:`Measurement ${id}`,color:'#d8ff55',result};
}
function measurementEndCaps(line:LineString,resolution:number):LineString[]{const coordinates=line.getCoordinates();if(coordinates.length<2)return[];const size=Math.max(resolution,0.01)*6;return [[coordinates[0],coordinates[1]],[coordinates.at(-1)!,coordinates.at(-2)!]].flatMap(([point,neighbor])=>{const dx=point[0]-neighbor[0],dy=point[1]-neighbor[1],length=Math.hypot(dx,dy);if(!length)return[];const perpendicular=[-dy/length*size,dx/length*size];return[new LineString([[point[0]-perpendicular[0],point[1]-perpendicular[1]],[point[0]+perpendicular[0],point[1]+perpendicular[1]]])]})}
function formatMeasurement(value:number,area:boolean){return area?(value>=1_000_000?`${(value/1_000_000).toFixed(2)} km²`:`${Math.round(value)} m²`):(value>=1000?`${(value/1000).toFixed(2)} km`:`${Math.round(value)} m`)}

export function MeasurementPanel({map,rasterPath}:{map:Map|null;rasterPath?:string}){
 const source=useRef(new VectorSource()),draws=useRef<Draw[]>([]),[mode,setMode]=useState<Mode>('pan'),[revision,setRevision]=useState(0),[profiles,setProfiles]=useState<ElevationProfileRoute[]>([]),[showProfile,setShowProfile]=useState(false),generation=useRef(0);
 useEffect(()=>{if(!map)return;const layer=new VectorLayer({source:source.current,style:(feature,resolution)=>{const geometry=feature.getGeometry(),area=geometry instanceof Polygon,value=geometry instanceof Polygon?geodesicArea(geometry,{projection:'EPSG:3857'}):geometry instanceof LineString?geodesicLength(geometry,{projection:'EPSG:3857'}):0,label=formatMeasurement(value,area),text=new Text({text:label,font:'bold 13px sans-serif',fill:new Fill({color:'#fff'}),stroke:new Stroke({color:'#101713',width:4}),backgroundFill:new Fill({color:'#101713dd'}),padding:[4,6,4,6]}),styles=[new Style({stroke:new Stroke({color:'#101713',width:7,lineCap:'round',lineJoin:'round'}),fill:new Fill({color:'rgba(216,255,85,.16)'})}),new Style({stroke:new Stroke({color:'#d8ff55',width:3,lineCap:'round',lineJoin:'round'}),fill:new Fill({color:'rgba(216,255,85,.16)'})})];if(geometry instanceof LineString)for(const cap of measurementEndCaps(geometry,resolution)){styles.push(new Style({geometry:cap,stroke:new Stroke({color:'#101713',width:7,lineCap:'round'})}),new Style({geometry:cap,stroke:new Stroke({color:'#d8ff55',width:3,lineCap:'round'})}))}styles.push(new Style({text,geometry:geometry instanceof LineString?new Point(geometry.getCoordinateAt(.5)):undefined}));return styles},zIndex:100});map.addLayer(layer);
  const distance=new Draw({source:source.current,type:'LineString',minPoints:2,stopClick:true}),area=new Draw({source:source.current,type:'Polygon',minPoints:3,stopClick:true});for(const draw of [distance,area])draw.on('drawend',event=>{const feature=event.feature,geometry=feature.getGeometry();if(geometry instanceof LineString||geometry instanceof Polygon){for(const previous of source.current.getFeatures()){if(previous===feature)continue;const previousGeometry=previous.getGeometry();if(geometry instanceof LineString&&previousGeometry instanceof LineString||geometry instanceof Polygon&&previousGeometry instanceof Polygon)source.current.removeFeature(previous)}}generation.current++;setProfiles([]);setShowProfile(false);setRevision(value=>value+1)});draws.current=[distance,area];map.addInteraction(distance);map.addInteraction(area);
  return()=>{generation.current++;map.removeInteraction(distance);map.removeInteraction(area);map.removeLayer(layer);draws.current=[]};
 },[map,rasterPath]);
 useEffect(()=>{draws.current[0]?.setActive(mode==='distance');draws.current[1]?.setActive(mode==='area')},[mode,map]);
 useEffect(()=>{generation.current++;setShowProfile(false);setProfiles([]);return()=>{generation.current++}},[rasterPath]);
 const openProfile=()=>{if(!rasterPath)return;if(showProfile){setShowProfile(false);generation.current++;return}const lines=source.current.getFeatures().filter(feature=>feature.getGeometry() instanceof LineString);if(!lines.length)return;const token=++generation.current;setProfiles([]);setShowProfile(true);void Promise.all(lines.map(async feature=>{const line=feature.getGeometry() as LineString,id=String(feature.getId()??`measure-${Date.now()}`);feature.setId(id);return makeProfile(rasterPath,sampledCoordinates(line),id)})).then(results=>{if(token===generation.current)setProfiles(results.filter((profile):profile is ElevationProfileRoute=>profile!==null))})};
 const remove=()=>{source.current.clear();generation.current++;setProfiles([]);setShowProfile(false);setRevision(value=>value+1)};
 return <><aside className="measurement-tools-float measurement-tools-standalone" aria-label={translateText('Herramientas de rutas y mediciones')}><b>{translateText('Mediciones')}</b><button className={mode==='distance'?'active':''} aria-pressed={mode==='distance'} onClick={()=>setMode(mode==='distance'?'pan':'distance')}><span className="point-tool-symbol"><svg className="tool-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 19 14-14M7.5 16.5l-2-2m5-1-2-2m5-1-2-2m5-1-2-2"/><path d="M15 5h4v4"/></svg></span>{translateText('Medir distancia')}</button>{rasterPath&&source.current.getFeatures().some(feature=>feature.getGeometry() instanceof LineString)&&<button className={showProfile?'active':''} aria-pressed={showProfile} onClick={openProfile}><span className="point-tool-symbol"><svg className="tool-icon" viewBox="0 0 24 24" width="15" height="15" aria-hidden="true"><path fill="currentColor" d="M1 20 8.2 6.5l4.1 7.1 3.1-4.2L23 20H1Z"/></svg></span>{translateText('Perfil de distancia')}</button>}<button className={mode==='area'?'active':''} aria-pressed={mode==='area'} onClick={()=>setMode(mode==='area'?'pan':'area')}><span className="point-tool-symbol">⬠</span>{translateText('Medir área')}</button>{source.current.getFeatures().length>0&&<button onClick={remove}><span className="point-tool-symbol">×</span>{translateText('Borrar medidas')}</button>}{mode!=='pan'&&<small>{translateText(mode==='distance'?'Haz clic para añadir puntos y doble clic para terminar la distancia.':'Haz clic para marcar el contorno y doble clic para terminar el área.')}</small>}<span hidden>{revision}</span></aside>{showProfile&&profiles.length>0&&<ElevationProfileOverlay routes={profiles} movable placement="bottom-right" />}</>;
}
