export const terrainLayerOptions=[['points','Puntos'],['pointLabels','Etiquetas'],['barriers','Barreras'],['crossings','Puentes y pasos'],['corridors','Corredores preferentes'],['pointsOfInterest','Puntos de interés'],['contours','Curvas de nivel'],['highestPoint','Punto más alto'],['scale','Escala']] as const;
type Layer=typeof terrainLayerOptions[number][0];
export interface TerrainToolbarState{exaggeration:number;routeWidth:number;palette:string;textureId:string;textureOptions:{id:string;name:string}[];textureDisabled:boolean;textureLoading:boolean;contoursAvailable:boolean;layers:Record<Layer,boolean>}
export type TerrainToolbarAction={type:'exaggeration'|'routeWidth';value:number}|{type:'palette'|'texture';value:string}|{type:'layer';key:Layer;value:boolean};
export function Terrain3DToolbar({state,onAction,onReturn,onDetach}:{state:TerrainToolbarState;onAction:(action:TerrainToolbarAction)=>void;onReturn?:()=>void;onDetach?:()=>void}){
 return <div className="terrain-3d-toolbar">{(onReturn||onDetach)&&<span className="terrain-3d-detach-control"><button type="button" className="terrain-3d-detach" title={onReturn?'Volver al visor integrado':'Abrir el visor 3D en una ventana independiente'} aria-label={onReturn?'Volver al visor integrado':'Abrir el visor 3D en una ventana independiente'} onClick={onReturn??onDetach}><span aria-hidden="true">{onReturn?'↙':'↗'}</span></button></span>}<strong>Visor 3D</strong><div className="terrain-3d-toolbar-options">
 <label>Exageración vertical <input type="range" min="0" max="8" step="0.5" value={state.exaggeration} onChange={e=>onAction({type:'exaggeration',value:Number(e.target.value)})}/><span>{state.exaggeration===0?'0 %':`${state.exaggeration.toFixed(1)}×`}</span></label>
 <label>Grosor de rutas <input type="range" min="1" max="12" step="1" value={state.routeWidth} onChange={e=>onAction({type:'routeWidth',value:Number(e.target.value)})}/><span>{state.routeWidth} px</span></label>
 <label>Paleta <select value={state.palette} onChange={e=>onAction({type:'palette',value:e.target.value})}>{[['grayscale','Grises'],['terrain','Terreno'],['hypsometric','Hipsométrica'],['viridis','Viridis'],['alpine','Alta montaña']].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
 <label>Capa base sobre el modelo <select value={state.textureId} disabled={state.textureDisabled} onChange={e=>onAction({type:'texture',value:e.target.value})}><option value="none">Sin mapa · paleta del MDT</option>{state.textureOptions.map(({id,name})=><option key={id} value={id}>{name}</option>)}</select></label>
 <div className="terrain-3d-layers">{terrainLayerOptions.map(([key,label])=><label key={key} title={key==='contours'&&!state.contoursAvailable?'Calcule primero las curvas de nivel':undefined}><input type="checkbox" checked={state.layers[key]} disabled={key==='contours'&&!state.contoursAvailable} onChange={e=>onAction({type:'layer',key,value:e.target.checked})}/>{label}</label>)}</div>
 {state.textureLoading&&<span className="terrain-texture-loading">Preparando mapa…</span>}
 </div></div>;
}
