import {useEffect,useMemo,useRef,useState} from 'react';
import type {ContourResult,GeoPoint,ViewshedResult} from '../types';
import type {RasterResult,TerrainMesh} from '../services/native';
import {calculateContours,calculateViewshed,generateTerrainMesh} from '../services/native';
import {viewshedDataUrl} from '../core/topographicAnalysis';
import {SurfaceAnalysisViewer} from './SurfaceAnalysisViewer';
import type {SharedMapView,StudyExtent} from './MapPanel';
import {Terrain3D} from './Terrain3D';
import {levelColor} from '../core/comparisonColors';
import {ViewerIcon} from './ViewerIcon';
import {locale} from '../core/i18n';

interface Props{tool:'contours'|'viewshed';raster:RasterResult|null;points:GeoPoint[];studyExtent:StudyExtent|null;previewImage?:string;initialView:SharedMapView;onNotice:(value:string)=>void;onComplete?:()=>void;onCalculationStatus?:(status:'running'|'success'|'error')=>void;onViewshedResult?:(result:ViewshedResult,activeObserver:number)=>void;onContourResult?:(result:ContourResult)=>void}
export function TopographicTools({tool,raster,points,studyExtent,previewImage,initialView,onNotice,onComplete:notifyComplete,onCalculationStatus,onViewshedResult,onContourResult}:Props){
 const [interval,setInterval]=useState(100),[height,setHeight]=useState(1.7),[contours,setContours]=useState<ContourResult|null>(null),[viewshed,setViewshed]=useState<ViewshedResult|null>(null),[selected,setSelected]=useState<number[]>([]),[activeObserver,setActiveObserver]=useState(0),[busy,setBusy]=useState(false),[viewer,setViewer]=useState<'contours'|'viewshed'|null>(null),[mesh,setMesh]=useState<TerrainMesh|null>(null),[show3d,setShow3d]=useState(false);
 const completedWhileBusy=useRef(false),previousBusy=useRef(false),onComplete=()=>{completedWhileBusy.current=true;onCalculationStatus?.('success');notifyComplete?.()};
 useEffect(()=>{if(busy&&!previousBusy.current){completedWhileBusy.current=false;onCalculationStatus?.('running')}else if(!busy&&previousBusy.current&&!completedWhileBusy.current)onCalculationStatus?.('error');previousBusy.current=busy},[busy,onCalculationStatus]);
 const observer=viewshed?.observers[activeObserver],surface=useMemo(()=>observer?viewshedDataUrl(observer):'',[observer]);
 useEffect(()=>{if(viewshed)onViewshedResult?.(viewshed,activeObserver)},[viewshed,activeObserver]);
 const contourLevels=useMemo(()=>contours?[...new Set(contours.lines.map(line=>line.level))].sort((a,b)=>a-b):[],[contours]);
 const contourLegend=<div className="isochrone-viewer-legend"><b>Altura de las curvas</b>{contourLevels.map((level,index)=><span key={level}><i style={{background:levelColor(index,contourLevels.length)}}/>{level.toLocaleString(locale(),{maximumFractionDigits:1})} m</span>)}</div>;
 const runContours=async()=>{if(!raster)return;setBusy(true);try{const result=await calculateContours(raster.path,interval);setContours(result);onContourResult?.(result);onNotice(`${result.lines.length.toLocaleString(locale())} segmentos de curvas calculados sobre el MDT.`);onComplete?.()}catch(e){onNotice(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const runViewshed=async()=>{if(!raster)return;if(!selected.length){onNotice('Seleccione al menos un punto de observación.');return}setBusy(true);try{const chosen=points.filter(p=>selected.includes(p.id));const result=await calculateViewshed(raster.path,chosen.map(p=>({id:String(p.id),name:p.name,coordinate:[p.lon,p.lat]})),height);setViewshed(result);setActiveObserver(0);onViewshedResult?.(result,0);onNotice(`Visibilidad calculada por separado para ${result.observers.length} observador(es).`);onComplete?.()}catch(e){onNotice(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const open3d=async()=>{if(!raster)return;setBusy(true);try{setMesh(mesh??await generateTerrainMesh(raster.path,450));setShow3d(true);completedWhileBusy.current=true;onCalculationStatus?.('success')}catch(e){onNotice(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <div className="analysis-output">
 {tool==='contours'?<><p className="hint">Extracción independiente del cálculo de rutas sobre el MDT cargado.</p><div className="analysis-settings"><label>Intervalo<select value={[10,20,50,100].includes(interval)?interval:'custom'} onChange={e=>e.target.value!=='custom'&&setInterval(Number(e.target.value))}><option value="10">10 m</option><option value="20">20 m</option><option value="50">50 m</option><option value="100">100 m</option><option value="custom">Personalizado</option></select></label><label>Intervalo personalizado<input type="number" min=".1" max="10000" step="1" value={interval} onChange={e=>setInterval(Math.max(.1,Number(e.target.value)||.1))}/><span>m</span></label></div><button className="primary wide" disabled={busy||!raster} onClick={()=>void runContours()}>{busy?'Calculando…':'Extraer curvas de nivel'}</button>{busy&&<div className="comparison-progress indeterminate" role="progressbar" aria-label="Extracción de curvas de nivel en curso"><div><i/></div><span>Analizando el modelo digital y extrayendo curvas…</span></div>}{contours&&<><div className="isochrone-summary"><b>{contours.lines.length.toLocaleString(locale())} segmentos</b><span>{contours.minElevationM.toFixed(1)}–{contours.maxElevationM.toFixed(1)} m</span><span>{contours.rasterCrs} · píxel {contours.resolutionM.toFixed(1)} m</span></div><button className="secondary wide viewer-button" onClick={()=>setViewer('contours')}><ViewerIcon/>Abrir visor de curvas de nivel</button></>}</>:
 <><p className="hint">Seleccione observadores existentes. Cada resultado se conserva por separado.</p><div className="comparison-profile-selection">{points.map(p=><label className="check" key={p.id}><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.id]:s.filter(id=>id!==p.id))}/>{p.name}</label>)}</div><div className="analysis-settings"><label>Altura del observador<select value={[1.7,3,10].includes(height)?height:'custom'} onChange={e=>e.target.value!=='custom'&&setHeight(Number(e.target.value))}><option value="1.7">Humana · 1,7 m</option><option value="3">Trípode · 3 m</option><option value="10">Torre · 10 m</option><option value="custom">Personalizada</option></select></label><label>Altura personalizada<input type="number" min="0" max="1000" step=".1" value={height} onChange={e=>setHeight(Math.max(0,Number(e.target.value)||0))}/><span>m</span></label></div><button className="primary wide" disabled={busy||!raster||!points.length} onClick={()=>void runViewshed()}>{busy?'Calculando…':'Calcular visibilidad'}</button>{viewshed&&<><label>Resultado <select value={activeObserver} onChange={e=>setActiveObserver(Number(e.target.value))}>{viewshed.observers.map((o,i)=><option value={i} key={o.observerId}>{o.observerName}</option>)}</select></label>{observer&&<div className="isochrone-summary"><b>{observer.visibleCells.toLocaleString(locale())} celdas visibles</b><span>{observer.validCells.toLocaleString(locale())} válidas</span><span>Terreno {observer.groundElevationM.toFixed(1)} m + {observer.observerHeightM.toFixed(1)} m</span></div>}<button className="secondary wide viewer-button" onClick={()=>setViewer('viewshed')}><ViewerIcon/>Abrir visor de visibilidad</button></>}</>}
 {viewer&&studyExtent&&previewImage&&(viewer==='contours'&&contours?<SurfaceAnalysisViewer title="Curvas de nivel" fileBase="curvas-nivel" points={points} selectedPointId={null} barriers={[]} corridors={[]} crossings={[]} route={null} initialView={initialView} studyExtent={studyExtent} mdtImageUrl={previewImage} lines={contours.lines} legend={contourLegend} onClose={()=>setViewer(null)}/>:observer?<SurfaceAnalysisViewer title={`Visibilidad · ${observer.observerName}`} fileBase={`visibilidad-${observer.observerName}`} points={points} selectedPointId={Number(observer.observerId)} barriers={[]} corridors={[]} crossings={[]} route={null} initialView={initialView} studyExtent={studyExtent} mdtImageUrl={previewImage} surfaceImageUrl={surface} surfaceLabel="Visible / no visible" legend={<div className="isochrone-viewer-legend"><b>Visibilidad topográfica</b><span><i style={{background:'#23e169'}}/>Visible</span><span><i style={{background:'#eb4646'}}/>No visible</span></div>} onClose={()=>setViewer(null)}/>:null)}
 {show3d&&mesh&&observer&&<section className="terrain-3d-overlay"><button className="terrain-3d-close" aria-label="Cerrar visor 3D" onClick={()=>setShow3d(false)}>×</button><div className="terrain-3d-stage"><Terrain3D mesh={mesh} exaggeration={1} palette="terrain" points={points} routes={[]} corridorSurface={{width:observer.surfaceWidth,height:observer.surfaceHeight,values:observer.surfaceValues,kind:'viewshed'}} onSnapshotReady={()=>{}} resetToken={0}/></div></section>}
 </div>
}
