import {CalculationButton} from './CalculationButton';
import {runCalculation} from '../services/calculationTasks';
import {trackProcess} from '../core/processStatus';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import type {ContourResult,GeoPoint,ViewshedObserverResult,ViewshedResult} from '../types';
import type {RasterResult,TerrainMesh} from '../services/native';
import {calculateContours,calculateViewshed,generateTerrainMesh} from '../services/native';
import {viewshedDataUrl} from '../core/topographicAnalysis';
import {SurfaceAnalysisViewer} from './SurfaceAnalysisViewer';
import type {SharedMapView,StudyExtent} from './MapPanel';
import {Terrain3D} from './Terrain3D';
import {levelColor} from '../core/comparisonColors';
import {ViewerIcon} from './ViewerIcon';
import {locale,translateText,useLanguage} from '../core/i18n';
import {terrainPeaks} from '../core/terrainPeaks';
import type {ContourDisplayStyle} from '../core/contourDisplayStyle';

interface Props{validationError?:string|null;tool:'contours'|'viewshed';raster:RasterResult|null;points:GeoPoint[];studyExtent:StudyExtent|null;imageExtent?:StudyExtent;previewImage?:string;initialView:SharedMapView;onNotice:(value:string)=>void;onComplete?:()=>void;onCalculationStatus?:(status:'running'|'success'|'error')=>void;onViewshedResult?:(result:ViewshedResult,activeObserver:number)=>void;viewshedObservers?:ViewshedObserverResult[];visibleViewshedIds?:string[];onViewshedVisibilityChange?:(id:string,visible:boolean)=>void;onContourResult?:(result:ContourResult)=>void;contourDisplayStyle?:ContourDisplayStyle;onContourDisplayStyleChange?:(style:ContourDisplayStyle)=>void}
export function TopographicTools({validationError,tool,raster,points,studyExtent,imageExtent,previewImage,initialView,onNotice,onComplete:notifyComplete,onCalculationStatus,onViewshedResult,viewshedObservers,visibleViewshedIds=[],onViewshedVisibilityChange,onContourResult,contourDisplayStyle,onContourDisplayStyleChange}:Props){
 const language=useLanguage();
 const [interval,setInterval]=useState(100),[height,setHeight]=useState(1.7),[contours,setContours]=useState<ContourResult|null>(null),[viewshed,setViewshed]=useState<ViewshedResult|null>(null),[busy,setBusy]=useState(false),[viewer,setViewer]=useState<'contours'|'viewshed'|null>(null),[mesh,setMesh]=useState<TerrainMesh|null>(null),[peakMesh,setPeakMesh]=useState<{rasterPath:string;mesh:TerrainMesh}|null>(null),[showPeaks,setShowPeaks]=useState(true),[peakLabels,setPeakLabels]=useState<{coordinate:[number,number];label:string}[]>([]),[show3d,setShow3d]=useState(false);
 const completedWhileBusy=useRef(false),previousBusy=useRef(false),onComplete=()=>{completedWhileBusy.current=true;onCalculationStatus?.('success');notifyComplete?.()};
 useEffect(()=>{if(busy&&!previousBusy.current){completedWhileBusy.current=false;onCalculationStatus?.('running')}else if(!busy&&previousBusy.current&&!completedWhileBusy.current)onCalculationStatus?.('error');previousBusy.current=busy},[busy,onCalculationStatus]);
 const observers=viewshedObservers??viewshed?.observers??[],activeObserver=observers.findIndex(item=>visibleViewshedIds.includes(item.observerId)),activeObserverIndex=activeObserver<0?0:activeObserver,observer=observers[activeObserverIndex],surface=useMemo(()=>observer?viewshedDataUrl(observer):'',[observer]);
 useEffect(()=>{if(viewshed)onViewshedResult?.(viewshed,activeObserverIndex)},[viewshed,activeObserverIndex,onViewshedResult]);
 useEffect(()=>{if(viewer!=='contours'||!raster)return;let active=true;setPeakMesh(null);setPeakLabels([]);void generateTerrainMesh(raster.path,700).then(terrain=>{if(!active)return;setMesh(terrain);setPeakMesh({rasterPath:raster.path,mesh:terrain})}).catch(error=>{if(active)onNotice(error instanceof Error?`No se pudieron localizar los picos del terreno: ${error.message}`:'No se pudieron localizar los picos del terreno.')});return()=>{active=false}},[viewer,raster?.path,onNotice]);
 const updatePeaksForExtent=useCallback((extent:[number,number,number,number],limit:number,globalView:boolean)=>{if(!peakMesh||peakMesh.rasterPath!==raster?.path)return;if(limit===0){setPeakLabels([]);return}const approximateWidthM=(extent[2]-extent[0])*111320*Math.cos((extent[1]+extent[3])*.5*Math.PI/180),approximateHeightM=(extent[3]-extent[1])*110540,separationM=Math.max(100,Math.min(1200,(approximateWidthM+approximateHeightM)/60)),peaks=globalView?terrainPeaks(peakMesh.mesh,1):terrainPeaks(peakMesh.mesh,limit,separationM,extent);setPeakLabels(peaks.map(peak=>({coordinate:[peak.lon,peak.lat],label:`▲ ${peak.elevationM.toLocaleString(locale(),{maximumFractionDigits:0})} m` })))},[peakMesh,raster?.path]);
 const contourLevels=useMemo(()=>contours?[...new Set(contours.lines.map(line=>line.level))].sort((a,b)=>a-b):[],[contours]);
 const contourLegend=<div className="isochrone-viewer-legend"><b>Altura de las curvas</b>{contourLevels.map((level,index)=><span key={level}><i style={{background:levelColor(index,contourLevels.length)}}/>{level.toLocaleString(locale(),{maximumFractionDigits:1})} m</span>)}</div>;
 const runContours=async()=>{return runCalculation('contours',async(process)=>{if(validationError){onNotice(validationError);return;}if(!raster)return;setBusy(true);try{const result=await calculateContours(raster.path,interval);setContours(result);onContourResult?.(result);onNotice(`${result.lines.length.toLocaleString(locale())} segmentos de curvas calculados sobre el MDT.`);onComplete?.()}catch(e){process.fail(e);onNotice(e instanceof Error?e.message:String(e))}finally{setBusy(false)}});};
 const runViewshed=async()=>{return runCalculation('viewshed',async(process)=>{if(validationError){onNotice(validationError);return;}if(!raster)return;if(!points.length){onNotice('Añada puntos en el visor de selección antes de calcular la visibilidad.');return}setBusy(true);try{const result=await calculateViewshed(raster.path,points.map(p=>({id:String(p.id),name:p.name,coordinate:[p.lon,p.lat]})),height);setViewshed(result);onNotice(`Visibilidad calculada para ${result.observers.length} punto(s).`);onComplete?.()}catch(e){process.fail(e);onNotice(e instanceof Error?e.message:String(e))}finally{setBusy(false)}});};
 const open3d=async()=>{return trackProcess(async(process)=>{if(!raster)return;setBusy(true);try{setMesh(mesh??await generateTerrainMesh(raster.path,450));setShow3d(true);completedWhileBusy.current=true;onCalculationStatus?.('success')}catch(e){process.fail(e);onNotice(e instanceof Error?e.message:String(e))}finally{setBusy(false)}});};
 return <div className="analysis-output">
 {tool==='contours'?<><div className="analysis-settings"><label>Intervalo<select value={interval} onChange={e=>setInterval(Number(e.target.value))}><option value="10">10 m</option><option value="20">20 m</option><option value="50">50 m</option><option value="100">100 m</option><option value="200">200 m</option><option value="250">250 m</option><option value="500">500 m</option><option value="1000">1000 m</option></select></label>{<label>Estilo <select value={contourDisplayStyle?.mode??'topographic'} onChange={event=>onContourDisplayStyleChange?.({...contourDisplayStyle!,mode:event.target.value as 'topographic'|'elevation'})}><option value="topographic">Topográfico</option><option value="elevation">Color por altitud</option></select></label>}{(contourDisplayStyle?.mode??'topographic')==='topographic'&&<label>Trazo <select value={contourDisplayStyle?.color??'#111111'} onChange={event=>onContourDisplayStyleChange?.({...contourDisplayStyle!,color:event.target.value as ContourDisplayStyle['color']})}><option value="#ffffff">Blanco</option><option value="#111111">Negro</option><option value="#ff8c00">Naranja</option><option value="#d8ff55">Lima</option></select></label>}<label>Curva maestra <select value={contourDisplayStyle?.majorInterval??5} onChange={event=>onContourDisplayStyleChange?.({...contourDisplayStyle!,majorInterval:Number(event.target.value) as 0|3|5|10})}><option value={0}>Sin curva maestra</option><option value={3}>Cada 3 curvas</option><option value={5}>Cada 5 curvas</option><option value={10}>Cada 10 curvas</option></select></label></div><CalculationButton mode="contours" disabled={!raster||Boolean(validationError)} onClick={()=>void runContours()} onError={onNotice}>Extraer curvas de nivel</CalculationButton>{busy&&<div className="comparison-progress indeterminate" role="progressbar" aria-label="Extracción de curvas de nivel en curso"><div><i/></div><span>Analizando el modelo digital y extrayendo curvas…</span></div>}{contours&&<><div className="isochrone-summary"><b>{contours.lines.length.toLocaleString(locale())} segmentos</b><span>{contours.minElevationM.toFixed(1)}–{contours.maxElevationM.toFixed(1)} m</span><span>{contours.rasterCrs} · píxel {contours.resolutionM.toFixed(1)} m</span></div><button className="secondary wide viewer-button" onClick={()=>setViewer('contours')}><ViewerIcon/>Abrir visor de curvas de nivel</button></>}</>:
 <><div className="analysis-settings"><label>Altura del observador<select value={[1.7,3,10].includes(height)?height:'custom'} onChange={e=>e.target.value!=='custom'&&setHeight(Number(e.target.value))}><option value="1.7">Humana · 1,7 m</option><option value="3">Trípode · 3 m</option><option value="10">Torre · 10 m</option><option value="custom">Personalizada</option></select></label><label>Altura personalizada<input type="number" min="0" max="1000" step=".1" value={height} onChange={e=>setHeight(Math.max(0,Number(e.target.value)||0))}/><span>m</span></label></div><CalculationButton mode="viewshed" disabled={!raster||!points.length||Boolean(validationError)} onClick={()=>void runViewshed()} onError={onNotice}>Calcular visibilidad</CalculationButton>{observers.length>0&&<><div className="viewshed-results-card"><div className="viewshed-summary"><span>{translateText('Altura:',language)} {observer?.observerHeightM.toLocaleString(locale(),{minimumFractionDigits:1,maximumFractionDigits:1})} m</span></div><div className="viewshed-observer-list" aria-label={translateText('Observadores calculados',language)}>{observers.map((item,index)=><label key={item.observerId} className="viewshed-observer-item"><input type="checkbox" checked={visibleViewshedIds.includes(item.observerId)} onChange={event=>onViewshedVisibilityChange?.(item.observerId,event.target.checked)}/><span>{item.observerName||`${translateText('Punto',language)} ${index+1}`}</span></label>)}</div></div><button className="secondary wide viewer-button" onClick={()=>setViewer('viewshed')}><ViewerIcon/>{translateText('Abrir visor de visibilidad',language)}</button></>}</>}
 {viewer&&studyExtent&&previewImage&&(viewer==='contours'&&contours?<SurfaceAnalysisViewer title="Curvas de nivel" points={points} selectedPointId={null} barriers={[]} corridors={[]} crossings={[]} route={null} initialView={initialView} studyExtent={studyExtent} imageExtent={imageExtent} mdtImageUrl={previewImage} rasterPath={raster?.path} lines={contours.lines} contourIntervalM={contours.intervalM} peakLabels={peakLabels} showPeaks={showPeaks} onShowPeaksChange={setShowPeaks} onPeakViewChange={updatePeaksForExtent} contourDisplayStyle={contourDisplayStyle} onContourDisplayStyleChange={onContourDisplayStyleChange} legend={contourLegend} onClose={()=>setViewer(null)}/>:observer?<SurfaceAnalysisViewer title={`Visibilidad · ${observer.observerName}`} points={points} selectedPointId={Number(observer.observerId)} barriers={[]} corridors={[]} crossings={[]} route={null} initialView={initialView} studyExtent={studyExtent} imageExtent={imageExtent} mdtImageUrl={previewImage} rasterPath={raster?.path} surfaceImageUrl={surface} surfaceLabel="Visible / no visible" viewshedResults={observers} visibleViewshedIds={visibleViewshedIds} onViewshedVisibilityChange={onViewshedVisibilityChange} legend={<div className="isochrone-viewer-legend"><b>Visibilidad topográfica</b><span><i style={{background:'#23e169'}}/>Visible</span><span><i style={{background:'#eb4646'}}/>No visible</span></div>} onClose={()=>setViewer(null)}/>:null)}
 {show3d&&mesh&&observer&&<section className="terrain-3d-overlay"><button className="terrain-3d-close" aria-label="Cerrar visor 3D" onClick={()=>setShow3d(false)}>×</button><div className="terrain-3d-stage"><Terrain3D mesh={mesh} exaggeration={1} palette="terrain" points={points} routes={[]} corridorSurface={{width:observer.surfaceWidth,height:observer.surfaceHeight,values:observer.surfaceValues,kind:'viewshed'}} onSnapshotReady={()=>{}} resetToken={0}/></div></section>}
 </div>
}
