import {CONTACT_EMAIL,CONTACT_HREF} from '../core/contact';
import {useEffect, useState} from 'react';
import {MODELS} from '../core/costModels';
import {MODEL_HELP} from '../core/calculationHelp';
import type {ModelId} from '../types';
import {TerrainBackdrop} from './TerrainBackdrop';

type Lang='es'|'en';
const modelIds=Object.keys(MODELS) as ModelId[];
const software=[['React / React DOM','MIT'],['OpenLayers','BSD-2-Clause'],['Three.js','MIT'],['jsPDF','MIT'],['Tauri / Dialog','Apache-2.0 OR MIT'],['Vite','MIT'],['TypeScript','Apache-2.0'],['Vitest / Testing Library / jsdom','MIT'],['GDAL','MIT/X'],['PROJ','MIT'],['Rust / Cargo','Apache-2.0 OR MIT'],['Tokio','MIT'],['Reqwest','Apache-2.0 OR MIT'],['Serde / Serde JSON','Apache-2.0 OR MIT'],['Futures Util','Apache-2.0 OR MIT'],['URL / UUID / Base64 / Thiserror','MIT OR Apache-2.0']];

const copy={
 es:{
  menu:'Menú',openMenu:'Abrir navegación',language:'Idioma',nav:['El programa','Funciones','Perfiles','Investigación','Autor','Descargas'],
  heroEye:'Análisis territorial · arqueología del paisaje',heroA:'Leer el territorio.',heroB:'Ensayar el movimiento.',heroText:'Una herramienta de escritorio para explorar caminos de menor coste, accesibilidad y relaciones espaciales sobre modelos reales de elevación.',discover:'Descubrir ViaSpania',downloadsLink:'Ver descargas',scroll:'Desplázate para recorrer el relieve',
  programEye:'El programa',programTitle:'Del relieve a una hipótesis que se puede observar.',programText:['ViaSpania reúne cartografía, modelos digitales de elevación y cálculo de coste en un flujo local. Seleccionas un área, sitúas los elementos relevantes, eliges un perfil de movimiento y comparas el resultado sobre mapas sincronizados y terreno tridimensional.','No presenta la ruta calculada como una verdad histórica. La convierte en una hipótesis explícita, reproducible y abierta a comparación.'],stats:['perfiles de desplazamiento','familias de análisis','flujo local','hipótesis comparables'],
  functionsEye:'Un laboratorio territorial',functionsTitle:'Una aplicación, múltiples escalas de lectura.',functionsIntro:'Desde el trayecto entre dos puntos hasta una red completa de desplazamientos, cada cálculo conserva su contexto, parámetros y atribuciones.',functions:[['Rutas de menor coste','Calcula ida y vuelta por separado y permite obtener entre 2 y 10 rutas subóptimas espacialmente diferenciadas. El rango 1 es el óptimo y los costes de todos los rangos se evalúan sobre la superficie original.'],['Comparación de perfiles','Superpone modelos manteniendo los mismos extremos y condiciones para estudiar cómo cambia cada trazado.'],['Multipunto','Construye una matriz dirigida de rutas entre hasta ocho puntos; permite leer accesibilidad y asimetrías.'],['Multirruta','Encadena los puntos en el orden elegido. Sus rutas subóptimas son itinerarios completos 1→2→3…, no combinaciones independientes de tramos.'],['Isócronas y superficies','Delimita áreas alcanzables desde uno o varios orígenes y visualiza el coste acumulado.'],['Pasillos de menor coste','Muestra alternativas cercanas al óptimo dentro de un umbral porcentual configurable.'],['Lectura topográfica','Genera visibilidad e isolíneas a partir del modelo de elevación, sin inventar vegetación ni edificios.'],['Terreno 3D y resultados','Explora el relieve, las rutas y los análisis con textura cartográfica, cámara y exportación visual.']],
  noveltyEye:'Lo diferencial',noveltyTitle:'El paisaje no es una superficie neutra.',noveltyIntro:'ViaSpania permite construir escenarios más ricos que una simple pendiente: incorpora elementos culturales, restricciones graduadas y lugares de paso.',novelty:[['Puntos de interés','Añade lugares significativos al proyecto sin obligarlos a ser origen o destino.'],['Barreras graduadas','Representa límites absolutos o permeables y ajusta cuánto penalizan el paso.'],['Corredores preferentes','Introduce ejes que facilitan el tránsito cuando la hipótesis arqueológica lo justifica.'],['Pasos y puentes','Abre cruces concretos sobre barreras, evitando simplificaciones de todo o nada.'],['Rutas subóptimas','Penaliza temporalmente las celdas ya utilizadas para revelar opciones espacialmente distintas; no las presenta como los k caminos mínimos exactos.'],['Multipunto','Compara redes dirigidas completas, no solo una pareja de lugares.'],['Multirruta','Estudia itinerarios secuenciales completos y compara su incremento de coste y solapamiento respecto al óptimo.']],researchEye:'Arqueología espacial y del paisaje',quote:'La eficacia no está en producir una única línea «correcta», sino en hacer visibles los supuestos y comprobar cómo cambia el resultado.',research:['Los modos multipunto y multirruta permiten estudiar conectividad, direccionalidad, secuencias y jerarquías entre lugares. Las rutas subóptimas amplían este contraste: cada nuevo rango penaliza las celdas usadas anteriormente, pero su coste se vuelve a medir sin esa penalización para conservar la comparabilidad.','La combinación de mapas familiares, comparación visual y terreno 3D también facilita explicar el método a estudiantes y público no especializado. Los resultados son interpretables, exportables y siempre se acompañan de sus límites.'],
  profilesEye:'Perfiles de desplazamiento',profilesTitle:'Quince maneras de preguntar al terreno.',profilesIntro:'Los perfiles no son intercambiables: unos estiman tiempo, otros energía o coste relativo. Elige un modelo según la población, el modo de transporte y la pregunta arqueológica.',directional:'Direccional',symmetric:'Simétrico',profileLabels:['Qué calcula','Qué puedes ajustar','Precauciones','Bibliografía básica'],modelNote:'Todos los perfiles admiten conectividad y elementos del paisaje. ViaSpania muestra las unidades y evita comparar directamente segundos, julios y coste relativo.',
  openEye:'Código abierto',openTitle:'Construido sobre conocimiento compartido.',openIntro:'ViaSpania ha sido programado íntegramente combinando tecnologías de código abierto. Cada dependencia conserva sus avisos y cada modelo científico cita su fuente.',attribution:'Cartografía y datos: © colaboradores de OpenStreetMap (ODbL 1.0); Instituto Geográfico Nacional / Centro Nacional de Información Geográfica, según sus condiciones de reutilización; Copernicus Land Monitoring Service / Agencia Europea de Medio Ambiente. Base metodológica reconocida: paquete R movecost, de Gianmarco Alberti.',
  authorEye:'Sobre el autor',authorText:'Este espacio recogerá próximamente la formación, trayectoria e intereses de investigación del creador de ViaSpania.',bioSoon:'Biografía en preparación',publications:'Publicaciones',publicationsTitle:'Investigación y textos',publicationsText:'La bibliografía personal y las publicaciones se incorporarán aquí en una próxima actualización.',catalogSoon:'Catálogo en preparación',
  downloadsEye:'Descargas',downloadsTitle:'ViaSpania en tu escritorio.',downloadsText:'Las versiones instalables aparecerán aquí cuando estén preparadas para distribución. El cálculo se ejecuta en tu equipo y los proyectos permanecen bajo tu control.',soon:'Próximamente',contact:'Contacto',contactTitle:'¿Una pregunta, una idea\no un caso de estudio?',licenses:'Licencias',back:'Volver arriba ↑',summary:'Resumen'
 },
 en:{
  menu:'Menu',openMenu:'Open navigation',language:'Language',nav:['The software','Features','Profiles','Research','Author','Downloads'],
  heroEye:'Territorial analysis · landscape archaeology',heroA:'Read the landscape.',heroB:'Explore movement.',heroText:'A desktop tool for exploring least-cost paths, accessibility and spatial relationships using real elevation models.',discover:'Discover ViaSpania',downloadsLink:'View downloads',scroll:'Scroll to travel across the terrain',
  programEye:'The software',programTitle:'From terrain to an observable hypothesis.',programText:['ViaSpania brings maps, digital elevation models and cost analysis together in a local workflow. Select an area, place the relevant elements, choose a movement profile and compare the outcome across synchronized maps and three-dimensional terrain.','It does not present a calculated route as historical truth. It turns it into an explicit, reproducible hypothesis that can be compared.'],stats:['movement profiles','analysis families','local workflow','comparable hypotheses'],
  functionsEye:'A territorial laboratory',functionsTitle:'One application, multiple scales of enquiry.',functionsIntro:'From a path between two points to a complete movement network, every calculation preserves its context, parameters and attributions.',functions:[['Least-cost paths','Calculates outward and return journeys separately and can produce 2–10 spatially distinct sub-optimal routes. Rank 1 is optimal and every ranked cost is evaluated on the original surface.'],['Profile comparison','Overlays models with identical endpoints and conditions to show how each route changes.'],['Multipoint','Builds a directed matrix of routes between up to eight points, revealing accessibility and asymmetry.'],['Multiroute','Links points in the selected order. Sub-optimal routes are complete 1→2→3… itineraries rather than unrelated combinations of legs.'],['Isochrones and surfaces','Delineates areas reachable from one or more origins and displays accumulated cost.'],['Least-cost corridors','Shows alternatives close to the optimum within a configurable percentage threshold.'],['Topographic analysis','Produces viewsheds and contour lines from elevation data without inventing vegetation or buildings.'],['3D terrain and results','Explore relief, routes and analyses with map textures, camera controls and visual exports.']],
  noveltyEye:'What sets it apart',noveltyTitle:'Landscape is not a neutral surface.',noveltyIntro:'ViaSpania builds richer scenarios than slope alone by incorporating cultural elements, graded constraints and crossing points.',novelty:[['Points of interest','Add significant places without forcing them to be an origin or destination.'],['Graded barriers','Represent absolute or permeable boundaries and control their crossing penalty.'],['Preferred corridors','Introduce axes that facilitate movement when supported by the archaeological hypothesis.'],['Crossings and bridges','Open specific passages across barriers instead of reducing them to all-or-nothing limits.'],['Sub-optimal routes','Temporarily penalise previously used cells to reveal spatially distinct options; they are not presented as exact k-shortest paths.'],['Multipoint','Compare complete directed networks rather than a single pair of places.'],['Multiroute','Study complete sequential itineraries and compare cost increase and overlap against the optimum.']],researchEye:'Spatial and landscape archaeology',quote:'Its strength is not producing one “correct” line, but exposing assumptions and showing how the outcome changes.',research:['Multipoint and multiroute modes support the study of connectivity, directionality, sequences and hierarchies between places. Sub-optimal routes extend that comparison: each new rank penalises previously used cells, while its published cost is measured again without that search penalty.','Familiar maps, visual comparison and 3D terrain also make the method easier to communicate to students and wider audiences. Results are interpretable, exportable and always presented with their limitations.'],
  profilesEye:'Movement profiles',profilesTitle:'Fifteen ways to question the terrain.',profilesIntro:'Profiles are not interchangeable: some estimate time, others energy or relative cost. Choose a model that fits the population, mode of travel and archaeological question.',directional:'Directional',symmetric:'Symmetric',profileLabels:['What it calculates','What you can adjust','Cautions','Key reference'],modelNote:'Every profile supports connectivity and landscape elements. ViaSpania displays units and prevents direct comparisons between seconds, joules and relative cost.',
  openEye:'Open source',openTitle:'Built on shared knowledge.',openIntro:'ViaSpania was developed entirely by combining open-source technologies. Every dependency retains its notices and every scientific model cites its source.',attribution:'Maps and data: © OpenStreetMap contributors (ODbL 1.0); Instituto Geográfico Nacional / Centro Nacional de Información Geográfica, under their reuse terms; Copernicus Land Monitoring Service / European Environment Agency. Acknowledged methodological basis: the R package movecost by Gianmarco Alberti.',
  authorEye:'About the author',authorText:'This space will soon present the education, career and research interests of ViaSpania’s creator.',bioSoon:'Biography in preparation',publications:'Publications',publicationsTitle:'Research and writing',publicationsText:'The author’s bibliography and publications will be added here in a future update.',catalogSoon:'Catalogue in preparation',
  downloadsEye:'Downloads',downloadsTitle:'ViaSpania on your desktop.',downloadsText:'Installable versions will appear here when they are ready for distribution. Calculations run on your computer and your projects remain under your control.',soon:'Coming soon',contact:'Contact',contactTitle:'A question, an idea\nor a case study?',licenses:'Licences',back:'Back to top ↑',summary:'Summary'
 }
} as const;

const englishModels:Record<ModelId,{family:string;description:string;purpose:string;editable:string;limits:string}>={
 tobler:{family:'Walking time',description:'Walking speed based on signed slope.',purpose:'Estimates walking time from slope, with maximum speed on a gentle descent of about 5%.',editable:'Connectivity, barriers and facilitators; the base speed is fixed.',limits:'A general walking function; it does not directly represent fatigue, weather, surface or individual ability.'},
 'tobler-off':{family:'Off-path walking',description:'Tobler speed reduced to 60%.',purpose:'Represents off-path movement with a uniform speed reduction.',editable:'Connectivity, barriers and facilitators; the 0.6 factor is fixed.',limits:'A single reduction factor cannot describe every land cover or surface.'},
 'marquez-perez':{family:'Natural trails',description:'Empirical fit for paths in natural areas.',purpose:'Estimates travel time using a slope response calibrated for natural trails.',editable:'Connectivity, barriers and facilitators.',limits:'Transferability depends on terrain and users resembling the calibration study.'},
 'kondo-seino':{family:'Walking time',description:'Treats descents steeper than 7% separately.',purpose:'Uses GPS-assisted walking experiments to distinguish steep downhill travel.',editable:'Connectivity, barriers and facilitators; coefficients are fixed.',limits:'An empirical model dependent on its experimental conditions.'},
 rees:{family:'Mountain terrain',description:'Travel speed for mountainous terrain.',purpose:'Penalises slope magnitude symmetrically.',editable:'Connectivity, barriers and facilitators.',limits:'It assigns the same cost to ascent and descent of equal steepness.'},
 gkrs:{family:'Walking time',description:'Exponential function of slope angle.',purpose:'Reduces a base speed exponentially as slope angle increases.',editable:'Connectivity, barriers and facilitators.',limits:'A symmetric model that does not distinguish direction of travel.'},
 tripcevich:{family:'Llama caravans',description:'Estimated speed for llama caravans.',purpose:'Models caravan movement rather than individual human walking.',editable:'Connectivity, barriers and facilitators.',limits:'Use only where llama-caravan movement is a reasonable interpretation.'},
 alberti:{family:'Pastoral movement',description:'Tobler rescaled to herd speed.',purpose:'Approximates herd movement at 25% of Tobler walking speed.',editable:'Connectivity, barriers and facilitators.',limits:'A fixed factor cannot represent every species, herd or pastoral condition.'},
 pandolf:{family:'Metabolic energy',description:'70 kg, no load, 1.2 m/s and configurable terrain.',purpose:'Estimates total energy expenditure for a person moving with a load.',editable:'Barriers and facilitators; mass, load and speed are currently fixed.',limits:'This variant does not distinguish ascent and descent and is not an individual diagnosis.'},
 'pandolf-corrected':{family:'Metabolic energy',description:'Applies the Yokota correction on downhill slopes.',purpose:'Adds a downhill correction to the Pandolf equation.',editable:'Connectivity, barriers and facilitators; mass, load and speed are fixed.',limits:'Interpret the correction within its published experimental domain.'},
 minetti:{family:'Metabolic energy',description:'Walking polynomial; recommended slope domain −0.5 to 0.5.',purpose:'Represents energy cost per kilogram using a slope polynomial.',editable:'Connectivity, barriers and facilitators.',limits:'The symmetric implementation does not distinguish ascent and descent.'},
 herzog:{family:'Metabolic energy',description:'Stable sixth-degree approximation related to Minetti.',purpose:'Provides a stable polynomial for archaeological optimal-path analysis.',editable:'Connectivity, barriers and facilitators.',limits:'A mathematical, symmetric approximation.'},
 ardigo:{family:'Walking, running or cycling',description:'Locomotion cost combining slope and speed.',purpose:'Models walking, running or cycling through slope and velocity.',editable:'Free speed or presets: walk 1.2, run 3.0, cycle 5.5 m/s; connectivity and landscape elements.',limits:'Uses absolute slope; presets are interface values, not personal calibrations.'},
 wheeled:{family:'Vehicle',description:'Critical slope controls quadratic cost growth; it is not a barrier.',purpose:'Produces relative vehicle cost above a reference slope.',editable:'Critical slope from 1% to 100%, connectivity and landscape elements.',limits:'It does not model a specific vehicle, grip or turning radius.'},
 eastman:{family:'Abstract cost',description:'Quadratic relative cost based on slope angle.',purpose:'Assigns an abstract slope-based cost for GIS analysis.',editable:'Connectivity, barriers and facilitators.',limits:'The index does not directly represent time or energy.'}
};
const englishModelNames:Record<ModelId,string>={tobler:'Tobler on-path','tobler-off':'Tobler off-path','marquez-perez':'Márquez-Pérez','kondo-seino':'Kondo–Seino',rees:'Rees',gkrs:'Garmy–Kaddouri–Rozenblat–Schneider',tripcevich:'Tripcevich',alberti:'Alberti pastoral',pandolf:'Pandolf','pandolf-corrected':'Pandolf with downhill correction',minetti:'Minetti',herzog:'Herzog',ardigo:'Ardigò',wheeled:'Vehicle with critical slope',eastman:'Eastman'};
const englishUnit=(unit:string)=>unit==='coste relativo'?'relative cost':unit;

const ids=['programa','funciones','perfiles','investigacion','autor','descargas'] as const;
function Mark(){return <a className="brand" href="#inicio"><span>VS</span><b>ViaSpania</b></a>}
function initialLanguage():Lang{return new URLSearchParams(location.search).get('lang')==='en'?'en':'es'}

export function Website(){
 const [menu,setMenu]=useState(false),[openModel,setOpenModel]=useState<ModelId>('tobler'),[lang,setLang]=useState<Lang>(initialLanguage);const t=copy[lang],english=lang==='en';
 useEffect(()=>{document.documentElement.lang=lang;document.title=english?'ViaSpania · Read the landscape':'ViaSpania · Leer el territorio';const url=new URL(location.href);if(english)url.searchParams.set('lang','en');else url.searchParams.delete('lang');history.replaceState(null,'',url)},[lang,english]);
 useEffect(()=>{const close=()=>setMenu(false);addEventListener('hashchange',close);return()=>removeEventListener('hashchange',close)},[]);
 const model=english?englishModels[openModel]:{family:MODELS[openModel].family,description:MODELS[openModel].description,purpose:MODEL_HELP[openModel].purpose,editable:MODEL_HELP[openModel].editable.join(' '),limits:MODEL_HELP[openModel].limits.join(' ')};
 return <div className="site-shell"><TerrainBackdrop/><header className="site-header"><Mark/><button className="menu" onClick={()=>setMenu(v=>!v)} aria-expanded={menu} aria-label={t.openMenu}>{t.menu}</button><nav className={menu?'open':''}>{t.nav.map((label,i)=><a key={ids[i]} href={`#${ids[i]}`}>{label}</a>)}<label className="language-picker"><span>{t.language}</span><select value={lang} onChange={e=>setLang(e.target.value as Lang)} aria-label={t.language}><option value="es">ES</option><option value="en">EN</option></select></label></nav></header>
 <main>
  <section className="hero" id="inicio"><div className="eyebrow"><i/>{t.heroEye}</div><h1>{t.heroA}<br/><em>{t.heroB}</em></h1><p>{t.heroText}</p><div className="hero-actions"><a className="primary" href="#programa">{t.discover}</a><a href="#descargas">{t.downloadsLink} <span>↓</span></a></div><div className="scroll-hint"><span>{t.scroll}</span><i/></div></section>
  <section className="manifest" id="programa"><div className="section-number">01</div><div><div className="eyebrow">{t.programEye}</div><h2>{t.programTitle}</h2></div><div className="lead">{t.programText.map(p=><p key={p}>{p}</p>)}</div></section>
  <section className="stats" aria-label={t.summary}>{['15','8','100%','∞'].map((value,i)=><div key={value}><b>{value}</b><span>{t.stats[i]}</span></div>)}</section>
  <section className="section" id="funciones"><header><div><span className="section-number">02</span><div className="eyebrow">{t.functionsEye}</div><h2>{t.functionsTitle}</h2></div><p>{t.functionsIntro}</p></header><div className="feature-grid">{t.functions.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section novelty" id="investigacion"><header><div><span className="section-number">03</span><div className="eyebrow">{t.noveltyEye}</div><h2>{t.noveltyTitle}</h2></div><p>{t.noveltyIntro}</p></header><div className="novelty-grid">{t.novelty.map(([title,text])=><article key={title}><i/><h3>{title}</h3><p>{text}</p></article>)}</div><aside className="research-note"><div className="eyebrow">{t.researchEye}</div><blockquote>{t.quote}</blockquote><div>{t.research.map(p=><p key={p}>{p}</p>)}</div></aside></section>
  <section className="profiles section" id="perfiles"><header><div><span className="section-number">04</span><div className="eyebrow">{t.profilesEye}</div><h2>{t.profilesTitle}</h2></div><p>{t.profilesIntro}</p></header><div className="profile-layout"><div className="profile-list" role="tablist">{modelIds.map(id=><button key={id} role="tab" aria-selected={openModel===id} onClick={()=>setOpenModel(id)}><span>{english?englishModelNames[id]:MODELS[id].name}</span><small>{english?englishModels[id].family:MODELS[id].family}</small></button>)}</div><article className="profile-detail"><div className="profile-meta"><span>{english?englishUnit(MODELS[openModel].unit):MODELS[openModel].unit}</span><span>{MODELS[openModel].directional?t.directional:t.symmetric}</span></div><h3>{english?englishModelNames[openModel]:MODELS[openModel].name}</h3><p className="profile-purpose">{model.purpose}</p><dl><div><dt>{t.profileLabels[0]}</dt><dd>{model.description}</dd></div><div><dt>{t.profileLabels[1]}</dt><dd>{model.editable}</dd></div><div><dt>{t.profileLabels[2]}</dt><dd>{model.limits}</dd></div><div><dt>{t.profileLabels[3]}</dt><dd>{MODEL_HELP[openModel].reference}</dd></div></dl></article></div><p className="model-note">{t.modelNote}</p></section>
  <section className="section open-source" id="codigo"><header><div><span className="section-number">05</span><div className="eyebrow">{t.openEye}</div><h2>{t.openTitle}</h2></div><p>{t.openIntro}</p></header><div className="license-grid">{software.map(([name,license])=><div key={name}><span>{name}</span><code>{license}</code></div>)}</div><p className="attribution">{t.attribution}</p></section>
  <section className="section author" id="autor"><span className="section-number">06</span><div><div className="eyebrow">{t.authorEye}</div><h2>Antonio López García</h2><p>{t.authorText}</p><div className="placeholder"><i/><span>{t.bioSoon}</span></div></div><div id="publicaciones"><div className="eyebrow">{t.publications}</div><h3>{t.publicationsTitle}</h3><p>{t.publicationsText}</p><div className="placeholder"><i/><span>{t.catalogSoon}</span></div></div></section>
  <section className="downloads section" id="descargas"><div><span className="section-number">07</span><div className="eyebrow">{t.downloadsEye}</div><h2>{t.downloadsTitle}</h2><p>{t.downloadsText}</p></div><div className="download-list">{[['macOS','Application · DMG','⌘'],['Windows','Installer · MSI / NSIS','⊞'],['Linux','AppImage · DEB / RPM','◇']].map(([os,format,icon])=><article key={os}><b>{icon}</b><div><h3>{os}</h3><p>{english?format:format.replace('Application','Aplicación').replace('Installer','Instalador')}</p></div><button disabled>{t.soon}</button></article>)}</div></section>
  <section className="contact section" id="contacto"><div className="eyebrow">{t.contact}</div><h2>{t.contactTitle.split('\n').map((line,i)=><span key={line}>{i>0&&<br/>}{line}</span>)}</h2><a href={CONTACT_HREF}>{CONTACT_EMAIL} <span>↗</span></a></section>
 </main><footer className="site-footer"><Mark/><p>ViaSpania<br/>Copyright © 2026 Antonio López García, Universidad de Granada<br/>Este programa se distribuye bajo la licencia GPL-3.0-only.</p><div><a href="#codigo">{t.licenses}</a><a href="#contacto">{t.contact}</a><a href="#inicio">{t.back}</a></div></footer></div>
}
