import {useEffect, useState} from 'react';
import {MODELS} from '../core/costModels';
import {MODEL_HELP} from '../core/calculationHelp';
import type {ModelId} from '../types';
import {TerrainBackdrop} from './TerrainBackdrop';

const modelIds=Object.keys(MODELS) as ModelId[];
const functions=[
  ['Rutas de menor coste','Calcula ida y vuelta por separado sobre elevación real, con perfiles direccionales y conectividad de 4, 8 o 16 vecinos.'],
  ['Comparación de perfiles','Superpone modelos manteniendo los mismos extremos y condiciones para estudiar cómo cambia cada trazado.'],
  ['Multipunto','Construye una matriz dirigida de rutas entre hasta ocho puntos; permite leer accesibilidad y asimetrías.'],
  ['Multirruta','Encadena los puntos en el orden elegido y conserva la geometría y el coste de cada tramo.'],
  ['Isócronas y superficies','Delimita áreas alcanzables desde uno o varios orígenes y visualiza el coste acumulado.'],
  ['Pasillos de menor coste','Muestra alternativas cercanas al óptimo dentro de un umbral porcentual configurable.'],
  ['Lectura topográfica','Genera visibilidad e isolíneas a partir del modelo de elevación, sin inventar vegetación ni edificios.'],
  ['Terreno 3D y resultados','Explora el relieve, las rutas y los análisis con textura cartográfica, cámara y exportación visual.'],
];
const novelty=[['Puntos de interés','Añade lugares significativos al proyecto sin obligarlos a ser origen o destino.'],['Barreras graduadas','Representa límites absolutos o permeables y ajusta cuánto penalizan el paso.'],['Corredores preferentes','Introduce ejes que facilitan el tránsito cuando la hipótesis arqueológica lo justifica.'],['Pasos y puentes','Abre cruces concretos sobre barreras, evitando simplificaciones de todo o nada.'],['Multipunto','Compara redes dirigidas completas, no solo una pareja de lugares.'],['Multirruta','Estudia itinerarios secuenciales y cada una de sus etapas dentro del mismo proyecto.']];
const software=[['React y React DOM','MIT'],['OpenLayers','BSD-2-Clause'],['Three.js','MIT'],['jsPDF','MIT'],['Tauri y Dialog','Apache-2.0 OR MIT'],['Vite','MIT'],['TypeScript','Apache-2.0'],['Vitest, Testing Library y jsdom','MIT'],['GDAL','MIT/X'],['PROJ','MIT'],['Rust y Cargo','Apache-2.0 OR MIT'],['Tokio','MIT'],['Reqwest','Apache-2.0 OR MIT'],['Serde y Serde JSON','Apache-2.0 OR MIT'],['Futures Util','Apache-2.0 OR MIT'],['URL, UUID, Base64 y Thiserror','MIT OR Apache-2.0']];

function Mark(){return <a className="brand" href="#inicio"><span>VS</span><b>ViaSpania</b></a>}
export function Website(){
 const [menu,setMenu]=useState(false);const [openModel,setOpenModel]=useState<ModelId>('tobler');
 useEffect(()=>{const close=()=>setMenu(false);addEventListener('hashchange',close);return()=>removeEventListener('hashchange',close)},[]);
 return <div className="site-shell"><TerrainBackdrop/><header className="site-header"><Mark/><button className="menu" onClick={()=>setMenu(v=>!v)} aria-expanded={menu} aria-label="Abrir navegación">Menú</button><nav className={menu?'open':''}><a href="#programa">El programa</a><a href="#funciones">Funciones</a><a href="#perfiles">Perfiles</a><a href="#investigacion">Investigación</a><a href="#autor">Autor</a><a href="#descargas">Descargas</a></nav></header>
 <main>
  <section className="hero" id="inicio"><div className="eyebrow"><i/> Análisis territorial · arqueología del paisaje</div><h1>Leer el territorio.<br/><em>Ensayar el movimiento.</em></h1><p>Una herramienta de escritorio para explorar caminos de menor coste, accesibilidad y relaciones espaciales sobre modelos reales de elevación.</p><div className="hero-actions"><a className="primary" href="#programa">Descubrir ViaSpania</a><a href="#descargas">Ver descargas <span>↓</span></a></div><div className="scroll-hint"><span>Desplázate para recorrer el relieve</span><i/></div></section>
  <section className="manifest" id="programa"><div className="section-number">01</div><div><div className="eyebrow">El programa</div><h2>Del relieve a una hipótesis que se puede observar.</h2></div><div className="lead"><p>ViaSpania reúne cartografía, modelos digitales de elevación y cálculo de coste en un flujo local. Seleccionas un área, sitúas los elementos relevantes, eliges un perfil de movimiento y comparas el resultado sobre mapas sincronizados y terreno tridimensional.</p><p>No presenta la ruta calculada como una verdad histórica. La convierte en una hipótesis explícita, reproducible y abierta a comparación.</p></div></section>
  <section className="stats" aria-label="Resumen"><div><b>15</b><span>perfiles de desplazamiento</span></div><div><b>8</b><span>familias de análisis</span></div><div><b>100%</b><span>flujo local</span></div><div><b>∞</b><span>hipótesis comparables</span></div></section>
  <section className="section" id="funciones"><header><div><span className="section-number">02</span><div className="eyebrow">Un laboratorio territorial</div><h2>Una aplicación, múltiples escalas de lectura.</h2></div><p>Desde el trayecto entre dos puntos hasta una red completa de desplazamientos, cada cálculo conserva su contexto, parámetros y atribuciones.</p></header><div className="feature-grid">{functions.map(([title,text],i)=><article key={title}><span>{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="section novelty" id="investigacion"><header><div><span className="section-number">03</span><div className="eyebrow">Lo diferencial</div><h2>El paisaje no es una superficie neutra.</h2></div><p>ViaSpania permite construir escenarios más ricos que una simple pendiente: incorpora elementos culturales, restricciones graduadas y lugares de paso.</p></header><div className="novelty-grid">{novelty.map(([title,text])=><article key={title}><i/><h3>{title}</h3><p>{text}</p></article>)}</div><aside className="research-note"><div className="eyebrow">Arqueología espacial y del paisaje</div><blockquote>La eficacia no está en producir una única línea «correcta», sino en hacer visibles los supuestos y comprobar cómo cambia el resultado.</blockquote><div><p>Los modos multipunto y multirruta permiten estudiar conectividad, direccionalidad, secuencias y jerarquías entre lugares. Barreras, pasos y corredores ayudan a ensayar hipótesis sobre cómo las decisiones sociales transforman la accesibilidad del relieve.</p><p>La combinación de mapas familiares, comparación visual y terreno 3D también facilita explicar el método a estudiantes y público no especializado. Los resultados son interpretables, exportables y siempre se acompañan de sus límites.</p></div></aside></section>
  <section className="profiles section" id="perfiles"><header><div><span className="section-number">04</span><div className="eyebrow">Perfiles de desplazamiento</div><h2>Quince maneras de preguntar al terreno.</h2></div><p>Los perfiles no son intercambiables: unos estiman tiempo, otros energía o coste relativo. Elige un modelo según la población, el modo de transporte y la pregunta arqueológica.</p></header><div className="profile-layout"><div className="profile-list" role="tablist">{modelIds.map(id=><button key={id} role="tab" aria-selected={openModel===id} onClick={()=>setOpenModel(id)}><span>{MODELS[id].name}</span><small>{MODELS[id].family}</small></button>)}</div><article className="profile-detail"><div className="profile-meta"><span>{MODELS[openModel].unit}</span><span>{MODELS[openModel].directional?'Direccional':'Simétrico'}</span></div><h3>{MODELS[openModel].name}</h3><p className="profile-purpose">{MODEL_HELP[openModel].purpose}</p><dl><div><dt>Qué calcula</dt><dd>{MODELS[openModel].description}</dd></div><div><dt>Qué puedes ajustar</dt><dd>{MODEL_HELP[openModel].editable.join(' ')}</dd></div><div><dt>Precauciones</dt><dd>{MODEL_HELP[openModel].limits.join(' ')}</dd></div><div><dt>Bibliografía básica</dt><dd>{MODEL_HELP[openModel].reference}</dd></div></dl></article></div><p className="model-note">Todos los perfiles admiten conectividad y elementos del paisaje. ViaSpania muestra las unidades y evita comparar directamente segundos, julios y coste relativo.</p></section>
  <section className="section open-source" id="codigo"><header><div><span className="section-number">05</span><div className="eyebrow">Código abierto</div><h2>Construido sobre conocimiento compartido.</h2></div><p>ViaSpania ha sido programado íntegramente combinando tecnologías de código abierto. Cada dependencia conserva sus avisos y cada modelo científico cita su fuente.</p></header><div className="license-grid">{software.map(([name,license])=><div key={name}><span>{name}</span><code>{license}</code></div>)}</div><p className="attribution">Cartografía y datos: © colaboradores de OpenStreetMap (ODbL 1.0); Instituto Geográfico Nacional / Centro Nacional de Información Geográfica, según sus condiciones de reutilización; Copernicus Land Monitoring Service / Agencia Europea de Medio Ambiente. Base metodológica reconocida: paquete R <i>movecost</i>, de Gianmarco Alberti.</p></section>
  <section className="section author" id="autor"><span className="section-number">06</span><div><div className="eyebrow">Sobre el autor</div><h2>Antonio López García</h2><p>Este espacio recogerá próximamente la formación, trayectoria e intereses de investigación del creador de ViaSpania.</p><div className="placeholder"><i/><span>Biografía en preparación</span></div></div><div id="publicaciones"><div className="eyebrow">Publicaciones</div><h3>Investigación y textos</h3><p>La bibliografía personal y las publicaciones se incorporarán aquí en una próxima actualización.</p><div className="placeholder"><i/><span>Catálogo en preparación</span></div></div></section>
  <section className="downloads section" id="descargas"><div><span className="section-number">07</span><div className="eyebrow">Descargas</div><h2>ViaSpania en tu escritorio.</h2><p>Las versiones instalables aparecerán aquí cuando estén preparadas para distribución. El cálculo se ejecuta en tu equipo y los proyectos permanecen bajo tu control.</p></div><div className="download-list">{[['macOS','Aplicación · DMG','⌘'],['Windows','Instalador · MSI / NSIS','⊞'],['Linux','AppImage · DEB / RPM','◇']].map(([os,format,icon])=><article key={os}><b>{icon}</b><div><h3>{os}</h3><p>{format}</p></div><button disabled>Próximamente</button></article>)}</div></section>
  <section className="contact section" id="contacto"><div className="eyebrow">Contacto</div><h2>¿Una pregunta, una idea<br/>o un caso de estudio?</h2><a href="mailto:antonio-lopez-garcia@hotmail.com">antonio-lopez-garcia@hotmail.com <span>↗</span></a></section>
 </main><footer className="site-footer"><Mark/><p>© 2026 Antonio López García</p><div><a href="#codigo">Licencias</a><a href="#contacto">Contacto</a><a href="#inicio">Volver arriba ↑</a></div></footer></div>
}
