import type {CalculationHelpMode} from './calculationHelp';
import type {ModelId} from '../types';
export const CALCULATION_MODE_HELP_EN:Record<CalculationHelpMode,{name:string;summary:string;process:string[];parameters:string[]}>= {
 ruta:{name:'Simple route',summary:'Finds the minimum accumulated-cost path and optional sub-optimal routes. Return is calculated separately because several profiles depend on slope direction.',process:['Turns every valid elevation-model cell into a grid node and runs Dijkstra.','For sub-optimal routes, penalises edges incident to previously used cells and repeats the search; these are spatial alternatives, not exact k-shortest paths.','Every ranked cost is evaluated again on the original, unpenalised surface. Waypoints remain mandatory in every complete itinerary.'],parameters:['Travel profile','Connectivity of 4, 8 or 16 neighbours','Barriers, corridors, enabled crossings and points of interest','Number of routes and separation strength']},
 comparar:{name:'Route comparison',summary:'Repeats the same route with several profiles to compare geometry, cost and slope sensitivity.',process:['Keeps endpoints, elevation, connectivity and facilitators identical.','Runs every selected profile independently.','Costs with different units—seconds, joules or relative cost—must not be compared numerically.'],parameters:['Included profiles','Connectivity','Critical slope for Wheeled','Speed for Ardigò']},
 multipunto:{name:'Multipoint',summary:'Calculates a directed least-cost matrix among the first eight points.',process:['Each point acts as origin in turn.','An independent route is calculated to every destination.','Matrices can be asymmetric with directional profiles.'],parameters:['Profile','Point order and position','Connectivity and facilitators']},
 multirruta:{name:'Multi-route',summary:'Chains consecutive routes in list order and can create complete sub-optimal itineraries.',process:['Solves every leg as a least-cost route.','Joins all legs into one itinerary per rank, then penalises cells used by that complete itinerary.','Ranks never mix unrelated leg alternatives and do not optimise visit order.','Costs are evaluated on the original surface and compared with rank 1.'],parameters:['Profile','Point order','Connectivity and facilitators','Number of itineraries and separation strength']},
 isocronas:{name:'Isochrones',summary:'Calculates minimum accumulated cost from one or more origins and extracts equal-cost lines.',process:['Starts Dijkstra simultaneously from the selected origins.','Builds an accumulated-cost surface.','Interpolates crossings at every requested level to form isolines.'],parameters:['Origin or origins','Interval and maximum levels','Profile, connectivity and facilitators','Surface display and opacity']},
 pasillos:{name:'Least-cost corridor',summary:'Delimits alternatives close to the optimal path between start and end.',process:['Calculates accumulated cost from both endpoints.','Combines origin→cell and cell→destination while respecting direction.','Includes cells within the selected percentage above optimum.'],parameters:['Percentage threshold','Profile and connectivity','Display opacity']},
 viewshed:{name:'Viewshed',summary:'Estimates which cells retain topographic line of sight from the observers.',process:['Compares each cell’s vertical angle with the maximum horizon in its direction.','Uses only the loaded model elevation.','Does not include vegetation, buildings or atmospheric refraction.'],parameters:['Observer points','Observer height','Model resolution and extent']},
 contours:{name:'Contour lines',summary:'Extracts lines joining equal elevations by interpolation across the grid.',process:['Traverses digital-model cells.','Interpolates where each elevation crosses cell edges.','Groups resulting segments by level.'],parameters:['Vertical interval in metres','Digital-model resolution and quality']},
};
type MT={author:string;purpose:string;variables:string[];editable:string[];limits:string[]};
export const MODEL_HELP_EN:Record<ModelId,MT>={
 tobler:{author:'Waldo R. Tobler (1930–2018), geographer and cartographer associated with quantitative geography.',purpose:'Estimates walking time from slope; maximum speed occurs on a gentle descent of about 5%.',variables:['s: signed slope = elevation difference / horizontal distance.','Three-dimensional step distance in metres.','Terrain, barrier and facilitator multipliers.'],editable:['Base speed is fixed at 6 km/h.','Connectivity, barriers and facilitators can be changed.'],limits:['A general function, not an individual measurement.','Does not directly include fatigue, weather, surface or physical ability.']},
 'tobler-off':{author:'Adaptation of Waldo R. Tobler’s walking function.',purpose:'Represents off-path walking by reducing Tobler speed to 60%.',variables:['Signed slope and step distance.','Fixed off-path factor 0.6.'],editable:['The factor is fixed.','Connectivity, barriers and facilitators are configurable.'],limits:['A uniform reduction cannot describe every land cover or surface.']},
 'marquez-perez':{author:'J. Márquez-Pérez and colleagues proposed an empirical fit for natural-area trails.',purpose:'Estimates travel time with a slope response calibrated for natural trails.',variables:['Signed slope, distance and terrain multiplier.'],editable:['Connectivity, barriers and facilitators.','Empirical coefficients are fixed.'],limits:['Transferability depends on similarity to the calibration terrain and population.']},
 'kondo-seino':{author:'Y. Kondo and Y. Seino developed this model from GPS-assisted walking experiments.',purpose:'Treats steep descents separately below a −7% slope.',variables:['Signed slope and fixed −7% threshold.'],editable:['Connectivity, barriers and facilitators.','Threshold and coefficients are fixed.'],limits:['Empirical and dependent on experimental conditions.']},
 rees:{author:'W. G. Rees formulated this function for mountainous least-cost paths.',purpose:'Penalises slope magnitude symmetrically.',variables:['Slope magnitude and distance.'],editable:['Connectivity, barriers and facilitators.'],limits:['Does not distinguish ascent from descent.']},
 gkrs:{author:'Attributed to Garmy, Kaddouri, Rozenblat and Schneider; later reviewed by Irmela Herzog.',purpose:'Reduces base speed exponentially as slope angle increases.',variables:['Absolute slope angle and distance.'],editable:['Connectivity, barriers and facilitators.'],limits:['Symmetric; does not distinguish direction.']},
 tripcevich:{author:'Nicholas Tripcevich studied llama-caravan speeds for Andean archaeology.',purpose:'Estimates caravan movement, not individual human walking.',variables:['Absolute slope angle in degrees.'],editable:['Connectivity, barriers and facilitators.'],limits:['Use only when llama caravans are an appropriate representation.']},
 alberti:{author:'Gianmarco Alberti proposed this adaptation for pastoral routes in Malta.',purpose:'Approximates herd movement by scaling Tobler speed to 25%.',variables:['Signed slope and fixed pastoral factor 0.25.'],editable:['Connectivity, barriers and facilitators.'],limits:['A fixed factor cannot represent every species, herd or condition.']},
 pandolf:{author:'Kent B. Pandolf, Baruch Givoni and Ralph F. Goldman developed this loaded-walking metabolic equation.',purpose:'Estimates total energy using the fixed mass and speed assumptions.',variables:['W = 70 kg; L = 0 kg; V = 1.2 m/s.','N: terrain multiplier; |s|: absolute slope.'],editable:['Mass, load and speed are fixed.','Barriers and facilitators modify spatial cost.'],limits:['Does not distinguish ascent and descent.','Not an individual physiological diagnosis.']},
 'pandolf-corrected':{author:'Pandolf’s equation combined with the descent correction evaluated by Yokota and colleagues.',purpose:'Applies a correction on negative slopes so ascent and descent expenditure differ.',variables:['Mass 70 kg, load 0 kg, speed 1.2 m/s, terrain and signed slope.'],editable:['Mass, load and speed are fixed.','Connectivity, barriers and facilitators are configurable.'],limits:['Interpret only within the published experimental domain.']},
 minetti:{author:'Alberto E. Minetti and colleagues measured locomotion cost on extreme slopes.',purpose:'Represents mass-specific energy cost with a slope polynomial.',variables:['Slope magnitude, distance and terrain multiplier.'],editable:['Connectivity, barriers and facilitators.'],limits:['Recommended domain: −0.5 ≤ s ≤ 0.5.','The implementation is symmetric.']},
 herzog:{author:'Irmela Herzog proposed stable approximations for archaeological optimal-path analysis.',purpose:'Uses a sixth-degree polynomial related to Minetti.',variables:['Absolute slope, distance and terrain.'],editable:['Connectivity, barriers and facilitators.'],limits:['A mathematical, symmetric approximation.']},
 ardigo:{author:'Luca P. Ardigò, Francesco Saibene and Alberto E. Minetti analysed human locomotion cost.',purpose:'Models walking, running or cycling using slope and speed.',variables:['Absolute slope.','Speed from 0.2 to 15 m/s.'],editable:['Free speed or walking, running and cycling presets.','Connectivity, barriers and facilitators.'],limits:['Uses absolute slope symmetrically.','Presets are not personal calibrations.']},
 wheeled:{author:'Vehicle function documented by Irmela Herzog in optimal-path literature.',purpose:'Produces relative cost that grows quadratically beyond a reference slope.',variables:['Absolute slope, distance and critical slope.'],editable:['Critical slope from 1% to 100%.','Connectivity, barriers and facilitators.'],limits:['Critical slope raises cost; it does not block a cell.','Does not model a specific vehicle, traction or turning radius.']},
 eastman:{author:'J. Ronald Eastman developed GIS multi-criteria and cost formulations.',purpose:'Assigns quadratic relative cost from slope angle.',variables:['Absolute slope angle, distance and terrain.'],editable:['Connectivity, barriers and facilitators.'],limits:['An abstract index, not direct time or energy.']},
};
