import {MODELS} from './costModels';
import type {ModelId} from '../types';

export type CalculationHelpMode='ruta'|'comparar'|'multipunto'|'multirruta'|'isocronas'|'pasillos'|'viewshed'|'contours';

export const CALCULATION_MODE_HELP:Record<CalculationHelpMode,{name:string;summary:string;process:string[];parameters:string[]}>= {
  ruta:{name:'Ruta simple',summary:'Busca el trayecto de coste acumulado mínimo entre Punto 1 y Punto 2 y, opcionalmente, rutas subóptimas espacialmente diferenciadas. La vuelta se calcula por separado porque varios perfiles dependen del sentido de la pendiente.',process:['Convierte cada celda válida del modelo de elevación en un nodo de una rejilla.','Aplica Dijkstra y reconstruye la secuencia de celdas con menor coste total.','Si se solicitan rutas subóptimas, penaliza las aristas incidentes a celdas ya utilizadas y repite Dijkstra. No son los k caminos mínimos exactos: se buscan opciones espacialmente distintas.','El coste de cada rango se vuelve a evaluar sobre la superficie original, sin la penalización de búsqueda. Los waypoint forman un itinerario completo en cada rango.'],parameters:['Perfil de desplazamiento','Conectividad de 4, 8 o 16 vecinos','Barreras, corredores, pasos habilitados y puntos de interés','Número de rutas (2–10) y separación baja, media o alta']},
  comparar:{name:'Ruta comparativa',summary:'Repite la misma ruta con varios perfiles para comparar geometría, coste y sensibilidad a la pendiente.',process:['Mantiene idénticos extremos, elevación, conectividad y facilitadores.','Ejecuta independientemente cada perfil seleccionado.','No deben compararse numéricamente costes con unidades diferentes como segundos, julios y coste relativo.'],parameters:['Perfiles incluidos en la comparación','Conectividad','Pendiente crítica si se incluye Vehículo','Velocidad si se incluye Ardigò']},
  multipunto:{name:'Matriz de conexiones',summary:'Calcula una matriz dirigida de menor coste entre todos los puntos de la lista.',process:['Cada punto actúa sucesivamente como origen.','Se calcula una ruta independiente hacia cada destino.','Las matrices pueden ser asimétricas con perfiles direccionales.'],parameters:['Perfil','Orden y posición de los puntos','Conectividad y facilitadores']},
  multirruta:{name:'Ruta secuencial',summary:'Encadena rutas consecutivas según el orden de la lista y puede generar itinerarios completos subóptimos.',process:['Use Crear punto y Subir/Bajar en la lista. Resuelve cada pareja consecutiva como una ruta de coste mínimo.','Para cada rango une todos los tramos 1→2→3… y después penaliza las celdas de todo ese itinerario antes del rango siguiente.','Los rangos no mezclan alternativas parciales y no optimizan el orden de visita.','Coste, incremento y solapamiento se calculan respecto al rango 1 sobre la superficie original.'],parameters:['Perfil','Orden de puntos','Conectividad y facilitadores','Número de itinerarios y grado de separación']},
  isocronas:{name:'Isócronas',summary:'Calcula el menor coste acumulado desde uno o varios orígenes y extrae líneas de igual coste.',process:['Inicia Dijkstra simultáneamente desde los orígenes elegidos.','Obtiene una superficie de coste acumulado.','Interpola los cruces de cada nivel solicitado para formar las isolíneas.'],parameters:['Origen u orígenes','Intervalo y número máximo de niveles','Perfil, conectividad y facilitadores','Visualización y opacidad de la superficie']},
  pasillos:{name:'Pasillo de menor coste',summary:'Delimita alternativas próximas al trayecto óptimo entre Punto 1 y Punto 2.',process:['Calcula costes acumulados desde ambos extremos.','Para cada celda combina origen→celda y celda→destino respetando la dirección.','Incluye las celdas cuyo coste no supera el óptimo más el porcentaje elegido.'],parameters:['Umbral porcentual sobre el óptimo','Perfil y conectividad','Opacidad de representación']},
  viewshed:{name:'Visibilidad',summary:'Estima qué celdas del modelo mantienen línea de visión topográfica desde los observadores.',process:['Compara el ángulo vertical de cada celda con el horizonte máximo encontrado en su dirección.','Usa exclusivamente la elevación del modelo cargado.','No incorpora vegetación, edificios ni refracción atmosférica.'],parameters:['Puntos observadores','Altura del observador','Resolución y extensión del modelo']},
  contours:{name:'Curvas de nivel',summary:'Extrae líneas que unen posiciones con la misma elevación mediante interpolación sobre la rejilla.',process:['Recorre las celdas del modelo digital.','Interpola dónde cruza cada cota los lados de una celda.','Agrupa los segmentos obtenidos por nivel.'],parameters:['Equidistancia vertical en metros','Resolución y calidad del modelo digital']},
};

type ModelHelp={author:string;purpose:string;formula:string;variables:string[];editable:string[];limits:string[];reference:string};
const common=(id:ModelId,help:ModelHelp)=>({...help,name:MODELS[id].name,family:MODELS[id].family,unit:MODELS[id].unit,directional:MODELS[id].directional});

export const MODEL_HELP:Record<ModelId,ReturnType<typeof common>>={
  tobler:common('tobler',{author:'Waldo R. Tobler (1930–2018), geógrafo y cartógrafo asociado al desarrollo de la geografía cuantitativa.',purpose:'Estima tiempo de marcha a partir de la pendiente. La máxima velocidad aparece en un descenso suave, alrededor del 5 %.',formula:'v = 6 · exp(−3,5 · |s + 0,05|) km/h; tiempo = distancia sobre la superficie / v.',variables:['s: pendiente firmada = desnivel (m) / distancia horizontal (m).','Distancia tridimensional del paso, en metros.','Multiplicadores de terreno, barreras y facilitadores.'],editable:['No se modifica la velocidad base de 6 km/h en esta versión.','Sí pueden cambiarse conectividad, barreras y facilitadores.'],limits:['Es una función general de marcha, no una medición individual.','No incorpora fatiga, clima, firme ni capacidad física salvo mediante capas de coste.'],reference:'Tobler, W. (1993), Three Presentations on Geographical Analysis and Modeling, NCGIA 93-1.'}),
  'tobler-off':common('tobler-off',{author:'Adaptación de la función de marcha de Waldo R. Tobler.',purpose:'Representa marcha campo a través reduciendo al 60 % la velocidad de Tobler.',formula:'v = 0,6 · 6 · exp(−3,5 · |s + 0,05|) km/h.',variables:['Pendiente firmada y distancia del paso.','Reducción fija campo a través de 0,6.'],editable:['La reducción 0,6 no es configurable actualmente.','Conectividad, barreras y facilitadores sí lo son.'],limits:['La reducción uniforme no describe toda la diversidad de cubiertas o firmes.'],reference:'Tobler (1993), NCGIA 93-1.'}),
  'marquez-perez':common('marquez-perez',{author:'J. Márquez-Pérez y colaboradores propusieron un ajuste empírico orientado a senderos en espacios naturales.',purpose:'Estima tiempo de recorrido con una respuesta a la pendiente calibrada para senderos naturales.',formula:'v = 4,8 · exp(−5,3 · |0,7s + 0,03|) km/h.',variables:['Pendiente firmada, distancia y multiplicador del terreno.'],editable:['Conectividad, barreras y facilitadores.','Los coeficientes empíricos no son configurables.'],limits:['Su transferibilidad depende de que el terreno y población se parezcan a los del estudio de calibración.'],reference:'Márquez-Pérez et al. (2017), Estimated travel time for walking trails in natural areas, DOI 10.1080/00167223.2017.1316212.'}),
  'kondo-seino':common('kondo-seino',{author:'Y. Kondo e Y. Seino desarrollaron un modelo basado en experimentos de marcha asistidos por GPS.',purpose:'Distingue los descensos pronunciados, cambiando la respuesta cuando la pendiente baja del −7 %.',formula:'v = 5,1 · exp(k · |s + 0,07|) km/h; k = −2,25 si s ≥ −0,07 y −1,5 en descenso más fuerte.',variables:['Pendiente firmada y umbral fijo de −7 %.'],editable:['Conectividad, barreras y facilitadores.','El umbral y coeficientes no se editan.'],limits:['Modelo empírico dependiente de las condiciones experimentales.'],reference:'Kondo & Seino (2010), GPS-aided Walking Experiments and Data-driven Travel Cost Modeling.'}),
  rees:common('rees',{author:'W. G. Rees formuló una función para rutas de menor coste en terreno montañoso.',purpose:'Penaliza simétricamente la magnitud de la pendiente; subir y bajar la misma inclinación tienen igual coste.',formula:'v = 3,6 / (0,75 + 0,09|s| + 14,6|s|²) km/h.',variables:['Magnitud de la pendiente y distancia.'],editable:['Conectividad, barreras y facilitadores.'],limits:['No diferencia ascenso y descenso.'],reference:'Rees, W. G. (2004), Least-cost paths in mountainous terrain, Computers & Geosciences 30(3), 203–209.'}),
  gkrs:common('gkrs',{author:'Modelo atribuido a Garmy, Kaddouri, Rozenblat y Schneider; revisado posteriormente por Irmela Herzog.',purpose:'Reduce exponencialmente una velocidad base conforme aumenta el ángulo de pendiente.',formula:'v = 4 · exp(−0,008 · a²) km/h; a = arctan(|s|) en grados.',variables:['Ángulo absoluto de pendiente y distancia.'],editable:['Conectividad, barreras y facilitadores.'],limits:['Es simétrico y no distingue el sentido de marcha.'],reference:'Garmy et al.; formulación documentada por Herzog (2020).'}),
  tripcevich:common('tripcevich',{author:'Nicholas Tripcevich estudió velocidades de caravanas de llamas para análisis arqueológico andino.',purpose:'Estima desplazamiento de caravanas, no marcha humana individual.',formula:'v = (4,028 · 46²) / ((a + 4,127)² + 46²) km/h.',variables:['Ángulo absoluto de pendiente a, en grados.'],editable:['Conectividad, barreras y facilitadores.'],limits:['Debe utilizarse solo cuando sea razonable representar caravanas de llamas.'],reference:'Tripcevich, N. (2008), Estimating Llama Caravan Travel Speeds.'}),
  alberti:common('alberti',{author:'Gianmarco Alberti propuso esta adaptación en un estudio de rutas pastorales de Malta.',purpose:'Aproxima el desplazamiento de rebaños reescalando la velocidad de Tobler al 25 %.',formula:'v = 0,25 · 6 · exp(−3,5 · |s + 0,05|) km/h.',variables:['Pendiente firmada y factor pastoral fijo 0,25.'],editable:['Conectividad, barreras y facilitadores.'],limits:['El factor fijo no representa todas las especies, rebaños o condiciones pastorales.'],reference:'Alberti, G. (2019), Locating potential pastoral foraging routes in Malta, SoftwareX 10, 100331.'}),
  pandolf:common('pandolf',{author:'Kent B. Pandolf, Baruch Givoni y Ralph F. Goldman desarrollaron una ecuación de gasto metabólico para desplazamiento con carga.',purpose:'Estima energía total para una persona de masa y velocidad fijadas por la implementación.',formula:'M = 1,5W + 2(W+L)(L/W)² + N(W+L)(1,5V² + 0,35V·100|s|) W; energía = M · distancia/V.',variables:['W = 70 kg; L = 0 kg; V = 1,2 m/s.','N: multiplicador de terreno; |s|: pendiente absoluta.'],editable:['Actualmente masa, carga y velocidad están fijadas.','Barreras y facilitadores modifican el coste espacial.'],limits:['No diferencia ascenso y descenso en esta variante.','No debe interpretarse como diagnóstico fisiológico individual.'],reference:'Pandolf, Givoni & Goldman (1977), Journal of Applied Physiology 43(4), 577–581, DOI 10.1152/jappl.1977.43.4.577.'}),
  'pandolf-corrected':common('pandolf-corrected',{author:'Combina la ecuación de Pandolf, Givoni y Goldman con una corrección para descenso evaluada por Yokota y colaboradores.',purpose:'Evita que descenso y ascenso tengan idéntico gasto, aplicando la corrección únicamente en pendientes negativas.',formula:'Parte de Pandolf y, si s < 0, resta el factor corrector de Yokota; el coste se limita a un valor positivo.',variables:['Masa 70 kg, carga 0 kg, velocidad 1,2 m/s, terreno y pendiente firmada.'],editable:['Masa, carga y velocidad aún no son configurables.','Conectividad, barreras y facilitadores sí.'],limits:['La corrección debe entenderse dentro del dominio experimental publicado.'],reference:'Pandolf et al. (1977); Yokota et al. (2004), USARIEM Technical Report T04-09.'}),
  minetti:common('minetti',{author:'Alberto E. Minetti y colaboradores midieron el coste energético de caminar y correr en pendientes extremas.',purpose:'Representa coste energético específico por kilogramo mediante un polinomio de la pendiente.',formula:'C = 280,5x⁵ − 58,7x⁴ − 76,8x³ + 51,9x² + 19,6x + 2,5 J/(kg·m), con x = |s|.',variables:['Magnitud de pendiente, distancia y multiplicador del terreno.'],editable:['Conectividad, barreras y facilitadores.'],limits:['ViaSpania recomienda −0,5 ≤ s ≤ 0,5.','La implementación simétrica no diferencia subida y bajada.'],reference:'Minetti et al. (2002), Energy cost of walking and running at extreme uphill and downhill slopes, Journal of Applied Physiology 93, 1039–1046.'}),
  herzog:common('herzog',{author:'Irmela Herzog propuso aproximaciones estables para análisis arqueológico de caminos óptimos.',purpose:'Usa un polinomio de sexto grado relacionado con la función de Minetti.',formula:'C = 1337,8x⁶ + 278,19x⁵ − 517,39x⁴ − 78,199x³ + 93,419x² + 19,825x + 1,64 J/(kg·m).',variables:['x = |pendiente|, distancia y terreno.'],editable:['Conectividad, barreras y facilitadores.'],limits:['Es una aproximación matemática y simétrica.'],reference:'Herzog, I. (2016), Potential and Limits of Optimal Path Analysis.'}),
  ardigo:common('ardigo',{author:'Luca P. Ardigò, Francesco Saibene y Alberto E. Minetti analizaron el coste energético de locomoción humana.',purpose:'Modela caminar, correr o bicicleta combinando pendiente y velocidad.',formula:'C = 1,866e^(4,911x)V² − 3,773e^(3,416x)V + 45,71x² + 18,9x + 4,456 J/(kg·m).',variables:['x = |pendiente|.','V: velocidad en m/s, entre 0,2 y 15 en ViaSpania.'],editable:['Velocidad libre o preajustes: caminar 1,2; correr 3,0; bicicleta 5,5 m/s.','Conectividad, barreras y facilitadores.'],limits:['La fórmula se aplica simétricamente a la pendiente absoluta.','Los preajustes son valores de interfaz, no calibraciones personales.'],reference:'Ardigò, Saibene & Minetti (2003), European Journal of Applied Physiology 90, 365–371.'}),
  wheeled:common('wheeled',{author:'Función de vehículo documentada en la literatura de análisis de caminos óptimos por Irmela Herzog.',purpose:'Produce un coste relativo que crece cuadráticamente al superar una pendiente de referencia.',formula:'C = distancia · (1 + (100|s|/p)²) · terreno; p es la pendiente crítica en %.',variables:['Pendiente absoluta, distancia y pendiente crítica.'],editable:['Pendiente crítica entre 1 % y 100 %.','Conectividad, barreras y facilitadores.'],limits:['La pendiente crítica no bloquea la celda: solo eleva su coste.','No modela un vehículo concreto, adherencia ni radio de giro.'],reference:'Herzog, I. (2016), Potential and Limits of Optimal Path Analysis.'}),
  eastman:common('eastman',{author:'J. Ronald Eastman desarrolló herramientas y formulaciones de evaluación multicriterio y coste en SIG.',purpose:'Asigna un coste relativo cuadrático basado en el ángulo de pendiente.',formula:'C = distancia · (0,031a² − 0,025a + 1) · terreno; a = arctan(|s|) en grados.',variables:['Ángulo absoluto de pendiente, distancia y terreno.'],editable:['Conectividad, barreras y facilitadores.'],limits:['Es un índice abstracto: no representa directamente tiempo ni energía.'],reference:'Eastman (1999); formulación documentada por Vaissié (2021).'}),
  'irmischer-clarke':common('irmischer-clarke',{author:'Ian J. Irmischer y Keith C. Clarke desarrollaron estas funciones a partir del estudio empírico de la velocidad de navegación humana a pie.',purpose:'Estima la velocidad de desplazamiento peatonal según la magnitud de la pendiente, con variantes de sexo/modelo y contexto.',formula:'p=100|s|. Masculino/caminos: v=(0,11+exp(−(p+5)²/(2·30²)))·3,6 km/h. Masculino/campo a través: v=(0,11+0,67exp(−(p+2)²/(2·30²)))·3,6. Las variantes femeninas multiplican la velocidad por 0,95. El tiempo usa la distancia del paso y la velocidad calculada.',variables:['s: pendiente firmada; p: valor absoluto en porcentaje.','Masculino/femenino y caminos/campo a través.','Distancia del paso y multiplicadores generales (aplicados una vez).'],editable:['Modelo masculino o femenino; por caminos o campo a través.','Conectividad, barreras y facilitadores.'],limits:['Simétrico: no distingue ascensos y descensos de igual magnitud.','Las variantes de sexo corresponden a la muestra original, no a constantes universales.','No incorpora fatiga, edad, clima o capacidad física individual.'],reference:'Irmischer, I. J. & Clarke, K. C. (2018), “Measuring and modeling the speed of human navigation”, Cartography and Geographic Information Science 45(2), 177–186. https://doi.org/10.1080/15230406.2017.1292150'}),
  'uriarte-gonzalez':common('uriarte-gonzalez',{author:'La función se asocia al trabajo de Teresa Chapa Brunet, Juan Manuel Vicent García, Victorino Mayoral Herrera y Antonio Uriarte González sobre modelos SIG de paisaje y poblamiento preindustrial mediterráneo.',purpose:'Estima el coste temporal peatonal a partir de la magnitud de la pendiente.',formula:'p=100|s|. tₘ=(0,0277·p+0,6115) s/m. MoveCost expresa esta relación mediante su recíproco; ViaSpania calcula el coste temporal directamente con el multiplicador general aplicado una vez.',variables:['s: pendiente firmada; p: magnitud absoluta en porcentaje.','Distancia del paso y multiplicadores generales.'],editable:['Conectividad, barreras, facilitadores y demás parámetros generales.'],limits:['Simétrico; trata por igual ascensos y descensos.','Es una aproximación y no una predicción individual exacta.'],reference:'Chapa Brunet, T., Vicent García, J. M., Mayoral Herrera, V. & Uriarte González, A. (2008), “GIS landscape models for the study of preindustrial settlement patterns in Mediterranean areas”, Geoinformation Technologies for Geo-Cultural Landscapes, pp. 255–273. https://doi.org/10.1201/9780203881613.ch12'}),
  'marin-arroyo':common('marin-arroyo',{author:'Ana B. Marín-Arroyo utilizó esta función en el análisis de áreas de captación y movilidad durante el Tardiglacial en Cantabria oriental, mediante Optimal Foraging Theory.',purpose:'Estima el coste temporal peatonal diferenciando subida y bajada.',formula:'p=100|s|. Descenso (s<0): tₘ=0,6·(p/23+1) s/m. Llano o ascenso (s≥0): tₘ=0,6·(p/11+1) s/m. MoveCost utiliza los recíprocos como conductancia; ViaSpania adapta las expresiones al coste temporal y aplica el multiplicador general una vez.',variables:['s: pendiente firmada; p: magnitud en porcentaje.','Dirección del desplazamiento y distancia del paso.','Multiplicadores generales.'],editable:['Conectividad, barreras, facilitadores y parámetros generales.'],limits:['Función general derivada de un contexto arqueológico específico.','No incorpora carga, fatiga, clima, edad o condición física.'],reference:'Marín-Arroyo, A. B. (2009), “The use of optimal foraging theory to estimate Late Glacial site catchment areas from a central place: The case of eastern Cantabria, Spain”, Journal of Anthropological Archaeology 28(1), 27–36. https://doi.org/10.1016/j.jaa.2008.11.001'}),
  'llobera-sluckin':common('llobera-sluckin',{author:'Marcos Llobera y T. J. Sluckin desarrollaron un modelo teórico para analizar estrategias de movimiento en pendientes y la eficiencia energética de recorridos en zigzag.',purpose:'Estima el coste metabólico del desplazamiento en función de la pendiente.',formula:'a=|s|. E=(2,635+17,37a+42,37a²−21,43a³+14,93a⁴) kJ/m. Energía del paso=distancia·E·multiplicadores generales.',variables:['s: pendiente firmada; a=|s|.','Distancia del paso y multiplicadores generales.'],editable:['Los coeficientes permanecen fijos.','Conectividad, barreras y facilitadores.'],limits:['La variante MoveCost usa |s| y asigna el mismo coste base a ascensos y descensos equivalentes.','Es coste energético, no tiempo.','Los trazados zigzag dependen también de resolución, conectividad y alternativas espaciales.','No incorpora fatiga acumulada, clima ni variabilidad fisiológica individual.'],reference:'Llobera, M. & Sluckin, T. J. (2007), “Zigzagging: Theoretical insights on climbing strategies”, Journal of Theoretical Biology 249(2), 206–217. https://doi.org/10.1016/j.jtbi.2007.07.020'}),
};
