import type { ModelId } from '../types';

export interface Transition { horizontalDistanceM:number; surfaceDistanceM:number; elevationFromM:number; elevationToM:number; signedSlope:number; terrainMultiplier:number; isBarrier:boolean; criticalSlopePercent?:number }
export interface CostModel { id:ModelId; name:string; family:string; unit:string; directional:boolean; description:string; citation:string; transitionCost(t:Transition):number }
const speedCost=(speedKmh:number,t:Transition)=>t.surfaceDistanceM/Math.max(speedKmh/3.6,1e-9);
const degrees=(slope:number)=>Math.atan(Math.abs(slope))*180/Math.PI;
const timeModel=(definition:Omit<CostModel,'transitionCost'>,speed:(t:Transition)=>number):CostModel=>({...definition,transitionCost:t=>t.isBarrier?Infinity:speedCost(speed(t),t)});
const metabolicModel=(definition:Omit<CostModel,'transitionCost'>,joulesPerKgM:(t:Transition)=>number):CostModel=>({...definition,transitionCost:t=>t.isBarrier?Infinity:joulesPerKgM(t)*t.surfaceDistanceM});

export const MODELS:Record<ModelId,CostModel>={
  tobler:timeModel({id:'tobler',name:'Tobler por caminos',family:'Tiempo de marcha',unit:'s',directional:true,description:'Velocidad de marcha según pendiente firmada.',citation:'Tobler (1993), NCGIA 93-1'},t=>6*Math.exp(-3.5*Math.abs(t.signedSlope+.05))/t.terrainMultiplier),
  'tobler-off':timeModel({id:'tobler-off',name:'Tobler campo a través',family:'Tiempo de marcha',unit:'s',directional:true,description:'Velocidad de Tobler multiplicada por 0,6.',citation:'Tobler (1993), NCGIA 93-1'},t=>6*Math.exp(-3.5*Math.abs(t.signedSlope+.05))*.6),
  'marquez-perez':timeModel({id:'marquez-perez',name:'Márquez-Pérez',family:'Senderos naturales',unit:'s',directional:true,description:'Ajuste empírico para senderos en espacios naturales.',citation:'Márquez-Pérez et al. (2017), DOI 10.1080/00167223.2017.1316212'},t=>4.8*Math.exp(-5.3*Math.abs(t.signedSlope*.7+.03))/t.terrainMultiplier),
  'kondo-seino':timeModel({id:'kondo-seino',name:'Kondo–Seino',family:'Tiempo de marcha',unit:'s',directional:true,description:'Diferencia los descensos de más del 7 %.',citation:'Kondo & Seino (2010), CAA 2009'},t=>5.1*Math.exp((t.signedSlope>=-.07?-2.25:-1.5)*Math.abs(t.signedSlope+.07))/t.terrainMultiplier),
  rees:timeModel({id:'rees',name:'Rees',family:'Terreno montañoso',unit:'s',directional:false,description:'Velocidad para desplazamiento en terreno montañoso.',citation:'Rees (2004), Computers & Geosciences 30(3), 203–209'},t=>(1/(.75+.09*Math.abs(t.signedSlope)+14.6*Math.abs(t.signedSlope)**2))*3.6/t.terrainMultiplier),
  gkrs:timeModel({id:'gkrs',name:'Garmy–Kaddouri–Rozenblat–Schneider',family:'Tiempo de marcha',unit:'s',directional:false,description:'Función exponencial de la pendiente angular.',citation:'Garmy et al.; formulación documentada por Herzog (2020)'},t=>4*Math.exp(-.008*degrees(t.signedSlope)**2)/t.terrainMultiplier),
  tripcevich:timeModel({id:'tripcevich',name:'Tripcevich',family:'Caravanas de llamas',unit:'s',directional:false,description:'Velocidad estimada para caravanas de llamas.',citation:'Tripcevich (2008), Estimating Llama Caravan Travel Speeds'},t=>(4.028*46**2)/((degrees(t.signedSlope)+4.127)**2+46**2)/t.terrainMultiplier),
  alberti:timeModel({id:'alberti',name:'Alberti pastoral',family:'Desplazamiento pastoral',unit:'s',directional:true,description:'Tobler reescalado a velocidad de rebaño.',citation:'Alberti (2019), SoftwareX 10, 100331'},t=>6*Math.exp(-3.5*Math.abs(t.signedSlope+.05))*.25),
  pandolf:{id:'pandolf',name:'Pandolf',family:'Energía metabólica',unit:'J',directional:false,description:'70 kg, sin carga, 1,2 m/s y terreno configurable.',citation:'Pandolf, Givoni & Goldman (1977), DOI 10.1152/jappl.1977.43.4.577',transitionCost:t=>{if(t.isBarrier)return Infinity;const W=70,L=0,V=1.2,N=t.terrainMultiplier,M=1.5*W+2*(W+L)*(L/W)**2+N*(W+L)*(1.5*V**2+.35*V*Math.abs(t.signedSlope)*100);return M*t.surfaceDistanceM/V}},
  'pandolf-corrected':{id:'pandolf-corrected',name:'Pandolf corregido para descenso',family:'Energía metabólica',unit:'J',directional:true,description:'Aplica la corrección de Yokota solo en descenso.',citation:'Pandolf et al. (1977); Yokota et al. (2004), USARIEM T04-09',transitionCost:t=>{if(t.isBarrier)return Infinity;const W=70,L=0,V=1.2,N=t.terrainMultiplier,G=Math.abs(t.signedSlope)*100;const M=1.5*W+2*(W+L)*(L/W)**2+N*(W+L)*(1.5*V**2+.35*V*G);const CF=N*(G*(W+L)*V/3.5)-((W+L)*(G+6)**2/W)+(25-V**2);return Math.max(1,t.signedSlope>=0?M:M-CF)*t.surfaceDistanceM/V}},
  minetti:metabolicModel({id:'minetti',name:'Minetti',family:'Energía metabólica',unit:'J/kg',directional:false,description:'Polinomio de marcha; dominio recomendado de pendiente −0,5 a 0,5.',citation:'Minetti et al. (2002), Journal of Applied Physiology 93, 1039–1046'},t=>{const x=Math.abs(t.signedSlope);return(280.5*x**5-58.7*x**4-76.8*x**3+51.9*x**2+19.6*x+2.5)*t.terrainMultiplier}),
  herzog:metabolicModel({id:'herzog',name:'Herzog',family:'Energía metabólica',unit:'J/kg',directional:false,description:'Aproximación polinómica estable de sexto grado a Minetti.',citation:'Herzog (2016), Potential and Limits of Optimal Path Analysis'},t=>{const x=Math.abs(t.signedSlope);return(1337.8*x**6+278.19*x**5-517.39*x**4-78.199*x**3+93.419*x**2+19.825*x+1.64)*t.terrainMultiplier}),
  ardigo:metabolicModel({id:'ardigo',name:'Ardigò',family:'Caminar, correr o bicicleta',unit:'J/kg',directional:false,description:'Coste locomotor a 1,2 m/s; la velocidad configurable se incorporará en una fase posterior.',citation:'Ardigò, Saibene & Minetti (2003), Eur J Appl Physiol 90, 365–371'},t=>{const x=Math.abs(t.signedSlope),V=1.2;return(1.866*Math.exp(4.911*x)*V**2-3.773*Math.exp(3.416*x)*V+45.71*x**2+18.9*x+4.456)*t.terrainMultiplier}),
  wheeled:{id:'wheeled',name:'Vehículo con pendiente crítica',family:'Vehículo',unit:'coste relativo',directional:false,description:'La pendiente crítica controla el crecimiento cuadrático del coste; no es una barrera.',citation:'Herzog (2016), Potential and Limits of Optimal Path Analysis',transitionCost:t=>t.isBarrier?Infinity:t.surfaceDistanceM*(1+(Math.abs(t.signedSlope)*100/(t.criticalSlopePercent??10))**2)*t.terrainMultiplier},
  eastman:{id:'eastman',name:'Eastman',family:'Coste abstracto',unit:'coste relativo',directional:false,description:'Coste cuadrático basado en la pendiente angular.',citation:'Eastman (1999); formulación en Vaissié (2021)',transitionCost:t=>{const a=degrees(t.signedSlope);return t.isBarrier?Infinity:t.surfaceDistanceM*(.031*a*a-.025*a+1)*t.terrainMultiplier}},
};
