/** Canonical, explicitly ordered Credits component list shared by every desktop target. */
export const SOFTWARE_CREDITS: readonly (readonly [string,string,string])[] = [
  ['React, React DOM y Scheduler','React, React DOM and Scheduler','MIT'],['OpenLayers','OpenLayers','BSD-2-Clause'],['Three.js','Three.js','MIT'],['jsPDF y sus componentes de renderizado','jsPDF and its rendering components','MIT y licencias compatibles'],
  ['GeoTIFF.js y códecs raster','GeoTIFF.js and raster codecs','MIT, Apache-2.0, BSD, Zlib y CC0'],['API JavaScript de Tauri y Dialog','Tauri and Dialog JavaScript APIs','Apache-2.0 OR MIT'],
  ['base64 0.22.1 (Rust)','base64 0.22.1 (Rust)','MIT'],
  ['futures-util 0.3.34 (Rust)','futures-util 0.3.34 (Rust)','MIT'],
  ['reqwest 0.12.28 (Rust)','reqwest 0.12.28 (Rust)','MIT'],
  ['serde 1.0.229 (Rust)','serde 1.0.229 (Rust)','MIT'],
  ['serde_json 1.0.151 (Rust)','serde_json 1.0.151 (Rust)','MIT'],
  ['tauri 2.11.5 (Rust)','tauri 2.11.5 (Rust)','MIT'],
  ['tauri-plugin-dialog 2.7.2 (Rust)','tauri-plugin-dialog 2.7.2 (Rust)','MIT'],
  ['thiserror 2.0.20 (Rust)','thiserror 2.0.20 (Rust)','MIT'],
  ['tokio 1.53.1 (Rust)','tokio 1.53.1 (Rust)','MIT'],
  ['url 2.5.8 (Rust)','url 2.5.8 (Rust)','MIT'],
  ['uuid 1.24.1 (Rust)','uuid 1.24.1 (Rust)','MIT'],
  ['@napi-rs/lzma-linux-x64-gnu 1.5.1 (build Linux)','@napi-rs/lzma-linux-x64-gnu 1.5.1 (Linux build)','MIT'],
  ['lerc 3.0.0','lerc 3.0.0','Apache-2.0'],
  ['stackback 0.0.2 (tests)','stackback 0.0.2 (tests)','MIT; formatstack.js: BSD-3-Clause'],
  ['libappindicator-sys 0.9.0 (Linux)','libappindicator-sys 0.9.0 (Linux)','MIT'],
  ['r-efi 5.3.0 y 6.0.0 (UEFI)','r-efi 5.3.0 and 6.0.0 (UEFI)','MIT'],
  ['selectors 0.36.1','selectors 0.36.1','MPL-2.0; GPL-3.0-only vía §3.3'],
  ['winapi-i686/x86_64-pc-windows-gnu 0.4.0 (Windows)','winapi-i686/x86_64-pc-windows-gnu 0.4.0 (Windows)','MIT'],
  ['Dependencias transitivas Rust','Transitive Rust dependencies','MIT, Apache-2.0, MPL-2.0, ISC, Unicode-3.0, CDLA-Permissive-2.0…'],['GDAL','GDAL','MIT/X'],['PROJ','PROJ','MIT'],
] as const;
