import type { EnabledCrossing, PointOfInterest, PreferredCorridor } from '../types';

const coordinate=(value:unknown):value is [number,number]=>Array.isArray(value)&&value.length>=2&&Number.isFinite(value[0])&&Number.isFinite(value[1])&&value[0]>=-180&&value[0]<=180&&value[1]>=-90&&value[1]<=90;
export function validateCorridor(value:PreferredCorridor){if(!value.name.trim())throw new Error('El corredor debe tener nombre');if(value.coordinates.length<2||!value.coordinates.every(coordinate))throw new Error('La geometría del corredor no es válida');if(!Number.isFinite(value.widthM)||value.widthM<=0)throw new Error('La anchura del corredor debe ser positiva');if(!Number.isFinite(value.costMultiplier)||value.costMultiplier<=0||value.costMultiplier>1)throw new Error('El multiplicador del corredor debe ser mayor que 0 y menor o igual que 1');return value}
export function validateCrossing(value:EnabledCrossing){if(!value.name.trim())throw new Error('El paso debe tener nombre');if(value.coordinates.length<2||!value.coordinates.every(coordinate))throw new Error('La geometría del paso no es válida');if(!Number.isFinite(value.crossingCostMultiplier)||value.crossingCostMultiplier<=0)throw new Error('El coste del paso debe ser estrictamente positivo');return value}
export function influenceMultiplier(distanceM:number,point:PointOfInterest){if(point.influenceRadiusM<=0||point.attraction<0||point.attraction>=1)throw new Error('La influencia del punto no es válida');const ratio=Math.max(0,1-distanceM/point.influenceRadiusM);return 1-point.attraction*ratio}
export function applyBoundedMultiplier(baseCost:number,multiplier:number){if(!Number.isFinite(baseCost)||baseCost<=0||!Number.isFinite(multiplier)||multiplier<=0)throw new Error('El coste y su multiplicador deben ser positivos');return baseCost*multiplier}
// Distancia ortodrómica en metros mediante haversine. Radio terrestre medio 6 371 008,8 m.
// Referencia: Sinnott, R. W. (1984), “Virtues of the Haversine”, Sky and Telescope 68(2), 159.
export function geodesicDistanceM(from:readonly [number,number],to:readonly [number,number]){const radians=Math.PI/180,lat1=from[1]*radians,lat2=to[1]*radians,deltaLat=(to[1]-from[1])*radians,deltaLon=(to[0]-from[0])*radians,a=Math.sin(deltaLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(deltaLon/2)**2;return 6_371_008.8*2*Math.atan2(Math.sqrt(a),Math.sqrt(Math.max(0,1-a)))}
export function orderWaypointsByProximity<T extends {coordinate:readonly [number,number]}>(start:readonly [number,number],waypoints:readonly T[]){const remaining=[...waypoints],ordered:T[]=[];let current=start;while(remaining.length){let nearest=0,distance=geodesicDistanceM(current,remaining[0].coordinate);for(let index=1;index<remaining.length;index++){const candidate=geodesicDistanceM(current,remaining[index].coordinate);if(candidate<distance){nearest=index;distance=candidate}}const[next]=remaining.splice(nearest,1);ordered.push(next);current=next.coordinate}return ordered}
export function validatePointOfInterest(value:PointOfInterest){if(!value.name.trim()||!value.category.trim())throw new Error('El punto de interés debe tener nombre y categoría');if(!coordinate(value.coordinate))throw new Error('Las coordenadas del punto de interés no son válidas');if(!Number.isFinite(value.influenceRadiusM)||value.influenceRadiusM<=0)throw new Error('El radio de influencia debe ser positivo');if(!Number.isFinite(value.attraction)||value.attraction<0||value.attraction>=1)throw new Error('La atracción debe estar entre 0 y 1, sin alcanzar 1');if(!['influence','single-visit','waypoint'].includes(value.mode))throw new Error('La modalidad del punto de interés no es válida');return value}
export function exportFacilitatorsGeoJson(corridors:readonly PreferredCorridor[],crossings:readonly EnabledCrossing[],points:readonly PointOfInterest[]=[]){return JSON.stringify({type:'FeatureCollection',name:'Facilitadores ViaSpania',crs:{type:'name',properties:{name:'urn:ogc:def:crs:OGC:1.3:CRS84'}},features:[...corridors.map(item=>({type:'Feature',id:item.id,properties:{viaspania_type:'preferred_corridor',name:item.name,width_m:item.widthM,cost_multiplier:item.costMultiplier},geometry:{type:'LineString',coordinates:item.coordinates}})),...crossings.map(item=>({type:'Feature',id:item.id,properties:{viaspania_type:'enabled_crossing',name:item.name,crossing_kind:item.kind,cost_multiplier:item.crossingCostMultiplier,barrier_id:item.barrierId??null,required:item.required===true},geometry:{type:'LineString',coordinates:item.coordinates}})),...points.map(item=>({type:'Feature',id:item.id,properties:{viaspania_type:'point_of_interest',name:item.name,category:item.category,influence_radius_m:item.influenceRadiusM,attraction:item.attraction,mode:item.mode},geometry:{type:'Point',coordinates:item.coordinate}}))]},null,2)}
export function parseFacilitatorsGeoJson(text:string){const data=JSON.parse(text);if(data?.type!=='FeatureCollection'||!Array.isArray(data.features))throw new Error('El archivo no es una colección GeoJSON válida');const corridors:PreferredCorridor[]=[],crossings:EnabledCrossing[]=[],points:PointOfInterest[]=[];for(const [index,feature] of data.features.entries()){const p=feature?.properties??{},id=String(feature?.id??`element-${index+1}`),name=String(p.name??`Elemento ${index+1}`);if(feature?.geometry?.type==='LineString'){const coordinates=feature.geometry.coordinates as [number,number][];if(p.viaspania_type==='preferred_corridor')corridors.push(validateCorridor({id,name,coordinates,widthM:Number(p.width_m),costMultiplier:Number(p.cost_multiplier)}));else if(p.viaspania_type==='enabled_crossing')crossings.push(validateCrossing({id,name,coordinates,kind:p.crossing_kind,crossingCostMultiplier:Number(p.cost_multiplier),required:p.required===true,barrierId:p.barrier_id?String(p.barrier_id):undefined}))}else if(feature?.geometry?.type==='Point'&&p.viaspania_type==='point_of_interest')points.push(validatePointOfInterest({id,name,category:String(p.category??'sin categoría'),coordinate:feature.geometry.coordinates,influenceRadiusM:Number(p.influence_radius_m),attraction:Number(p.attraction),mode:p.mode}));}return{corridors,crossings,points}}

/** Greedy proximity order, as for POIs; crossing vertices stay consecutive. */
export function requiredRouteWaypoints(start:readonly [number,number],points:readonly PointOfInterest[],crossings:readonly EnabledCrossing[]){
 const remaining=[...points.filter(point=>point.mode==='waypoint').map(point=>({id:point.id,name:point.name,coordinates:[point.coordinate]})),...crossings.filter(crossing=>crossing.required===true).map(crossing=>{validateCrossing(crossing);return{id:crossing.id,name:crossing.name,coordinates:crossing.coordinates}})];
 const ordered:{id:string;name:string;coordinate:[number,number]}[]=[];
 let current=start;
 while(remaining.length){
  const candidates=remaining.flatMap((item,index)=>[{index,reverse:false,coordinate:item.coordinates[0]},...(item.coordinates.length>1?[{index,reverse:true,coordinate:item.coordinates.at(-1)!}]:[])]);
  const next=orderWaypointsByProximity(current,candidates)[0],item=remaining.splice(next.index,1)[0];
  const coordinates=next.reverse?[...item.coordinates].reverse():item.coordinates;
  for(const coordinate of coordinates)ordered.push({id:item.id,name:item.name,coordinate:[...coordinate]});
  current=coordinates.at(-1)!;
 }
 return ordered;
}
