function palette(){const result:number[]=[];for(let index=0;index<256;index++)result.push(((index>>5)&7)*255/7,((index>>2)&7)*255/7,(index&3)*255/3);return result.map(Math.round)}
function indexed(pixels:Uint8ClampedArray){const output=new Uint8Array(pixels.length/4);for(let i=0;i<output.length;i++){const o=i*4;output[i]=(pixels[o]>>5)<<5|(pixels[o+1]>>5)<<2|(pixels[o+2]>>6)}return output}
function lzw(data:Uint8Array){const clear=256,end=257,codes:number[]=[];for(let index=0;index<data.length;index+=250)codes.push(clear,...data.subarray(index,index+250));codes.push(end);let buffer=0,bits=0;const packed:number[]=[];for(const code of codes){buffer|=code<<bits;bits+=9;while(bits>=8){packed.push(buffer&255);buffer>>=8;bits-=8}}if(bits)packed.push(buffer&255);const bytes:number[]=[8];for(let index=0;index<packed.length;index+=255)bytes.push(Math.min(255,packed.length-index),...packed.slice(index,index+255));bytes.push(0);return bytes}
const word=(value:number)=>[value&255,value>>8&255];
function append(target:number[],values:readonly number[]){for(let index=0;index<values.length;index+=8192)target.push(...values.slice(index,index+8192))}
export class GifEncoder {
 private readonly chunks:Uint8Array[]=[];private frameCount=0;
 constructor(private readonly width:number,private readonly height:number,private readonly delayMs:number){this.chunks.push(Uint8Array.from([71,73,70,56,57,97,...word(width),...word(height),247,0,0,...palette(),33,255,11,...Array.from('NETSCAPE2.0').map(c=>c.charCodeAt(0)),3,1,0,0,0]))}
 addFrame(frame:ImageData){if(frame.width!==this.width||frame.height!==this.height)throw new Error('Todos los fotogramas del GIF deben tener el mismo tamaño.');const delay=Math.min(65535,Math.max(2,Math.round(this.delayMs/10))),out:number[]=[33,249,4,0,...word(delay),0,0,44,0,0,0,0,...word(this.width),...word(this.height),0];append(out,lzw(indexed(frame.data)));this.chunks.push(Uint8Array.from(out));this.frameCount++}
 finish(){if(!this.frameCount)throw new Error('No hay fotogramas para crear el GIF.');this.chunks.push(Uint8Array.of(59));const size=this.chunks.reduce((sum,item)=>sum+item.length,0),result=new Uint8Array(size);let offset=0;for(const chunk of this.chunks){result.set(chunk,offset);offset+=chunk.length}return result}
}
export function encodeGif(frames:ImageData[],delayMs:number){if(!frames.length)throw new Error('No hay fotogramas para crear el GIF.');const encoder=new GifEncoder(frames[0].width,frames[0].height,delayMs);frames.forEach(frame=>encoder.addFrame(frame));return encoder.finish()}
