// @vitest-environment jsdom
import {act,cleanup,fireEvent,render,screen} from '@testing-library/react';
import {useState} from 'react';
import {afterEach,describe,expect,it} from 'vitest';
import {LocalizationBoundary,setLanguage,translateText} from './i18n';
afterEach(()=>cleanup());
describe('localización',()=>{
  it('traduce la interfaz y permite volver al español',()=>{setLanguage('es');render(<LocalizationBoundary><button aria-label="Configuración">Nuevo proyecto</button></LocalizationBoundary>);act(()=>setLanguage('en'));expect(screen.getByRole('button',{name:'Settings'}).textContent).toBe('New project');act(()=>setLanguage('es'));expect(screen.getByRole('button',{name:'Configuración'}).textContent).toBe('Nuevo proyecto')});
  it('traduce nodos y atributos que React actualiza después del montaje',async()=>{function Dynamic(){const[done,setDone]=useState(false);return <button aria-label={done?'Cerrar ayuda':'Configuración'} onClick={()=>setDone(true)}>{done?'Calcular matriz multipunto':'Nuevo proyecto'}</button>}setLanguage('en');render(<LocalizationBoundary><Dynamic/></LocalizationBoundary>);expect(screen.getByRole('button',{name:'Settings'}).textContent).toBe('New project');fireEvent.click(screen.getByRole('button'));await screen.findByRole('button',{name:'Close help'});expect(screen.getByRole('button').textContent).toBe('Calculate multipoint matrix');setLanguage('es')});
  it('traduce texto técnico dinámico sin producir frases híbridas',()=>{setLanguage('en');expect(translateText('Coste acumulado: 12 J · Página 1 de 2')).toBe('Accumulated cost: 12 J · Page 1 of 2');expect(translateText('Ruta de vuelta · Tobler')).toBe('Return route · Tobler');expect(translateText('48.0 GB de memoria detectada')).toBe('48.0 GB of memory detected');expect(translateText('Límite recomendado: 5.000.000 celdas')).toBe('Recommended limit: 5.000.000 cells');expect(translateText('Informe de Ruta simple')).toBe('Simple route report');expect(translateText('Visor 3D preparado: 200 × 150 vértices.')).toBe('3D viewer ready: 200 × 150 vertices.');expect(translateText('MDT05 cargado y reproyectado a EPSG:25830: 12 MB')).toBe('MDT05 loaded and reprojected to EPSG:25830: 12 MB');expect(translateText('Ruta subóptima ida · rango 2 · +8.0 % · 65 % compartido')).toBe('Outbound sub-optimal route · rank 2 · +8.0 % · 65 % shared');expect(translateText('Itinerario subóptimo completo · rango 3')).toBe('Complete sub-optimal itinerary · rank 3');expect(translateText('Pasillo LCP calculado: 1,250 celdas · umbral 20 % · superficie preparada')).toBe('LCP corridor calculated: 1,250 cells · threshold 20 % · prepared surface');expect(translateText('Perfil: Tobler por caminos')).toBe('Profile: Tobler on paths');expect(translateText('Curvas · intervalo 20 m')).toBe('Contours · interval 20 m');expect(translateText('3.000.000 · recomendado · 9–16 GB')).toBe('3,000,000 · recommended · 9–16 GB');setLanguage('es')});
});
