// @vitest-environment jsdom
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import App from './App';
vi.mock('./services/gazetteer',()=>({projectCoordinate:vi.fn(async()=>({crs:'EPSG:3857',coordinate:[0,0]})),gazetteer:{search:vi.fn()}}));
vi.mock('./components/MapPanel',()=>({MapPanel:({kind,placeMarkerCoordinates,selectionMarkerCoordinate,onPointerCoordinate}:{kind:string;placeMarkerCoordinates:unknown;selectionMarkerCoordinate:unknown;onPointerCoordinate:(coordinate:{lon:number;lat:number}|null)=>void})=><div data-testid={`map-${kind}`}><output data-testid={`place-${kind}`}>{JSON.stringify(placeMarkerCoordinates)}</output><output data-testid={`cursor-${kind}`}>{JSON.stringify(selectionMarkerCoordinate)}</output><button aria-label={`Mover cursor ${kind}`} onClick={()=>onPointerCoordinate({lon:2,lat:42})}/><button aria-label={`Salir ${kind}`} onClick={()=>onPointerCoordinate(null)}/></div>}));
vi.mock('./components/MdtMapPanel',()=>({MdtMapPanel:()=>null}));
vi.mock('./components/WelcomeDialog',()=>({WelcomeDialog:()=>null}));
vi.mock('./components/AppTutorial',()=>({AppTutorial:()=>null}));
afterEach(()=>{cleanup();localStorage.removeItem('viaspania.settings.v1')});
it('conserva el lugar al mover el cursor sincronizado y lo elimina desde la búsqueda',async()=>{
 localStorage.setItem('viaspania.settings.v1',JSON.stringify({showSelectionMarker:true}));
 render(<App/>);
 fireEvent.click(screen.getByRole('button',{name:'Buscar lugar'}));
 fireEvent.change(screen.getByRole('combobox',{name:'Buscar lugar'}),{target:{value:'40,-3'}});
 fireEvent.keyDown(screen.getByRole('combobox',{name:'Buscar lugar'}),{key:'Enter'});
 await screen.findByRole('button',{name:'Borrar lugar'});
 fireEvent.click(screen.getByRole('button',{name:'Cerrar búsqueda de lugar'}));
 for(const kind of ['osm','pnoa','historical'])expect(screen.getByTestId(`place-${kind}`).textContent).toBe('[{"lon":-3,"lat":40}]');
 fireEvent.click(screen.getByRole('button',{name:'Mover cursor osm'}));
 await waitFor(()=>expect(screen.getByTestId('cursor-pnoa').textContent).toBe('{"lon":2,"lat":42}'));
 expect(screen.getByTestId('cursor-historical').textContent).toBe('{"lon":2,"lat":42}');
 expect(screen.getByTestId('place-pnoa').textContent).toBe('[{"lon":-3,"lat":40}]');
 fireEvent.click(screen.getByRole('button',{name:'Salir osm'}));
 expect(screen.getByTestId('cursor-pnoa').textContent).toBe('null');
 expect(screen.getByTestId('place-pnoa').textContent).toBe('[{"lon":-3,"lat":40}]');
 fireEvent.click(screen.getByRole('button',{name:'Buscar lugar'}));
 fireEvent.change(screen.getByRole('combobox',{name:'Buscar lugar'}),{target:{value:'41,-4'}});
 fireEvent.keyDown(screen.getByRole('combobox',{name:'Buscar lugar'}),{key:'Enter'});
 await waitFor(()=>expect(screen.getAllByRole('button',{name:'Borrar lugar'})).toHaveLength(2));
 for(const kind of ['osm','pnoa','historical'])expect(screen.getByTestId(`place-${kind}`).textContent).toBe('[{"lon":-3,"lat":40},{"lon":-4,"lat":41}]');
 fireEvent.click(screen.getAllByRole('button',{name:'Ocultar en el mapa'})[0]);
 for(const kind of ['osm','pnoa','historical'])expect(screen.getByTestId(`place-${kind}`).textContent).toBe('[{"lon":-4,"lat":41}]');
 expect(screen.getAllByRole('button',{name:'Borrar lugar'})).toHaveLength(2);
 fireEvent.click(screen.getByRole('button',{name:'Cerrar búsqueda de lugar'}));
 fireEvent.click(screen.getByRole('button',{name:'Buscar lugar'}));
 fireEvent.click(screen.getByRole('button',{name:'Mostrar en el mapa'}));
 for(const kind of ['osm','pnoa','historical'])expect(screen.getByTestId(`place-${kind}`).textContent).toBe('[{"lon":-3,"lat":40},{"lon":-4,"lat":41}]');
 fireEvent.click(screen.getAllByRole('button',{name:'Ocultar en el mapa'})[0]);
 fireEvent.click(screen.getAllByRole('button',{name:'Borrar lugar'})[0]);
 for(const kind of ['osm','pnoa','historical'])expect(screen.getByTestId(`place-${kind}`).textContent).toBe('[{"lon":-4,"lat":41}]');
 fireEvent.click(screen.getByRole('button',{name:'Borrar lugar'}));
 for(const kind of ['osm','pnoa','historical'])expect(screen.getByTestId(`place-${kind}`).textContent).toBe('[]');
});
